USE finex_db;

SET NAMES utf8mb4;

DROP TABLE IF EXISTS gl_accvouch;
DROP TABLE IF EXISTS gl_accsum;
DROP TABLE IF EXISTS gl_accass;

CREATE TABLE gl_accvouch (
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '自动编号',
    iperiod TINYINT COMMENT '会计期间',
    csign VARCHAR(64) COMMENT '凭证类别字',
    isignseq INT COMMENT '凭证类别排序号',
    ino_id SMALLINT COMMENT '凭证编号',
    inid SMALLINT COMMENT '行号',
    dbill_date DATETIME COMMENT '制单日期',
    idoc SMALLINT COMMENT '附单据数',
    cbill VARCHAR(64) COMMENT '制单人',
    ccheck VARCHAR(64) COMMENT '审核人',
    cbook VARCHAR(64) COMMENT '记账人',
    ibook TINYINT COMMENT '记账标志',
    ccashier VARCHAR(64) COMMENT '出纳签字人',
    iflag TINYINT COMMENT '凭证标志',
    ctext1 VARCHAR(255) COMMENT '凭证头自定义项1',
    ctext2 VARCHAR(255) COMMENT '凭证头自定义项2',
    cdigest VARCHAR(255) COMMENT '摘要',
    ccode VARCHAR(64) COMMENT '科目编码',
    ccode_name VARCHAR(128) COMMENT '科目名称',
    cexch_name VARCHAR(32) COMMENT '币种名称',
    md DECIMAL(18,2) COMMENT '借方金额',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    md_f DECIMAL(18,2) COMMENT '外币借方金额',
    mc_f DECIMAL(18,2) COMMENT '外币贷方金额',
    nfrat DECIMAL(18,6) COMMENT '汇率',
    nd_s DECIMAL(18,6) COMMENT '数量借方',
    nc_s DECIMAL(18,6) COMMENT '数量贷方',
    csettle VARCHAR(64) COMMENT '结算方式编码',
    cn_id VARCHAR(64) COMMENT '票据号',
    dt_date DATETIME COMMENT '票号发生日期',
    cdept_id VARCHAR(64) COMMENT '部门编码',
    cperson_id VARCHAR(64) COMMENT '职员编码',
    ccus_id VARCHAR(64) COMMENT '客户编码',
    csup_id VARCHAR(64) COMMENT '供应商编码',
    citem_id VARCHAR(6) COMMENT '项目编码',
    citem_class VARCHAR(2) COMMENT '项目大类编码',
    cash_flow_item_id BIGINT COMMENT '现金流量档案ID',
    cash_flow_item_name VARCHAR(200) COMMENT '现金流量名称快照',
    cname VARCHAR(64) COMMENT '业务员',
    ccode_equal VARCHAR(64) COMMENT '对方科目编码',
    iflagbank TINYINT COMMENT '银行账两清标志',
    iflagPerson TINYINT COMMENT '往来账两清标志',
    bdelete TINYINT(1) COMMENT '是否核销',
    coutaccset VARCHAR(64) COMMENT '外部凭证账套号',
    ioutyear SMALLINT COMMENT '外部凭证会计年度',
    coutsysname VARCHAR(255) COMMENT '外部凭证系统名称',
    coutsysver VARCHAR(255) COMMENT '外部凭证系统版本号',
    doutbilldate DATETIME COMMENT '外部凭证制单日期',
    ioutperiod TINYINT COMMENT '外部凭证会计期间',
    coutsign VARCHAR(64) COMMENT '外部凭证业务类型',
    coutno_id VARCHAR(64) COMMENT '外部凭证业务号',
    doutdate DATETIME COMMENT '外部凭证单据日期',
    coutbillsign VARCHAR(64) COMMENT '外部凭证单据类型',
    coutid VARCHAR(64) COMMENT '外部凭证单据号',
    bvouchedit TINYINT(1) COMMENT '凭证是否可修改',
    bvouchAddordele TINYINT(1) COMMENT '凭证分录是否可增删',
    bvouchmoneyhold TINYINT(1) COMMENT '凭证合计金额是否保值',
    bvalueedit TINYINT(1) COMMENT '分录数值是否可修改',
    bcodeedit TINYINT(1) COMMENT '分录科目是否可修改',
    ccodecontrol VARCHAR(32) COMMENT '分录受控科目可用状态',
    bPCSedit TINYINT(1) COMMENT '分录往来项是否可修改',
    bDeptedit TINYINT(1) COMMENT '分录部门是否可修改',
    bItemedit TINYINT(1) COMMENT '分录项目是否可修改',
    bCusSupInput TINYINT(1) COMMENT '分录往来项是否必输',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    cDefine1 VARCHAR(255) COMMENT '自定义项1',
    cDefine2 VARCHAR(255) COMMENT '自定义项2',
    cDefine3 VARCHAR(255) COMMENT '自定义项3',
    cDefine4 DATETIME COMMENT '自定义项4',
    cDefine5 INT COMMENT '自定义项5',
    PRIMARY KEY (i_id),
    KEY idx_gl_accvouch_company_id (company_id),
    KEY idx_gl_accvouch_iperiod (iperiod),
    KEY idx_gl_accvouch_ccode (ccode),
    KEY idx_gl_accvouch_ino_id (ino_id),
    KEY idx_gl_accvouch_dbill_date (dbill_date),
    KEY idx_gl_accvouch_ccus_id (ccus_id),
    KEY idx_gl_accvouch_csup_id (csup_id),
    KEY idx_gl_accvouch_cperson_id (cperson_id),
    KEY idx_gl_accvouch_cdept_id (cdept_id),
    KEY idx_gl_accvouch_citem_id (citem_id),
    KEY idx_gl_accvouch_company_ccode (company_id, ccode),
    KEY idx_gl_accvouch_company_cperson (company_id, cperson_id),
    KEY idx_gl_accvouch_company_ccus (company_id, ccus_id),
    KEY idx_gl_accvouch_company_csup (company_id, csup_id),
    KEY idx_gl_accvouch_company_citem_class (company_id, citem_class),
    KEY idx_gl_accvouch_company_citem_id (company_id, citem_id),
    KEY idx_gl_accvouch_company_citem_class_id (company_id, citem_class, citem_id),
    KEY idx_gl_accvouch_company_cash_flow (company_id, cash_flow_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证及明细账';

CREATE TABLE gl_accsum (
    cbegind_c VARCHAR(32) COMMENT '金额期初方向',
    cbegind_c_engl VARCHAR(32) COMMENT '金额期初方向英文',
    ccode VARCHAR(64) COMMENT '科目编码',
    cendd_c VARCHAR(32) COMMENT '金额期末方向',
    cendd_c_engl VARCHAR(32) COMMENT '金额期末方向英文',
    cexch_name VARCHAR(32) COMMENT '币种名称',
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '自动编号',
    iperiod TINYINT COMMENT '会计期间',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    mb DECIMAL(18,2) COMMENT '金额期初',
    mb_f DECIMAL(18,2) COMMENT '外币期初',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    mc_f DECIMAL(18,2) COMMENT '外币贷方金额',
    md DECIMAL(18,2) COMMENT '借方金额',
    md_f DECIMAL(18,2) COMMENT '外币借方金额',
    me DECIMAL(18,2) COMMENT '金额期末',
    me_f DECIMAL(18,2) COMMENT '外币期末',
    nb_s DECIMAL(18,6) COMMENT '数量期初',
    nc_s DECIMAL(18,6) COMMENT '数量贷方',
    nd_s DECIMAL(18,6) COMMENT '数量借方',
    ne_s DECIMAL(18,6) COMMENT '数量期末',
    PRIMARY KEY (i_id),
    KEY idx_gl_accsum_company_id (company_id),
    KEY idx_gl_accsum_iperiod (iperiod),
    KEY idx_gl_accsum_ccode (ccode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科目总账';

CREATE TABLE gl_accass (
    cbegind_c VARCHAR(32) COMMENT '金额期初方向',
    cbegind_c_engl VARCHAR(32) COMMENT '金额期初方向英文',
    ccode VARCHAR(64) COMMENT '科目编码',
    ccus_id VARCHAR(64) COMMENT '客户编码',
    cdept_id VARCHAR(64) COMMENT '部门编码',
    cendd_c VARCHAR(32) COMMENT '金额期末方向',
    cendd_c_engl VARCHAR(32) COMMENT '金额期末方向英文',
    cexch_name VARCHAR(32) COMMENT '币种名称',
    citem_class VARCHAR(2) COMMENT '项目大类编码',
    citem_id VARCHAR(6) COMMENT '项目编码',
    cperson_id VARCHAR(64) COMMENT '职员编码',
    csup_id VARCHAR(64) COMMENT '供应商编码',
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '自动编号',
    iperiod TINYINT COMMENT '会计期间',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    mb DECIMAL(18,2) COMMENT '金额期初',
    mb_f DECIMAL(18,2) COMMENT '外币期初',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    mc_f DECIMAL(18,2) COMMENT '外币贷方金额',
    md DECIMAL(18,2) COMMENT '借方金额',
    md_f DECIMAL(18,2) COMMENT '外币借方金额',
    me DECIMAL(18,2) COMMENT '金额期末',
    me_f DECIMAL(18,2) COMMENT '外币期末',
    nb_s DECIMAL(18,6) COMMENT '数量期初',
    nc_s DECIMAL(18,6) COMMENT '数量贷方',
    nd_s DECIMAL(18,6) COMMENT '数量借方',
    ne_s DECIMAL(18,6) COMMENT '数量期末',
    PRIMARY KEY (i_id),
    KEY idx_gl_accass_company_id (company_id),
    KEY idx_gl_accass_iperiod (iperiod),
    KEY idx_gl_accass_ccode (ccode),
    KEY idx_gl_accass_ccus_id (ccus_id),
    KEY idx_gl_accass_csup_id (csup_id),
    KEY idx_gl_accass_cperson_id (cperson_id),
    KEY idx_gl_accass_cdept_id (cdept_id),
    KEY idx_gl_accass_citem_id (citem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='辅助总账';


CREATE TABLE IF NOT EXISTS gl_Customer (
    cCusCode VARCHAR(64) NOT NULL COMMENT '客户编码',
    cCusName VARCHAR(128) NOT NULL COMMENT '客户名称',
    cCusAbbName VARCHAR(64) NULL COMMENT '客户简称',
    cCCCode VARCHAR(64) NULL COMMENT '客户分类编码',
    cDCCode VARCHAR(64) NULL COMMENT '地区编码',
    cCusTradeCCode VARCHAR(64) NULL COMMENT '行业编码',
    cTrade VARCHAR(255) NULL COMMENT '所属行业',
    cCusAddress VARCHAR(255) NULL COMMENT '地址',
    cCusPostCode VARCHAR(16) NULL COMMENT '邮政编码',
    cCusRegCode VARCHAR(255) NULL COMMENT '纳税人登记号',
    cCusBank VARCHAR(128) NULL COMMENT '开户银行',
    cCusAccount VARCHAR(64) NULL COMMENT '银行账号',
    cCusLPerson VARCHAR(64) NULL COMMENT '法人',
    cCusPerson VARCHAR(64) NULL COMMENT '联系人',
    cCusHand VARCHAR(32) NULL COMMENT '手机',
    cCusCreGrade VARCHAR(255) NULL COMMENT '信用等级',
    iCusCreLine DECIMAL(18,2) NULL COMMENT '信用额度',
    iCusCreDate INT NULL COMMENT '信用期限',
    cCusOAddress VARCHAR(255) NULL COMMENT '发货地址',
    cCusOType VARCHAR(255) NULL COMMENT '发运方式',
    cCusHeadCode VARCHAR(64) NULL COMMENT '客户总公司编码',
    cCusWhCode VARCHAR(64) NULL COMMENT '发货仓库',
    cCusDepart VARCHAR(64) NULL COMMENT '分管部门',
    iARMoney DECIMAL(18,2) NULL COMMENT '应收余额',
    dLastDate DATETIME NULL COMMENT '最后交易日期',
    iLastMoney DECIMAL(18,2) NULL COMMENT '最后交易金额',
    dLRDate DATETIME NULL COMMENT '最后收款日期',
    iLRMoney DECIMAL(18,2) NULL COMMENT '最后收款金额',
    dEndDate DATETIME NULL COMMENT '停用日期',
    cCusBankCode VARCHAR(64) NULL COMMENT '所属银行编码',
    cCusDefine1 VARCHAR(255) NULL COMMENT '客户自定义项1',
    cCusDefine2 VARCHAR(255) NULL COMMENT '客户自定义项2',
    cCusDefine3 VARCHAR(255) NULL COMMENT '客户自定义项3',
    cCusDefine4 VARCHAR(255) NULL COMMENT '客户自定义项4',
    cCusDefine5 VARCHAR(255) NULL COMMENT '客户自定义项5',
    cCusDefine6 VARCHAR(255) NULL COMMENT '客户自定义项6',
    cCusDefine7 VARCHAR(255) NULL COMMENT '客户自定义项7',
    cCusDefine8 VARCHAR(255) NULL COMMENT '客户自定义项8',
    cCusDefine9 VARCHAR(255) NULL COMMENT '客户自定义项9',
    cCusDefine10 VARCHAR(255) NULL COMMENT '客户自定义项10',
    cCusDefine11 INT NULL COMMENT '客户自定义项11',
    cCusDefine12 INT NULL COMMENT '客户自定义项12',
    cCusDefine13 DECIMAL(18,2) NULL COMMENT '客户自定义项13',
    cCusDefine14 DECIMAL(18,2) NULL COMMENT '客户自定义项14',
    cCusDefine15 DATETIME NULL COMMENT '客户自定义项15',
    cCusDefine16 DATETIME NULL COMMENT '客户自定义项16',
    cInvoiceCompany VARCHAR(255) NULL COMMENT '开票单位',
    bCredit TINYINT DEFAULT 0 COMMENT '是否控制信用',
    bCreditDate TINYINT DEFAULT 0 COMMENT '是否控制信用期限',
    bCreditByHead TINYINT DEFAULT 0 COMMENT '是否按总公司控制信用',
    cMemo VARCHAR(255) NULL COMMENT '备注',
    fCommisionRate DECIMAL(18,2) NULL COMMENT '佣金比率(%)',
    fInsueRate DECIMAL(18,2) NULL COMMENT '保险费率(%)',
    CustomerKCode VARCHAR(64) NULL COMMENT '客户级别编码',
    bCusState TINYINT DEFAULT 0 COMMENT '是否成交',
    company_id VARCHAR(64) NULL COMMENT '公司主体编码',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (cCusCode),
    KEY idx_gl_Customer_name (cCusName),
    KEY idx_gl_Customer_company (company_id),
    KEY idx_gl_Customer_end_date (dEndDate),
    CONSTRAINT fk_gl_Customer_company_id FOREIGN KEY (company_id) REFERENCES sys_company(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户档案表';

-- comment standardization begin
ALTER TABLE gl_customer
    MODIFY COLUMN cCusCode varchar(64) NOT NULL COMMENT '客户编码',
    MODIFY COLUMN cCusName varchar(128) NOT NULL COMMENT '客户名称',
    MODIFY COLUMN cCusAbbName varchar(64) NULL COMMENT '客户简称',
    MODIFY COLUMN cCCCode varchar(64) NULL COMMENT '客户分类编码',
    MODIFY COLUMN cDCCode varchar(64) NULL COMMENT '地区编码',
    MODIFY COLUMN cCusTradeCCode varchar(64) NULL COMMENT '行业编码',
    MODIFY COLUMN cTrade varchar(255) NULL COMMENT '所属行业',
    MODIFY COLUMN cCusAddress varchar(255) NULL COMMENT '地址',
    MODIFY COLUMN cCusPostCode varchar(16) NULL COMMENT '邮政编码',
    MODIFY COLUMN cCusRegCode varchar(255) NULL COMMENT '纳税人登记号',
    MODIFY COLUMN cCusBank varchar(128) NULL COMMENT '开户银行',
    MODIFY COLUMN cCusAccount varchar(64) NULL COMMENT '银行账号',
    MODIFY COLUMN cCusLPerson varchar(64) NULL COMMENT '法人',
    MODIFY COLUMN cCusPerson varchar(64) NULL COMMENT '联系人',
    MODIFY COLUMN cCusHand varchar(32) NULL COMMENT '手机',
    MODIFY COLUMN cCusCreGrade varchar(255) NULL COMMENT '信用等级',
    MODIFY COLUMN iCusCreLine decimal(18,2) NULL COMMENT '信用额度',
    MODIFY COLUMN iCusCreDate int NULL COMMENT '信用期限',
    MODIFY COLUMN cCusOAddress varchar(255) NULL COMMENT '发货地址',
    MODIFY COLUMN cCusOType varchar(255) NULL COMMENT '发运方式',
    MODIFY COLUMN cCusHeadCode varchar(64) NULL COMMENT '客户总公司编码',
    MODIFY COLUMN cCusWhCode varchar(64) NULL COMMENT '发货仓库',
    MODIFY COLUMN cCusDepart varchar(64) NULL COMMENT '分管部门',
    MODIFY COLUMN iARMoney decimal(18,2) NULL COMMENT '应收余额',
    MODIFY COLUMN dLastDate datetime NULL COMMENT '最后交易日期',
    MODIFY COLUMN iLastMoney decimal(18,2) NULL COMMENT '最后交易金额',
    MODIFY COLUMN dLRDate datetime NULL COMMENT '最后收款日期',
    MODIFY COLUMN iLRMoney decimal(18,2) NULL COMMENT '最后收款金额',
    MODIFY COLUMN dEndDate datetime NULL COMMENT '停用日期',
    MODIFY COLUMN cCusBankCode varchar(64) NULL COMMENT '所属银行编码',
    MODIFY COLUMN cCusDefine1 varchar(255) NULL COMMENT '客户自定义项1',
    MODIFY COLUMN cCusDefine2 varchar(255) NULL COMMENT '客户自定义项2',
    MODIFY COLUMN cCusDefine3 varchar(255) NULL COMMENT '客户自定义项3',
    MODIFY COLUMN cCusDefine4 varchar(255) NULL COMMENT '客户自定义项4',
    MODIFY COLUMN cCusDefine5 varchar(255) NULL COMMENT '客户自定义项5',
    MODIFY COLUMN cCusDefine6 varchar(255) NULL COMMENT '客户自定义项6',
    MODIFY COLUMN cCusDefine7 varchar(255) NULL COMMENT '客户自定义项7',
    MODIFY COLUMN cCusDefine8 varchar(255) NULL COMMENT '客户自定义项8',
    MODIFY COLUMN cCusDefine9 varchar(255) NULL COMMENT '客户自定义项9',
    MODIFY COLUMN cCusDefine10 varchar(255) NULL COMMENT '客户自定义项10',
    MODIFY COLUMN cCusDefine11 int NULL COMMENT '客户自定义项11',
    MODIFY COLUMN cCusDefine12 int NULL COMMENT '客户自定义项12',
    MODIFY COLUMN cCusDefine13 decimal(18,2) NULL COMMENT '客户自定义项13',
    MODIFY COLUMN cCusDefine14 decimal(18,2) NULL COMMENT '客户自定义项14',
    MODIFY COLUMN cCusDefine15 datetime NULL COMMENT '客户自定义项15',
    MODIFY COLUMN cCusDefine16 datetime NULL COMMENT '客户自定义项16',
    MODIFY COLUMN cInvoiceCompany varchar(255) NULL COMMENT '开票单位',
    MODIFY COLUMN bCredit tinyint NULL DEFAULT 0 COMMENT '是否控制信用',
    MODIFY COLUMN bCreditDate tinyint NULL DEFAULT 0 COMMENT '是否控制信用期限',
    MODIFY COLUMN bCreditByHead tinyint NULL DEFAULT 0 COMMENT '是否按总公司控制信用',
    MODIFY COLUMN cMemo varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN fCommisionRate decimal(18,2) NULL COMMENT '佣金比率(%)',
    MODIFY COLUMN fInsueRate decimal(18,2) NULL COMMENT '保险费率(%)',
    MODIFY COLUMN CustomerKCode varchar(64) NULL COMMENT '客户级别编码',
    MODIFY COLUMN bCusState tinyint NULL DEFAULT 0 COMMENT '是否成交',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '客户档案表';

-- comment standardization end
