USE finex_db;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS gl_Vender (
    cVenCode VARCHAR(255) NOT NULL COMMENT '供应商编码',
    cVenName VARCHAR(255) NOT NULL COMMENT '供应商名称',
    cVenAbbName VARCHAR(255) NULL COMMENT '供应商简称',
    cVCCode VARCHAR(255) NULL COMMENT '供应商分类编码',
    cTrade VARCHAR(255) NULL COMMENT '所属行业',
    cVenAddress VARCHAR(255) NULL COMMENT '地址',
    cVenRegCode VARCHAR(255) NULL COMMENT '纳税人登记号',
    cVenBank VARCHAR(255) NULL COMMENT '开户银行',
    cVenAccount VARCHAR(255) NULL COMMENT '银行账号',
    cVenBankNub VARCHAR(255) NULL COMMENT '银行行号',
    cVenPerson VARCHAR(255) NULL COMMENT '联系人',
    cVenPhone VARCHAR(255) NULL COMMENT '电话',
    cVenHand VARCHAR(255) NULL COMMENT '手机',
    cVenEmail VARCHAR(255) NULL COMMENT 'Email地址',
    company_id VARCHAR(255) NULL COMMENT '公司主体编码',
    cMemo VARCHAR(255) NULL COMMENT '备注',
    dEndDate DATETIME NULL COMMENT '停用日期',
    bBusinessDate TINYINT DEFAULT 0 COMMENT '经营许可证是否期限管理',
    bLicenceDate TINYINT DEFAULT 0 COMMENT '营业执照是否期限管理',
    bPassGMP TINYINT DEFAULT 0 COMMENT '是否通过GMP认证',
    bProxyDate TINYINT DEFAULT 0 COMMENT '法人委托书是否期限管理',
    bProxyForeign TINYINT DEFAULT 0 COMMENT '是否委外',
    bVenCargo TINYINT DEFAULT 0 COMMENT '是否货物',
    bVenService TINYINT DEFAULT 0 COMMENT '是否服务',
    bVenTax TINYINT DEFAULT 0 COMMENT '单价是否含税',
    cBarCode VARCHAR(255) NULL COMMENT '对应条形码',
    cCreatePerson VARCHAR(255) NULL COMMENT '建档人',
    cDCCode VARCHAR(255) NULL COMMENT '地区编码',
    cModifyPerson VARCHAR(255) NULL COMMENT '变更人',
    cRelCustomer VARCHAR(255) NULL COMMENT '对应客户',
    cVenBankCode VARCHAR(255) NULL COMMENT '所属银行编码',
    cVenBP VARCHAR(255) NULL COMMENT '呼机',
    cVenDefine10 VARCHAR(255) NULL COMMENT '供应商自定义项10',
    cVenDefine11 INT NULL COMMENT '供应商自定义项11',
    cVenDefine12 INT NULL COMMENT '供应商自定义项12',
    cVenDefine13 DECIMAL(18,2) NULL COMMENT '供应商自定义项13',
    cVenDefine14 DECIMAL(18,2) NULL COMMENT '供应商自定义项14',
    cVenDefine15 DATETIME NULL COMMENT '供应商自定义项15',
    cVenDefine16 DATETIME NULL COMMENT '供应商自定义项16',
    cVenDefine3 VARCHAR(255) NULL COMMENT '供应商自定义项3',
    cVenDefine4 VARCHAR(255) NULL COMMENT '供应商自定义项4',
    cVenDefine5 VARCHAR(255) NULL COMMENT '供应商自定义项5',
    cVenDefine6 VARCHAR(255) NULL COMMENT '供应商自定义项6',
    cVenDefine7 VARCHAR(255) NULL COMMENT '供应商自定义项7',
    cVenDefine8 VARCHAR(255) NULL COMMENT '供应商自定义项8',
    cVenDefine9 VARCHAR(255) NULL COMMENT '供应商自定义项9',
    cVenDepart VARCHAR(255) NULL COMMENT '分管部门',
    cVenFax VARCHAR(255) NULL COMMENT '传真',
    cVenHeadCode VARCHAR(255) NULL COMMENT '供应商总公司编码',
    cVenIAddress VARCHAR(255) NULL COMMENT '到货地址',
    cVenIType VARCHAR(255) NULL COMMENT '到货方式',
    cVenLPerson VARCHAR(255) NULL COMMENT '法人',
    cVenPayCond VARCHAR(255) NULL COMMENT '付款条件编码',
    cVenPostCode VARCHAR(255) NULL COMMENT '邮政编码',
    cVenPPerson VARCHAR(255) NULL COMMENT '专营业务员',
    cVenTradeCCode VARCHAR(255) NULL COMMENT '行业编码',
    cVenWhCode VARCHAR(255) NULL COMMENT '到货仓库',
    dBusinessEDate DATETIME NULL COMMENT '经营许可证到期日期',
    dBusinessSDate DATETIME NULL COMMENT '经营许可证生效日期',
    dLastDate DATETIME NULL COMMENT '最后交易日期',
    dLicenceEDate DATETIME NULL COMMENT '营业执照到期日期',
    dLicenceSDate DATETIME NULL COMMENT '营业执照生效日期',
    dLRDate DATETIME NULL COMMENT '最后付款日期',
    dModifyDate DATETIME NULL COMMENT '变更日期',
    dProxyEDate DATETIME NULL COMMENT '法人委托书到期日期',
    dProxySDate DATETIME NULL COMMENT '法人委托书生效日期',
    dVenDevDate DATETIME NULL COMMENT '发展日期',
    fRegistFund DECIMAL(18,2) NULL COMMENT '注册资金',
    iAPMoney DECIMAL(18,2) NULL COMMENT '应付余额',
    iBusinessADays INT NULL COMMENT '经营许可证预警天数',
    iEmployeeNum INT NULL COMMENT '员工人数',
    iFrequency INT NULL COMMENT '使用频度',
    iGradeABC SMALLINT NULL COMMENT 'ABC等级',
    iId INT NULL COMMENT '所属权限组',
    iLastMoney DECIMAL(18,2) NULL COMMENT '最后交易金额',
    iLicenceADays INT NULL COMMENT '营业执照预警天数',
    iLRMoney DECIMAL(18,2) NULL COMMENT '最后付款金额',
    iProxyADays INT NULL COMMENT '法人委托书预警天数',
    iVenCreDate INT NULL COMMENT '信用期限',
    iVenCreGrade VARCHAR(255) NULL COMMENT '信用等级',
    iVenCreLine DECIMAL(18,2) NULL COMMENT '信用额度',
    iVenDisRate DECIMAL(18,2) NULL COMMENT '扣率',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (cVenCode),
    KEY idx_gl_Vender_name (cVenName),
    KEY idx_gl_Vender_company (company_id),
    KEY idx_gl_Vender_end_date (dEndDate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商档案表';

CREATE TABLE IF NOT EXISTS pm_document_instance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '单据实例ID',
    document_code VARCHAR(64) NOT NULL COMMENT '单据编码',
    template_code VARCHAR(64) NOT NULL COMMENT '模板编码',
    template_name VARCHAR(100) NOT NULL COMMENT '模板名称',
    template_type VARCHAR(32) NOT NULL COMMENT '模板类型',
    form_design_code VARCHAR(64) NULL COMMENT '表单设计编码',
    approval_flow_code VARCHAR(64) NULL COMMENT '审批流程编码',
    flow_name VARCHAR(100) NULL COMMENT '审批流程名称',
    submitter_user_id BIGINT NOT NULL COMMENT '提单人用户ID',
    submitter_name VARCHAR(100) NOT NULL COMMENT '提单人姓名',
    document_title VARCHAR(200) NULL COMMENT '单据标题',
    document_reason VARCHAR(500) NULL COMMENT '单据摘要/事由',
    total_amount DECIMAL(18,2) NULL COMMENT '总金额',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_APPROVAL' COMMENT '单据状态',
    form_data_json LONGTEXT NOT NULL COMMENT '表单填写数据',
    template_snapshot_json LONGTEXT NOT NULL COMMENT '模板快照',
    form_schema_snapshot_json LONGTEXT NOT NULL COMMENT '表单schema快照',
    flow_snapshot_json LONGTEXT NULL COMMENT '流程快照',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_pm_document_instance_code (document_code),
    KEY idx_pm_document_instance_submitter (submitter_user_id, created_at),
    KEY idx_pm_document_instance_template (template_code),
    KEY idx_pm_document_instance_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批单实例表';
