USE finex_db;

SET NAMES utf8mb4;

DROP TABLE IF EXISTS gl_accvouch;
DROP TABLE IF EXISTS gl_accsum;
DROP TABLE IF EXISTS gl_accass;

CREATE TABLE gl_accvouch (
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '主键',
    iyear INT COMMENT '会计年度',
    iyperiod INT COMMENT '会计年月(YYYYMM)',
    iperiod TINYINT COMMENT '会计期间',
    csign VARCHAR(64) COMMENT '凭证类别',
    isignseq INT COMMENT '凭证类别顺序',
    ino_id SMALLINT COMMENT '凭证号',
    inid SMALLINT COMMENT '行号',
    dbill_date DATETIME COMMENT '制单日期',
    idoc SMALLINT COMMENT '附件张数',
    cbill VARCHAR(64) COMMENT '制单人',
    ccheck VARCHAR(64) COMMENT '审核人',
    checked_at DATETIME COMMENT '审核时间',
    cbook VARCHAR(64) COMMENT '记账人',
    ibook TINYINT COMMENT '记账标记',
    posted_at DATETIME COMMENT '记账时间',
    ccashier VARCHAR(64) COMMENT '出纳签字人',
    iflag TINYINT COMMENT '错误标记',
    ctext1 VARCHAR(255) COMMENT '凭证头自定义项1',
    ctext2 VARCHAR(255) COMMENT '凭证头自定义项2',
    cdigest VARCHAR(255) COMMENT '摘要',
    ccode VARCHAR(64) COMMENT '科目编码',
    ccode_name VARCHAR(128) COMMENT '科目名称',
    cexch_name VARCHAR(32) COMMENT '币种名称',
    currency_code VARCHAR(32) COMMENT '币种编码',
    md DECIMAL(18,2) COMMENT '借方金额',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    md_f DECIMAL(18,2) COMMENT '借方外币金额',
    mc_f DECIMAL(18,2) COMMENT '贷方外币金额',
    nfrat DECIMAL(18,6) COMMENT '汇率',
    nd_s DECIMAL(18,6) COMMENT '借方数量',
    nc_s DECIMAL(18,6) COMMENT '贷方数量',
    csettle VARCHAR(64) COMMENT '结算方式编码',
    cn_id VARCHAR(64) COMMENT '票据号',
    dt_date DATETIME COMMENT '票据日期',
    cdept_id VARCHAR(64) COMMENT '部门编码',
    cperson_id VARCHAR(64) COMMENT '人员编码',
    ccus_id VARCHAR(64) COMMENT '客户编码',
    csup_id VARCHAR(64) COMMENT '供应商编码',
    citem_id VARCHAR(6) COMMENT '项目编码',
    citem_class VARCHAR(2) COMMENT '项目大类编码',
    cash_flow_item_id BIGINT COMMENT '现金流量项目ID',
    cash_flow_item_name VARCHAR(200) COMMENT '现金流量项目名称',
    cname VARCHAR(64) COMMENT '业务员',
    ccode_equal VARCHAR(64) COMMENT '对方科目编码',
    iflagbank TINYINT COMMENT '银行标记',
    iflagPerson TINYINT COMMENT '人员往来标记',
    bdelete TINYINT(1) COMMENT '删除标记',
    coutaccset VARCHAR(64) COMMENT '外部账套号',
    ioutyear SMALLINT COMMENT '外部凭证年度',
    coutsysname VARCHAR(255) COMMENT '外部系统名称',
    coutsysver VARCHAR(255) COMMENT '外部系统版本',
    doutbilldate DATETIME COMMENT '外部制单日期',
    ioutperiod TINYINT COMMENT '外部凭证期间',
    coutsign VARCHAR(64) COMMENT '外部凭证类别',
    coutno_id VARCHAR(64) COMMENT '外部凭证号',
    doutdate DATETIME COMMENT '外部导出日期',
    coutbillsign VARCHAR(64) COMMENT '外部单据类别',
    coutid VARCHAR(64) COMMENT '外部单据号',
    bvouchedit TINYINT(1) COMMENT '是否允许改凭证',
    bvouchAddordele TINYINT(1) COMMENT '是否允许增删分录',
    bvouchmoneyhold TINYINT(1) COMMENT '是否允许改金额',
    bvalueedit TINYINT(1) COMMENT '是否允许改值',
    bcodeedit TINYINT(1) COMMENT '是否允许改科目',
    ccodecontrol VARCHAR(32) COMMENT '科目受控标记',
    bPCSedit TINYINT(1) COMMENT '是否允许改人客供',
    bDeptedit TINYINT(1) COMMENT '是否允许改部门',
    bItemedit TINYINT(1) COMMENT '是否允许改项目',
    bCusSupInput TINYINT(1) COMMENT '是否允许录入客商',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    cDefine1 VARCHAR(255) COMMENT '自定义项1',
    cDefine2 VARCHAR(255) COMMENT '自定义项2',
    cDefine3 VARCHAR(255) COMMENT '自定义项3',
    cDefine4 DATETIME COMMENT '自定义项4',
    cDefine5 INT COMMENT '自定义项5',
    PRIMARY KEY (i_id),
    KEY idx_gl_accvouch_company_id (company_id),
    KEY idx_gl_accvouch_iperiod (iperiod),
    KEY idx_gl_accvouch_company_year_period (company_id, iyear, iyperiod),
    KEY idx_gl_accvouch_company_year_period_no (company_id, iyear, iyperiod, csign, ino_id),
    KEY idx_gl_accvouch_ccode (ccode),
    KEY idx_gl_accvouch_ino_id (ino_id),
    KEY idx_gl_accvouch_dbill_date (dbill_date),
    KEY idx_gl_accvouch_ccus_id (ccus_id),
    KEY idx_gl_accvouch_csup_id (csup_id),
    KEY idx_gl_accvouch_cperson_id (cperson_id),
    KEY idx_gl_accvouch_cdept_id (cdept_id),
    KEY idx_gl_accvouch_citem_id (citem_id),
    KEY idx_gl_accvouch_company_ccode (company_id, ccode),
    KEY idx_gl_accvouch_company_cperson (company_id, cperson_id),
    KEY idx_gl_accvouch_company_ccus (company_id, ccus_id),
    KEY idx_gl_accvouch_company_csup (company_id, csup_id),
    KEY idx_gl_accvouch_company_citem_class (company_id, citem_class),
    KEY idx_gl_accvouch_company_citem_id (company_id, citem_id),
    KEY idx_gl_accvouch_company_citem_class_id (company_id, citem_class, citem_id),
    KEY idx_gl_accvouch_company_cash_flow (company_id, cash_flow_item_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='总账凭证明细表';

CREATE TABLE gl_accsum (
    cbegind_c VARCHAR(32) COMMENT '期初方向',
    cbegind_c_engl VARCHAR(32) COMMENT '期初方向英文',
    ccode VARCHAR(64) COMMENT '科目编码',
    cendd_c VARCHAR(32) COMMENT '期末方向',
    cendd_c_engl VARCHAR(32) COMMENT '期末方向英文',
    cexch_name VARCHAR(32) COMMENT '币种名称',
    currency_code VARCHAR(32) COMMENT '币种编码',
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '主键',
    iyear INT COMMENT '会计年度',
    iyperiod INT COMMENT '会计年月(YYYYMM)',
    iperiod TINYINT COMMENT '会计期间',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    mb DECIMAL(18,2) COMMENT '期初余额',
    mb_f DECIMAL(18,2) COMMENT '期初外币余额',
    mc DECIMAL(18,2) COMMENT '本期贷方金额',
    mc_f DECIMAL(18,2) COMMENT '本期贷方外币金额',
    md DECIMAL(18,2) COMMENT '本期借方金额',
    md_f DECIMAL(18,2) COMMENT '本期借方外币金额',
    me DECIMAL(18,2) COMMENT '期末余额',
    me_f DECIMAL(18,2) COMMENT '期末外币余额',
    nb_s DECIMAL(18,6) COMMENT '期初数量余额',
    nc_s DECIMAL(18,6) COMMENT '贷方数量',
    nd_s DECIMAL(18,6) COMMENT '借方数量',
    ne_s DECIMAL(18,6) COMMENT '期末数量余额',
    PRIMARY KEY (i_id),
    KEY idx_gl_accsum_company_id (company_id),
    KEY idx_gl_accsum_iperiod (iperiod),
    KEY idx_gl_accsum_company_year_period (company_id, iyear, iyperiod),
    KEY idx_gl_accsum_ccode (ccode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='总账科目余额表';

CREATE TABLE gl_accass (
    cbegind_c VARCHAR(32) COMMENT '期初方向',
    cbegind_c_engl VARCHAR(32) COMMENT '期初方向英文',
    ccode VARCHAR(64) COMMENT '科目编码',
    ccus_id VARCHAR(64) COMMENT '客户编码',
    cdept_id VARCHAR(64) COMMENT '部门编码',
    cendd_c VARCHAR(32) COMMENT '期末方向',
    cendd_c_engl VARCHAR(32) COMMENT '期末方向英文',
    cexch_name VARCHAR(32) COMMENT '币种名称',
    currency_code VARCHAR(32) COMMENT '币种编码',
    citem_class VARCHAR(2) COMMENT '项目大类编码',
    citem_id VARCHAR(6) COMMENT '项目编码',
    cperson_id VARCHAR(64) COMMENT '人员编码',
    csup_id VARCHAR(64) COMMENT '供应商编码',
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '主键',
    iyear INT COMMENT '会计年度',
    iyperiod INT COMMENT '会计年月(YYYYMM)',
    iperiod TINYINT COMMENT '会计期间',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    mb DECIMAL(18,2) COMMENT '期初余额',
    mb_f DECIMAL(18,2) COMMENT '期初外币余额',
    mc DECIMAL(18,2) COMMENT '本期贷方金额',
    mc_f DECIMAL(18,2) COMMENT '本期贷方外币金额',
    md DECIMAL(18,2) COMMENT '本期借方金额',
    md_f DECIMAL(18,2) COMMENT '本期借方外币金额',
    me DECIMAL(18,2) COMMENT '期末余额',
    me_f DECIMAL(18,2) COMMENT '期末外币余额',
    nb_s DECIMAL(18,6) COMMENT '期初数量余额',
    nc_s DECIMAL(18,6) COMMENT '贷方数量',
    nd_s DECIMAL(18,6) COMMENT '借方数量',
    ne_s DECIMAL(18,6) COMMENT '期末数量余额',
    PRIMARY KEY (i_id),
    KEY idx_gl_accass_company_id (company_id),
    KEY idx_gl_accass_iperiod (iperiod),
    KEY idx_gl_accass_company_year_period (company_id, iyear, iyperiod),
    KEY idx_gl_accass_ccode (ccode),
    KEY idx_gl_accass_ccus_id (ccus_id),
    KEY idx_gl_accass_csup_id (csup_id),
    KEY idx_gl_accass_cperson_id (cperson_id),
    KEY idx_gl_accass_cdept_id (cdept_id),
    KEY idx_gl_accass_citem_id (citem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='总账辅助余额表';
