USE finex_db;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS gl_Vender (
    cVenCode VARCHAR(64) NOT NULL COMMENT '供应商编码',
    cVenName VARCHAR(128) NOT NULL COMMENT '供应商名称',
    cVenAbbName VARCHAR(64) NULL COMMENT '供应商简称',
    cVCCode VARCHAR(64) NULL COMMENT '供应商分类编码',
    cTrade VARCHAR(255) NULL COMMENT '所属行业',
    cVenAddress VARCHAR(255) NULL COMMENT '地址',
    cVenRegCode VARCHAR(255) NULL COMMENT '纳税人登记号',
    cVenBank VARCHAR(128) NULL COMMENT '开户银行',
    cVenAccount VARCHAR(64) NULL COMMENT '银行账号',
    cVenBankNub VARCHAR(64) NULL COMMENT '银行行号',
    receipt_account_name VARCHAR(128) NULL COMMENT '收款开户名',
    receipt_bank_province VARCHAR(64) NULL COMMENT '收款开户省',
    receipt_bank_city VARCHAR(64) NULL COMMENT '收款开户市',
    receipt_branch_code VARCHAR(64) NULL COMMENT '收款分支行编码',
    receipt_branch_name VARCHAR(128) NULL COMMENT '收款分支行名称',
    cVenPerson VARCHAR(64) NULL COMMENT '联系人',
    cVenPhone VARCHAR(32) NULL COMMENT '电话',
    cVenHand VARCHAR(32) NULL COMMENT '手机',
    cVenEmail VARCHAR(255) NULL COMMENT 'Email地址',
    company_id VARCHAR(64) NULL COMMENT '公司主体编码',
    cMemo VARCHAR(255) NULL COMMENT '备注',
    dEndDate DATETIME NULL COMMENT '停用日期',
    bBusinessDate TINYINT DEFAULT 0 COMMENT '经营许可证是否期限管理',
    bLicenceDate TINYINT DEFAULT 0 COMMENT '营业执照是否期限管理',
    bPassGMP TINYINT DEFAULT 0 COMMENT '是否通过GMP认证',
    bProxyDate TINYINT DEFAULT 0 COMMENT '法人委托书是否期限管理',
    bProxyForeign TINYINT DEFAULT 0 COMMENT '是否委外',
    bVenCargo TINYINT DEFAULT 0 COMMENT '是否货物',
    bVenService TINYINT DEFAULT 0 COMMENT '是否服务',
    bVenTax TINYINT DEFAULT 0 COMMENT '单价是否含税',
    cBarCode VARCHAR(255) NULL COMMENT '对应条形码',
    cCreatePerson VARCHAR(64) NULL COMMENT '建档人',
    cDCCode VARCHAR(64) NULL COMMENT '地区编码',
    cModifyPerson VARCHAR(64) NULL COMMENT '变更人',
    cRelCustomer VARCHAR(64) NULL COMMENT '对应客户',
    cVenBankCode VARCHAR(64) NULL COMMENT '所属银行编码',
    cVenBP VARCHAR(32) NULL COMMENT '呼机',
    cVenDefine10 VARCHAR(255) NULL COMMENT '供应商自定义项10',
    cVenDefine11 INT NULL COMMENT '供应商自定义项11',
    cVenDefine12 INT NULL COMMENT '供应商自定义项12',
    cVenDefine13 DECIMAL(18,2) NULL COMMENT '供应商自定义项13',
    cVenDefine14 DECIMAL(18,2) NULL COMMENT '供应商自定义项14',
    cVenDefine15 DATETIME NULL COMMENT '供应商自定义项15',
    cVenDefine16 DATETIME NULL COMMENT '供应商自定义项16',
    cVenDefine3 VARCHAR(255) NULL COMMENT '供应商自定义项3',
    cVenDefine4 VARCHAR(255) NULL COMMENT '供应商自定义项4',
    cVenDefine5 VARCHAR(255) NULL COMMENT '供应商自定义项5',
    cVenDefine6 VARCHAR(255) NULL COMMENT '供应商自定义项6',
    cVenDefine7 VARCHAR(255) NULL COMMENT '供应商自定义项7',
    cVenDefine8 VARCHAR(255) NULL COMMENT '供应商自定义项8',
    cVenDefine9 VARCHAR(255) NULL COMMENT '供应商自定义项9',
    cVenDepart VARCHAR(255) NULL COMMENT '分管部门',
    cVenFax VARCHAR(32) NULL COMMENT '传真',
    cVenHeadCode VARCHAR(64) NULL COMMENT '供应商总公司编码',
    cVenIAddress VARCHAR(255) NULL COMMENT '到货地址',
    cVenIType VARCHAR(255) NULL COMMENT '到货方式',
    cVenLPerson VARCHAR(64) NULL COMMENT '法人',
    cVenPayCond VARCHAR(64) NULL COMMENT '付款条件编码',
    cVenPostCode VARCHAR(16) NULL COMMENT '邮政编码',
    cVenPPerson VARCHAR(64) NULL COMMENT '专营业务员',
    cVenTradeCCode VARCHAR(64) NULL COMMENT '行业编码',
    cVenWhCode VARCHAR(64) NULL COMMENT '到货仓库',
    dBusinessEDate DATETIME NULL COMMENT '经营许可证到期日期',
    dBusinessSDate DATETIME NULL COMMENT '经营许可证生效日期',
    dLastDate DATETIME NULL COMMENT '最后交易日期',
    dLicenceEDate DATETIME NULL COMMENT '营业执照到期日期',
    dLicenceSDate DATETIME NULL COMMENT '营业执照生效日期',
    dLRDate DATETIME NULL COMMENT '最后付款日期',
    dModifyDate DATETIME NULL COMMENT '变更日期',
    dProxyEDate DATETIME NULL COMMENT '法人委托书到期日期',
    dProxySDate DATETIME NULL COMMENT '法人委托书生效日期',
    dVenDevDate DATETIME NULL COMMENT '发展日期',
    fRegistFund DECIMAL(18,2) NULL COMMENT '注册资金',
    iAPMoney DECIMAL(18,2) NULL COMMENT '应付余额',
    iBusinessADays INT NULL COMMENT '经营许可证预警天数',
    iEmployeeNum INT NULL COMMENT '员工人数',
    iFrequency INT NULL COMMENT '使用频度',
    iGradeABC SMALLINT NULL COMMENT 'ABC等级',
    iId INT NULL COMMENT '所属权限组',
    iLastMoney DECIMAL(18,2) NULL COMMENT '最后交易金额',
    iLicenceADays INT NULL COMMENT '营业执照预警天数',
    iLRMoney DECIMAL(18,2) NULL COMMENT '最后付款金额',
    iProxyADays INT NULL COMMENT '法人委托书预警天数',
    iVenCreDate INT NULL COMMENT '信用期限',
    iVenCreGrade VARCHAR(255) NULL COMMENT '信用等级',
    iVenCreLine DECIMAL(18,2) NULL COMMENT '信用额度',
    iVenDisRate DECIMAL(18,2) NULL COMMENT '扣率',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (cVenCode),
    KEY idx_gl_Vender_name (cVenName),
    KEY idx_gl_Vender_company (company_id),
    KEY idx_gl_Vender_end_date (dEndDate)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='供应商档案表';

CREATE TABLE IF NOT EXISTS pm_document_instance (
    id BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '单据实例ID',
    document_code VARCHAR(64) NOT NULL COMMENT '单据编码',
    template_code VARCHAR(64) NOT NULL COMMENT '模板编码',
    template_name VARCHAR(64) NOT NULL COMMENT '模板名称',
    template_type VARCHAR(32) NOT NULL COMMENT '模板类型',
    form_design_code VARCHAR(64) NULL COMMENT '表单设计编码',
    approval_flow_code VARCHAR(64) NULL COMMENT '审批流程编码',
    flow_name VARCHAR(64) NULL COMMENT '审批流程名称',
    submitter_user_id BIGINT NOT NULL COMMENT '提单人用户ID',
    submitter_name VARCHAR(64) NOT NULL COMMENT '提单人姓名',
    document_title VARCHAR(128) NULL COMMENT '单据标题',
    document_reason VARCHAR(500) NULL COMMENT '单据摘要/事由',
    total_amount DECIMAL(18,2) NULL COMMENT '总金额',
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING_APPROVAL' COMMENT '单据状态',
    form_data_json LONGTEXT NOT NULL COMMENT '表单填写数据',
    template_snapshot_json LONGTEXT NOT NULL COMMENT '模板快照',
    form_schema_snapshot_json LONGTEXT NOT NULL COMMENT '表单schema快照',
    flow_snapshot_json LONGTEXT NULL COMMENT '流程快照',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    UNIQUE KEY uk_pm_document_instance_code (document_code),
    KEY idx_pm_document_instance_submitter (submitter_user_id, created_at),
    KEY idx_pm_document_instance_template (template_code),
    KEY idx_pm_document_instance_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='审批单实例表';

-- comment standardization begin
ALTER TABLE gl_vender
    MODIFY COLUMN cVenCode varchar(64) NOT NULL COMMENT '供应商编码',
    MODIFY COLUMN cVenName varchar(128) NOT NULL COMMENT '供应商名称',
    MODIFY COLUMN cVenAbbName varchar(64) NULL COMMENT '供应商简称',
    MODIFY COLUMN cVCCode varchar(64) NULL COMMENT '供应商分类编码',
    MODIFY COLUMN cTrade varchar(255) NULL COMMENT '所属行业',
    MODIFY COLUMN cVenAddress varchar(255) NULL COMMENT '地址',
    MODIFY COLUMN cVenRegCode varchar(255) NULL COMMENT '纳税人登记号',
    MODIFY COLUMN cVenBank varchar(128) NULL COMMENT '开户银行',
    MODIFY COLUMN cVenAccount varchar(64) NULL COMMENT '银行账号',
    MODIFY COLUMN cVenBankNub varchar(64) NULL COMMENT '银行行号',
    MODIFY COLUMN receipt_account_name varchar(128) NULL COMMENT '收款开户名',
    MODIFY COLUMN receipt_bank_province varchar(64) NULL COMMENT '收款开户省',
    MODIFY COLUMN receipt_bank_city varchar(64) NULL COMMENT '收款开户市',
    MODIFY COLUMN receipt_branch_code varchar(64) NULL COMMENT '收款分支行编码',
    MODIFY COLUMN receipt_branch_name varchar(128) NULL COMMENT '收款分支行名称',
    MODIFY COLUMN cVenPerson varchar(64) NULL COMMENT '联系人',
    MODIFY COLUMN cVenPhone varchar(32) NULL COMMENT '电话',
    MODIFY COLUMN cVenHand varchar(32) NULL COMMENT '手机',
    MODIFY COLUMN cVenEmail varchar(255) NULL COMMENT 'Email地址',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN cMemo varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN dEndDate datetime NULL COMMENT '停用日期',
    MODIFY COLUMN bBusinessDate tinyint NULL DEFAULT 0 COMMENT '经营许可证是否期限管理',
    MODIFY COLUMN bLicenceDate tinyint NULL DEFAULT 0 COMMENT '营业执照是否期限管理',
    MODIFY COLUMN bPassGMP tinyint NULL DEFAULT 0 COMMENT '是否通过GMP认证',
    MODIFY COLUMN bProxyDate tinyint NULL DEFAULT 0 COMMENT '法人委托书是否期限管理',
    MODIFY COLUMN bProxyForeign tinyint NULL DEFAULT 0 COMMENT '是否委外',
    MODIFY COLUMN bVenCargo tinyint NULL DEFAULT 0 COMMENT '是否货物',
    MODIFY COLUMN bVenService tinyint NULL DEFAULT 0 COMMENT '是否服务',
    MODIFY COLUMN bVenTax tinyint NULL DEFAULT 0 COMMENT '单价是否含税',
    MODIFY COLUMN cBarCode varchar(255) NULL COMMENT '对应条形码',
    MODIFY COLUMN cCreatePerson varchar(64) NULL COMMENT '建档人',
    MODIFY COLUMN cDCCode varchar(64) NULL COMMENT '地区编码',
    MODIFY COLUMN cModifyPerson varchar(64) NULL COMMENT '变更人',
    MODIFY COLUMN cRelCustomer varchar(64) NULL COMMENT '对应客户',
    MODIFY COLUMN cVenBankCode varchar(64) NULL COMMENT '所属银行编码',
    MODIFY COLUMN cVenBP varchar(32) NULL COMMENT '呼机',
    MODIFY COLUMN cVenDefine10 varchar(255) NULL COMMENT '供应商自定义项10',
    MODIFY COLUMN cVenDefine11 int NULL COMMENT '供应商自定义项11',
    MODIFY COLUMN cVenDefine12 int NULL COMMENT '供应商自定义项12',
    MODIFY COLUMN cVenDefine13 decimal(18,2) NULL COMMENT '供应商自定义项13',
    MODIFY COLUMN cVenDefine14 decimal(18,2) NULL COMMENT '供应商自定义项14',
    MODIFY COLUMN cVenDefine15 datetime NULL COMMENT '供应商自定义项15',
    MODIFY COLUMN cVenDefine16 datetime NULL COMMENT '供应商自定义项16',
    MODIFY COLUMN cVenDefine3 varchar(255) NULL COMMENT '供应商自定义项3',
    MODIFY COLUMN cVenDefine4 varchar(255) NULL COMMENT '供应商自定义项4',
    MODIFY COLUMN cVenDefine5 varchar(255) NULL COMMENT '供应商自定义项5',
    MODIFY COLUMN cVenDefine6 varchar(255) NULL COMMENT '供应商自定义项6',
    MODIFY COLUMN cVenDefine7 varchar(255) NULL COMMENT '供应商自定义项7',
    MODIFY COLUMN cVenDefine8 varchar(255) NULL COMMENT '供应商自定义项8',
    MODIFY COLUMN cVenDefine9 varchar(255) NULL COMMENT '供应商自定义项9',
    MODIFY COLUMN cVenDepart varchar(255) NULL COMMENT '分管部门',
    MODIFY COLUMN cVenFax varchar(32) NULL COMMENT '传真',
    MODIFY COLUMN cVenHeadCode varchar(64) NULL COMMENT '供应商总公司编码',
    MODIFY COLUMN cVenIAddress varchar(255) NULL COMMENT '到货地址',
    MODIFY COLUMN cVenIType varchar(255) NULL COMMENT '到货方式',
    MODIFY COLUMN cVenLPerson varchar(64) NULL COMMENT '法人',
    MODIFY COLUMN cVenPayCond varchar(64) NULL COMMENT '付款条件编码',
    MODIFY COLUMN cVenPostCode varchar(16) NULL COMMENT '邮政编码',
    MODIFY COLUMN cVenPPerson varchar(64) NULL COMMENT '专营业务员',
    MODIFY COLUMN cVenTradeCCode varchar(64) NULL COMMENT '行业编码',
    MODIFY COLUMN cVenWhCode varchar(64) NULL COMMENT '到货仓库',
    MODIFY COLUMN dBusinessEDate datetime NULL COMMENT '经营许可证到期日期',
    MODIFY COLUMN dBusinessSDate datetime NULL COMMENT '经营许可证生效日期',
    MODIFY COLUMN dLastDate datetime NULL COMMENT '最后交易日期',
    MODIFY COLUMN dLicenceEDate datetime NULL COMMENT '营业执照到期日期',
    MODIFY COLUMN dLicenceSDate datetime NULL COMMENT '营业执照生效日期',
    MODIFY COLUMN dLRDate datetime NULL COMMENT '最后付款日期',
    MODIFY COLUMN dModifyDate datetime NULL COMMENT '变更日期',
    MODIFY COLUMN dProxyEDate datetime NULL COMMENT '法人委托书到期日期',
    MODIFY COLUMN dProxySDate datetime NULL COMMENT '法人委托书生效日期',
    MODIFY COLUMN dVenDevDate datetime NULL COMMENT '发展日期',
    MODIFY COLUMN fRegistFund decimal(18,2) NULL COMMENT '注册资金',
    MODIFY COLUMN iAPMoney decimal(18,2) NULL COMMENT '应付余额',
    MODIFY COLUMN iBusinessADays int NULL COMMENT '经营许可证预警天数',
    MODIFY COLUMN iEmployeeNum int NULL COMMENT '员工人数',
    MODIFY COLUMN iFrequency int NULL COMMENT '使用频度',
    MODIFY COLUMN iGradeABC smallint NULL COMMENT 'ABC等级',
    MODIFY COLUMN iId int NULL COMMENT '所属权限组',
    MODIFY COLUMN iLastMoney decimal(18,2) NULL COMMENT '最后交易金额',
    MODIFY COLUMN iLicenceADays int NULL COMMENT '营业执照预警天数',
    MODIFY COLUMN iLRMoney decimal(18,2) NULL COMMENT '最后付款金额',
    MODIFY COLUMN iProxyADays int NULL COMMENT '法人委托书预警天数',
    MODIFY COLUMN iVenCreDate int NULL COMMENT '信用期限',
    MODIFY COLUMN iVenCreGrade varchar(255) NULL COMMENT '信用等级',
    MODIFY COLUMN iVenCreLine decimal(18,2) NULL COMMENT '信用额度',
    MODIFY COLUMN iVenDisRate decimal(18,2) NULL COMMENT '扣率',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '供应商档案表';

-- comment standardization end
