USE finex_db;

SET NAMES utf8mb4;

DROP TABLE IF EXISTS gl_accvouch;
DROP TABLE IF EXISTS gl_accsum;
DROP TABLE IF EXISTS gl_accass;

CREATE TABLE gl_accvouch (
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '自动编号',
    iperiod TINYINT COMMENT '会计期间',
    csign VARCHAR(255) COMMENT '凭证类别字',
    isignseq INT COMMENT '凭证类别排序号',
    ino_id SMALLINT COMMENT '凭证编号',
    inid SMALLINT COMMENT '行号',
    dbill_date DATETIME COMMENT '制单日期',
    idoc SMALLINT COMMENT '附单据数',
    cbill VARCHAR(255) COMMENT '制单人',
    ccheck VARCHAR(255) COMMENT '审核人',
    cbook VARCHAR(255) COMMENT '记账人',
    ibook TINYINT COMMENT '记账标志',
    ccashier VARCHAR(255) COMMENT '出纳签字人',
    iflag TINYINT COMMENT '凭证标志',
    ctext1 VARCHAR(255) COMMENT '凭证头自定义项1',
    ctext2 VARCHAR(255) COMMENT '凭证头自定义项2',
    cdigest VARCHAR(255) COMMENT '摘要',
    ccode VARCHAR(255) COMMENT '科目编码',
    cexch_name VARCHAR(255) COMMENT '币种名称',
    md DECIMAL(18,2) COMMENT '借方金额',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    md_f DECIMAL(18,2) COMMENT '外币借方金额',
    mc_f DECIMAL(18,2) COMMENT '外币贷方金额',
    nfrat DECIMAL(18,6) COMMENT '汇率',
    nd_s DECIMAL(18,6) COMMENT '数量借方',
    nc_s DECIMAL(18,6) COMMENT '数量贷方',
    csettle VARCHAR(255) COMMENT '结算方式编码',
    cn_id VARCHAR(255) COMMENT '票据号',
    dt_date DATETIME COMMENT '票号发生日期',
    cdept_id VARCHAR(255) COMMENT '部门编码',
    cperson_id VARCHAR(255) COMMENT '职员编码',
    ccus_id VARCHAR(255) COMMENT '客户编码',
    csup_id VARCHAR(255) COMMENT '供应商编码',
    citem_id VARCHAR(255) COMMENT '项目编码',
    citem_class VARCHAR(255) COMMENT '项目大类编码',
    cname VARCHAR(255) COMMENT '业务员',
    ccode_equal VARCHAR(255) COMMENT '对方科目编码',
    iflagbank TINYINT COMMENT '银行账两清标志',
    iflagPerson TINYINT COMMENT '往来账两清标志',
    bdelete TINYINT(1) COMMENT '是否核销',
    coutaccset VARCHAR(255) COMMENT '外部凭证账套号',
    ioutyear SMALLINT COMMENT '外部凭证会计年度',
    coutsysname VARCHAR(255) COMMENT '外部凭证系统名称',
    coutsysver VARCHAR(255) COMMENT '外部凭证系统版本号',
    doutbilldate DATETIME COMMENT '外部凭证制单日期',
    ioutperiod TINYINT COMMENT '外部凭证会计期间',
    coutsign VARCHAR(255) COMMENT '外部凭证业务类型',
    coutno_id VARCHAR(255) COMMENT '外部凭证业务号',
    doutdate DATETIME COMMENT '外部凭证单据日期',
    coutbillsign VARCHAR(255) COMMENT '外部凭证单据类型',
    coutid VARCHAR(255) COMMENT '外部凭证单据号',
    bvouchedit TINYINT(1) COMMENT '凭证是否可修改',
    bvouchAddordele TINYINT(1) COMMENT '凭证分录是否可增删',
    bvouchmoneyhold TINYINT(1) COMMENT '凭证合计金额是否保值',
    bvalueedit TINYINT(1) COMMENT '分录数值是否可修改',
    bcodeedit TINYINT(1) COMMENT '分录科目是否可修改',
    ccodecontrol VARCHAR(255) COMMENT '分录受控科目可用状态',
    bPCSedit TINYINT(1) COMMENT '分录往来项是否可修改',
    bDeptedit TINYINT(1) COMMENT '分录部门是否可修改',
    bItemedit TINYINT(1) COMMENT '分录项目是否可修改',
    bCusSupInput TINYINT(1) COMMENT '分录往来项是否必输',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    cDefine1 VARCHAR(255) COMMENT '自定义项1',
    cDefine2 VARCHAR(255) COMMENT '自定义项2',
    cDefine3 VARCHAR(255) COMMENT '自定义项3',
    cDefine4 DATETIME COMMENT '自定义项4',
    cDefine5 INT COMMENT '自定义项5',
    PRIMARY KEY (i_id),
    KEY idx_gl_accvouch_company_id (company_id),
    KEY idx_gl_accvouch_iperiod (iperiod),
    KEY idx_gl_accvouch_ccode (ccode),
    KEY idx_gl_accvouch_ino_id (ino_id),
    KEY idx_gl_accvouch_dbill_date (dbill_date),
    KEY idx_gl_accvouch_ccus_id (ccus_id),
    KEY idx_gl_accvouch_csup_id (csup_id),
    KEY idx_gl_accvouch_cperson_id (cperson_id),
    KEY idx_gl_accvouch_cdept_id (cdept_id),
    KEY idx_gl_accvouch_citem_id (citem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='凭证及明细账';

CREATE TABLE gl_accsum (
    cbegind_c VARCHAR(255) COMMENT '金额期初方向',
    cbegind_c_engl VARCHAR(255) COMMENT '金额期初方向英文',
    ccode VARCHAR(255) COMMENT '科目编码',
    cendd_c VARCHAR(255) COMMENT '金额期末方向',
    cendd_c_engl VARCHAR(255) COMMENT '金额期末方向英文',
    cexch_name VARCHAR(255) COMMENT '币种名称',
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '自动编号',
    iperiod TINYINT COMMENT '会计期间',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    mb DECIMAL(18,2) COMMENT '金额期初',
    mb_f DECIMAL(18,2) COMMENT '外币期初',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    mc_f DECIMAL(18,2) COMMENT '外币贷方金额',
    md DECIMAL(18,2) COMMENT '借方金额',
    md_f DECIMAL(18,2) COMMENT '外币借方金额',
    me DECIMAL(18,2) COMMENT '金额期末',
    me_f DECIMAL(18,2) COMMENT '外币期末',
    nb_s DECIMAL(18,6) COMMENT '数量期初',
    nc_s DECIMAL(18,6) COMMENT '数量贷方',
    nd_s DECIMAL(18,6) COMMENT '数量借方',
    ne_s DECIMAL(18,6) COMMENT '数量期末',
    PRIMARY KEY (i_id),
    KEY idx_gl_accsum_company_id (company_id),
    KEY idx_gl_accsum_iperiod (iperiod),
    KEY idx_gl_accsum_ccode (ccode)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='科目总账';

CREATE TABLE gl_accass (
    cbegind_c VARCHAR(255) COMMENT '金额期初方向',
    cbegind_c_engl VARCHAR(255) COMMENT '金额期初方向英文',
    ccode VARCHAR(255) COMMENT '科目编码',
    ccus_id VARCHAR(255) COMMENT '客户编码',
    cdept_id VARCHAR(255) COMMENT '部门编码',
    cendd_c VARCHAR(255) COMMENT '金额期末方向',
    cendd_c_engl VARCHAR(255) COMMENT '金额期末方向英文',
    cexch_name VARCHAR(255) COMMENT '币种名称',
    citem_class VARCHAR(255) COMMENT '项目大类编码',
    citem_id VARCHAR(255) COMMENT '项目编码',
    cperson_id VARCHAR(255) COMMENT '职员编码',
    csup_id VARCHAR(255) COMMENT '供应商编码',
    i_id INT NOT NULL AUTO_INCREMENT COMMENT '自动编号',
    iperiod TINYINT COMMENT '会计期间',
    company_id VARCHAR(64) COMMENT '公司主体编码',
    mb DECIMAL(18,2) COMMENT '金额期初',
    mb_f DECIMAL(18,2) COMMENT '外币期初',
    mc DECIMAL(18,2) COMMENT '贷方金额',
    mc_f DECIMAL(18,2) COMMENT '外币贷方金额',
    md DECIMAL(18,2) COMMENT '借方金额',
    md_f DECIMAL(18,2) COMMENT '外币借方金额',
    me DECIMAL(18,2) COMMENT '金额期末',
    me_f DECIMAL(18,2) COMMENT '外币期末',
    nb_s DECIMAL(18,6) COMMENT '数量期初',
    nc_s DECIMAL(18,6) COMMENT '数量贷方',
    nd_s DECIMAL(18,6) COMMENT '数量借方',
    ne_s DECIMAL(18,6) COMMENT '数量期末',
    PRIMARY KEY (i_id),
    KEY idx_gl_accass_company_id (company_id),
    KEY idx_gl_accass_iperiod (iperiod),
    KEY idx_gl_accass_ccode (ccode),
    KEY idx_gl_accass_ccus_id (ccus_id),
    KEY idx_gl_accass_csup_id (csup_id),
    KEY idx_gl_accass_cperson_id (cperson_id),
    KEY idx_gl_accass_cdept_id (cdept_id),
    KEY idx_gl_accass_citem_id (citem_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='辅助总账';
