USE finex_db;

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS fin_account_set (
    company_id VARCHAR(64) NOT NULL COMMENT '鍏徃涓讳綋缂栫爜',
    status VARCHAR(16) NOT NULL DEFAULT 'INITIALIZING' COMMENT '璐﹀鐘舵€?',
    enabled_year INT NULL COMMENT '鍚敤骞村害',
    enabled_period INT NULL COMMENT '鍚敤鏈熼棿',
    template_code VARCHAR(32) NULL COMMENT '妯℃澘缂栫爜',
    supervisor_user_id BIGINT NULL COMMENT '璐﹀涓荤鐢ㄦ埛ID',
    create_mode VARCHAR(16) NOT NULL DEFAULT 'BLANK' COMMENT '鍒涘缓鏂瑰紡',
    reference_company_id VARCHAR(64) NULL COMMENT '鍙傜収璐﹀鍏徃',
    subject_code_scheme VARCHAR(32) NULL COMMENT '绉戠洰缂栫爜瑙勫垯',
    subject_count INT NOT NULL DEFAULT 0 COMMENT '绉戠洰鏁伴噺',
    last_task_no VARCHAR(32) NULL COMMENT '鏈€杩戜换鍔″彿',
    error_message VARCHAR(500) NULL COMMENT '澶辫触鍘熷洜',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    PRIMARY KEY (company_id),
    KEY idx_fin_account_set_status (status),
    KEY idx_fin_account_set_template (template_code),
    KEY idx_fin_account_set_supervisor (supervisor_user_id),
    KEY idx_fin_account_set_reference (reference_company_id),
    CONSTRAINT fk_fin_account_set_company FOREIGN KEY (company_id) REFERENCES sys_company(company_id),
    CONSTRAINT fk_fin_account_set_reference_company FOREIGN KEY (reference_company_id) REFERENCES sys_company(company_id),
    CONSTRAINT fk_fin_account_set_supervisor FOREIGN KEY (supervisor_user_id) REFERENCES sys_user(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璐㈠姟璐﹀涓昏〃';

CREATE TABLE IF NOT EXISTS fin_account_set_code_rule (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涓婚敭',
    company_id VARCHAR(64) NOT NULL COMMENT '鍏徃涓讳綋缂栫爜',
    rule_type VARCHAR(32) NOT NULL COMMENT '瑙勫垯绫诲瀷',
    scheme VARCHAR(32) NOT NULL COMMENT '瑙勫垯琛ㄨ揪寮?',
    level1_length INT NOT NULL DEFAULT 4 COMMENT '涓€绾х鐩暱搴?',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    PRIMARY KEY (id),
    UNIQUE KEY uk_fin_account_set_code_rule (company_id, rule_type),
    KEY idx_fin_account_set_code_rule_company (company_id),
    CONSTRAINT fk_fin_account_set_code_rule_company FOREIGN KEY (company_id) REFERENCES sys_company(company_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璐﹀缂栫爜瑙勫垯';

CREATE TABLE IF NOT EXISTS fin_account_set_template (
    template_code VARCHAR(32) NOT NULL COMMENT '妯℃澘缂栫爜',
    template_name VARCHAR(128) NOT NULL COMMENT '妯℃澘鍚嶇О',
    accounting_standard VARCHAR(128) NOT NULL COMMENT '鍒跺害鍙ｅ緞',
    description VARCHAR(500) NULL COMMENT '妯℃澘璇存槑',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    PRIMARY KEY (template_code),
    KEY idx_fin_account_set_template_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璐﹀妯℃澘涓昏〃';

CREATE TABLE IF NOT EXISTS fin_account_set_template_subject (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涓婚敭',
    template_code VARCHAR(32) NOT NULL COMMENT '妯℃澘缂栫爜',
    subject_key VARCHAR(128) NOT NULL COMMENT '妯℃澘绉戠洰閿?',
    parent_subject_key VARCHAR(128) NULL COMMENT '鐖剁骇妯℃澘绉戠洰閿?',
    subject_level INT NOT NULL COMMENT '绉戠洰灞傜骇',
    level_segment VARCHAR(32) NOT NULL COMMENT '褰撳墠绾х紪鐮佹',
    subject_name VARCHAR(128) NOT NULL COMMENT '绉戠洰鍚嶇О',
    balance_direction VARCHAR(16) NOT NULL COMMENT '浣欓鏂瑰悜',
    subject_category VARCHAR(32) NOT NULL COMMENT '绉戠洰绫诲埆',
    leaf_flag TINYINT NOT NULL DEFAULT 1 COMMENT '鏄惁鏈骇',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    PRIMARY KEY (id),
    UNIQUE KEY uk_fin_account_set_template_subject (template_code, subject_key),
    KEY idx_fin_account_set_template_subject_parent (template_code, parent_subject_key),
    KEY idx_fin_account_set_template_subject_sort (template_code, sort_order),
    CONSTRAINT fk_fin_account_set_template_subject_template FOREIGN KEY (template_code) REFERENCES fin_account_set_template(template_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='璐﹀妯℃澘绉戠洰';

CREATE TABLE IF NOT EXISTS fin_account_subject (
    id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涓婚敭',
    company_id VARCHAR(64) NOT NULL COMMENT '鍏徃涓讳綋缂栫爜',
    subject_code VARCHAR(64) NOT NULL COMMENT '绉戠洰缂栫爜',
    subject_name VARCHAR(128) NOT NULL COMMENT '绉戠洰鍚嶇О',
    parent_subject_code VARCHAR(64) NULL COMMENT '鐖剁骇绉戠洰缂栫爜',
    subject_level INT NOT NULL COMMENT '绉戠洰灞傜骇',
    balance_direction VARCHAR(16) NOT NULL COMMENT '浣欓鏂瑰悜',
    subject_category VARCHAR(32) NOT NULL COMMENT '绉戠洰绫诲埆',
    leaf_flag TINYINT NOT NULL DEFAULT 1 COMMENT '鏄惁鏈骇',
    status TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?',
    template_code VARCHAR(32) NULL COMMENT '鏉ユ簮妯℃澘缂栫爜',
    sort_order INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    PRIMARY KEY (id),
    UNIQUE KEY uk_fin_account_subject (company_id, subject_code),
    KEY idx_fin_account_subject_company_level (company_id, subject_level, sort_order),
    KEY idx_fin_account_subject_company_parent (company_id, parent_subject_code),
    CONSTRAINT fk_fin_account_subject_company FOREIGN KEY (company_id) REFERENCES sys_company(company_id),
    CONSTRAINT fk_fin_account_subject_template FOREIGN KEY (template_code) REFERENCES fin_account_set_template(template_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='鍏徃绾т細璁＄鐩?';

ALTER TABLE fin_account_set
    MODIFY COLUMN company_id VARCHAR(64) NOT NULL COMMENT '鍏徃涓讳綋缂栫爜',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'INITIALIZING' COMMENT '璐﹀鐘舵€?',
    MODIFY COLUMN enabled_year INT NULL COMMENT '鍚敤骞村害',
    MODIFY COLUMN enabled_period INT NULL COMMENT '鍚敤鏈熼棿',
    MODIFY COLUMN template_code VARCHAR(32) NULL COMMENT '妯℃澘缂栫爜',
    MODIFY COLUMN supervisor_user_id BIGINT NULL COMMENT '璐﹀涓荤鐢ㄦ埛ID',
    MODIFY COLUMN create_mode VARCHAR(16) NOT NULL DEFAULT 'BLANK' COMMENT '鍒涘缓鏂瑰紡',
    MODIFY COLUMN reference_company_id VARCHAR(64) NULL COMMENT '鍙傜収璐﹀鍏徃',
    MODIFY COLUMN subject_code_scheme VARCHAR(32) NULL COMMENT '绉戠洰缂栫爜瑙勫垯',
    MODIFY COLUMN subject_count INT NOT NULL DEFAULT 0 COMMENT '绉戠洰鏁伴噺',
    MODIFY COLUMN last_task_no VARCHAR(32) NULL COMMENT '鏈€杩戜换鍔″彿',
    MODIFY COLUMN error_message VARCHAR(500) NULL COMMENT '澶辫触鍘熷洜',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    COMMENT = '璐㈠姟璐﹀涓昏〃';

ALTER TABLE fin_account_set_code_rule
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涓婚敭',
    MODIFY COLUMN company_id VARCHAR(64) NOT NULL COMMENT '鍏徃涓讳綋缂栫爜',
    MODIFY COLUMN rule_type VARCHAR(32) NOT NULL COMMENT '瑙勫垯绫诲瀷',
    MODIFY COLUMN scheme VARCHAR(32) NOT NULL COMMENT '瑙勫垯琛ㄨ揪寮?',
    MODIFY COLUMN level1_length INT NOT NULL DEFAULT 4 COMMENT '涓€绾х鐩暱搴?',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    COMMENT = '璐﹀缂栫爜瑙勫垯';

ALTER TABLE fin_account_set_template
    MODIFY COLUMN template_code VARCHAR(32) NOT NULL COMMENT '妯℃澘缂栫爜',
    MODIFY COLUMN template_name VARCHAR(128) NOT NULL COMMENT '妯℃澘鍚嶇О',
    MODIFY COLUMN accounting_standard VARCHAR(128) NOT NULL COMMENT '鍒跺害鍙ｅ緞',
    MODIFY COLUMN description VARCHAR(500) NULL COMMENT '妯℃澘璇存槑',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    COMMENT = '璐﹀妯℃澘涓昏〃';

ALTER TABLE fin_account_set_template_subject
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涓婚敭',
    MODIFY COLUMN template_code VARCHAR(32) NOT NULL COMMENT '妯℃澘缂栫爜',
    MODIFY COLUMN subject_key VARCHAR(128) NOT NULL COMMENT '妯℃澘绉戠洰閿?',
    MODIFY COLUMN parent_subject_key VARCHAR(128) NULL COMMENT '鐖剁骇妯℃澘绉戠洰閿?',
    MODIFY COLUMN subject_level INT NOT NULL COMMENT '绉戠洰灞傜骇',
    MODIFY COLUMN level_segment VARCHAR(32) NOT NULL COMMENT '褰撳墠绾х紪鐮佹',
    MODIFY COLUMN subject_name VARCHAR(128) NOT NULL COMMENT '绉戠洰鍚嶇О',
    MODIFY COLUMN balance_direction VARCHAR(16) NOT NULL COMMENT '浣欓鏂瑰悜',
    MODIFY COLUMN subject_category VARCHAR(32) NOT NULL COMMENT '绉戠洰绫诲埆',
    MODIFY COLUMN leaf_flag TINYINT NOT NULL DEFAULT 1 COMMENT '鏄惁鏈骇',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    COMMENT = '璐﹀妯℃澘绉戠洰';

ALTER TABLE fin_account_subject
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '涓婚敭',
    MODIFY COLUMN company_id VARCHAR(64) NOT NULL COMMENT '鍏徃涓讳綋缂栫爜',
    MODIFY COLUMN subject_code VARCHAR(64) NOT NULL COMMENT '绉戠洰缂栫爜',
    MODIFY COLUMN subject_name VARCHAR(128) NOT NULL COMMENT '绉戠洰鍚嶇О',
    MODIFY COLUMN parent_subject_code VARCHAR(64) NULL COMMENT '鐖剁骇绉戠洰缂栫爜',
    MODIFY COLUMN subject_level INT NOT NULL COMMENT '绉戠洰灞傜骇',
    MODIFY COLUMN balance_direction VARCHAR(16) NOT NULL COMMENT '浣欓鏂瑰悜',
    MODIFY COLUMN subject_category VARCHAR(32) NOT NULL COMMENT '绉戠洰绫诲埆',
    MODIFY COLUMN leaf_flag TINYINT NOT NULL DEFAULT 1 COMMENT '鏄惁鏈骇',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '鐘舵€?',
    MODIFY COLUMN template_code VARCHAR(32) NULL COMMENT '鏉ユ簮妯℃澘缂栫爜',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 0 COMMENT '鎺掑簭鍙?',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '鍒涘缓鏃堕棿',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '鏇存柊鏃堕棿',
    COMMENT = '璐﹀浼氳绉戠洰';

ALTER TABLE fin_account_set_template_subject
    ADD COLUMN cclassany VARCHAR(32) NULL COMMENT '璐㈠姟鍒嗘瀽绫诲瀷' AFTER subject_category,
    ADD COLUMN bproperty TINYINT NOT NULL DEFAULT 0 COMMENT '绉戠洰鎬ц川' AFTER cclassany,
    ADD COLUMN cbook_type VARCHAR(32) NULL COMMENT '璐﹂〉鏍煎紡' AFTER bproperty,
    ADD COLUMN chelp VARCHAR(128) NULL COMMENT '科目助记码' AFTER cbook_type,
    ADD COLUMN cexch_name VARCHAR(32) NULL COMMENT '甯佺鍚嶇О' AFTER chelp,
    ADD COLUMN cmeasure VARCHAR(64) NULL COMMENT '璁￠噺鍗曚綅' AFTER cexch_name,
    ADD COLUMN bperson TINYINT NOT NULL DEFAULT 0 COMMENT '个人往来核算' AFTER cmeasure,
    ADD COLUMN bcus TINYINT NOT NULL DEFAULT 0 COMMENT '客户往来核算' AFTER bperson,
    ADD COLUMN bsup TINYINT NOT NULL DEFAULT 0 COMMENT '供应商往来核算' AFTER bcus,
    ADD COLUMN bdept TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁閮ㄩ棬鏍哥畻' AFTER bsup,
    ADD COLUMN bitem TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁椤圭洰鏍哥畻' AFTER bdept,
    ADD COLUMN cass_item VARCHAR(64) NULL COMMENT '椤圭洰澶х被缂栫爜' AFTER bitem,
    ADD COLUMN br TINYINT NOT NULL DEFAULT 0 COMMENT '日记账' AFTER cass_item,
    ADD COLUMN be TINYINT NOT NULL DEFAULT 0 COMMENT '银行账' AFTER br,
    ADD COLUMN cgather VARCHAR(16) NULL COMMENT '汇总打印' AFTER be,
    ADD COLUMN bexchange TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鍙備笌姹囧厬鎹熺泭璁＄畻' AFTER leaf_flag,
    ADD COLUMN bcash TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鐜伴噾绉戠洰' AFTER bexchange,
    ADD COLUMN bbank TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁閾惰绉戠洰' AFTER bcash,
    ADD COLUMN bused TINYINT NOT NULL DEFAULT 0 COMMENT '银行科目启用' AFTER bbank,
    ADD COLUMN bd_c TINYINT NOT NULL DEFAULT 0 COMMENT '银行对账方向' AFTER bused,
    ADD COLUMN dbegin DATETIME NULL COMMENT '起始日期' AFTER bd_c,
    ADD COLUMN dend DATETIME NULL COMMENT '截止日期' AFTER dbegin,
    ADD COLUMN itrans TINYINT NOT NULL DEFAULT 0 COMMENT '鐗规畩绉戠洰鏍囧織' AFTER dend,
    ADD COLUMN bclose TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁灏佸瓨' AFTER itrans,
    ADD COLUMN cother VARCHAR(64) NULL COMMENT '鍙楁帶绉戠洰鍙楁帶绯荤粺鏍囪瘑' AFTER bclose,
    ADD COLUMN iotherused INT NOT NULL DEFAULT 0 COMMENT '鍏跺畠绯荤粺鏄惁浣跨敤' AFTER cother,
    ADD COLUMN bReport TINYINT NOT NULL DEFAULT 0 COMMENT '打印转账通知书' AFTER iotherused,
    ADD COLUMN bGCJS TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁宸ョ▼缁撶畻绉戠洰' AFTER bReport,
    ADD COLUMN bCashItem TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁甯哥敤鐜伴噾娴侀噺绉戠洰' AFTER bGCJS,
    ADD COLUMN iViewItem INT NOT NULL DEFAULT 0 COMMENT '鍦ㄥ缓宸ョ▼椤圭洰绉戠洰绫诲瀷' AFTER bCashItem,
    ADD COLUMN bcDefine1 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER iViewItem,
    ADD COLUMN bcDefine2 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine1,
    ADD COLUMN bcDefine3 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine2,
    ADD COLUMN bcDefine4 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine3,
    ADD COLUMN bcDefine5 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine4,
    ADD COLUMN bcDefine6 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine5,
    ADD COLUMN bcDefine7 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine6,
    ADD COLUMN bcDefine8 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine7,
    ADD COLUMN bcDefine9 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine8,
    ADD COLUMN bcDefine10 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?0' AFTER bcDefine9,
    ADD COLUMN bcDefine11 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?1' AFTER bcDefine10,
    ADD COLUMN bcDefine12 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?2' AFTER bcDefine11,
    ADD COLUMN bcDefine13 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?3' AFTER bcDefine12,
    ADD COLUMN bcDefine14 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?4' AFTER bcDefine13,
    ADD COLUMN bcDefine15 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?5' AFTER bcDefine14,
    ADD COLUMN bcDefine16 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?6' AFTER bcDefine15;

ALTER TABLE fin_account_subject
    ADD COLUMN cclassany VARCHAR(32) NULL COMMENT '璐㈠姟鍒嗘瀽绫诲瀷' AFTER subject_category,
    ADD COLUMN bproperty TINYINT NOT NULL DEFAULT 0 COMMENT '绉戠洰鎬ц川' AFTER cclassany,
    ADD COLUMN cbook_type VARCHAR(32) NULL COMMENT '璐﹂〉鏍煎紡' AFTER bproperty,
    ADD COLUMN chelp VARCHAR(128) NULL COMMENT '科目助记码' AFTER cbook_type,
    ADD COLUMN cexch_name VARCHAR(32) NULL COMMENT '甯佺鍚嶇О' AFTER chelp,
    ADD COLUMN cmeasure VARCHAR(64) NULL COMMENT '璁￠噺鍗曚綅' AFTER cexch_name,
    ADD COLUMN bperson TINYINT NOT NULL DEFAULT 0 COMMENT '个人往来核算' AFTER cmeasure,
    ADD COLUMN bcus TINYINT NOT NULL DEFAULT 0 COMMENT '客户往来核算' AFTER bperson,
    ADD COLUMN bsup TINYINT NOT NULL DEFAULT 0 COMMENT '供应商往来核算' AFTER bcus,
    ADD COLUMN bdept TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁閮ㄩ棬鏍哥畻' AFTER bsup,
    ADD COLUMN bitem TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁椤圭洰鏍哥畻' AFTER bdept,
    ADD COLUMN cass_item VARCHAR(64) NULL COMMENT '椤圭洰澶х被缂栫爜' AFTER bitem,
    ADD COLUMN br TINYINT NOT NULL DEFAULT 0 COMMENT '日记账' AFTER cass_item,
    ADD COLUMN be TINYINT NOT NULL DEFAULT 0 COMMENT '银行账' AFTER br,
    ADD COLUMN cgather VARCHAR(16) NULL COMMENT '汇总打印' AFTER be,
    ADD COLUMN bexchange TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鍙備笌姹囧厬鎹熺泭璁＄畻' AFTER leaf_flag,
    ADD COLUMN bcash TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鐜伴噾绉戠洰' AFTER bexchange,
    ADD COLUMN bbank TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁閾惰绉戠洰' AFTER bcash,
    ADD COLUMN bused TINYINT NOT NULL DEFAULT 0 COMMENT '银行科目启用' AFTER bbank,
    ADD COLUMN bd_c TINYINT NOT NULL DEFAULT 0 COMMENT '银行对账方向' AFTER bused,
    ADD COLUMN dbegin DATETIME NULL COMMENT '起始日期' AFTER bd_c,
    ADD COLUMN dend DATETIME NULL COMMENT '截止日期' AFTER dbegin,
    ADD COLUMN itrans TINYINT NOT NULL DEFAULT 0 COMMENT '鐗规畩绉戠洰鏍囧織' AFTER dend,
    ADD COLUMN bclose TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁灏佸瓨' AFTER itrans,
    ADD COLUMN cother VARCHAR(64) NULL COMMENT '鍙楁帶绉戠洰鍙楁帶绯荤粺鏍囪瘑' AFTER bclose,
    ADD COLUMN iotherused INT NOT NULL DEFAULT 0 COMMENT '鍏跺畠绯荤粺鏄惁浣跨敤' AFTER cother,
    ADD COLUMN bReport TINYINT NOT NULL DEFAULT 0 COMMENT '打印转账通知书' AFTER iotherused,
    ADD COLUMN bGCJS TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁宸ョ▼缁撶畻绉戠洰' AFTER bReport,
    ADD COLUMN bCashItem TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁甯哥敤鐜伴噾娴侀噺绉戠洰' AFTER bGCJS,
    ADD COLUMN iViewItem INT NOT NULL DEFAULT 0 COMMENT '鍦ㄥ缓宸ョ▼椤圭洰绉戠洰绫诲瀷' AFTER bCashItem,
    ADD COLUMN bcDefine1 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER iViewItem,
    ADD COLUMN bcDefine2 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine1,
    ADD COLUMN bcDefine3 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine2,
    ADD COLUMN bcDefine4 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine3,
    ADD COLUMN bcDefine5 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine4,
    ADD COLUMN bcDefine6 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine5,
    ADD COLUMN bcDefine7 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine6,
    ADD COLUMN bcDefine8 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine7,
    ADD COLUMN bcDefine9 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?' AFTER bcDefine8,
    ADD COLUMN bcDefine10 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?0' AFTER bcDefine9,
    ADD COLUMN bcDefine11 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?1' AFTER bcDefine10,
    ADD COLUMN bcDefine12 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?2' AFTER bcDefine11,
    ADD COLUMN bcDefine13 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?3' AFTER bcDefine12,
    ADD COLUMN bcDefine14 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?4' AFTER bcDefine13,
    ADD COLUMN bcDefine15 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?5' AFTER bcDefine14,
    ADD COLUMN bcDefine16 TINYINT NOT NULL DEFAULT 0 COMMENT '鏄惁鏈夎嚜瀹氫箟椤?6' AFTER bcDefine15;

UPDATE fin_account_set_template_subject
SET cclassany = COALESCE(NULLIF(cclassany, ''), subject_category),
    bproperty = COALESCE(bproperty, CASE WHEN balance_direction = 'DEBIT' THEN 1 ELSE 0 END),
    cbook_type = COALESCE(NULLIF(cbook_type, ''), CASE
        WHEN subject_key LIKE '1001%' THEN 'CASH'
        WHEN subject_key LIKE '1002%' THEN 'BANK'
        ELSE 'GENERAL'
    END),
    chelp = COALESCE(NULLIF(chelp, ''), REPLACE(subject_key, '_', '')),
    cexch_name = COALESCE(NULLIF(cexch_name, ''), 'CNY'),
    cgather = COALESCE(NULLIF(cgather, ''), '0'),
    br = COALESCE(br, CASE WHEN subject_key LIKE '1001%' OR subject_key LIKE '1002%' THEN 1 ELSE 0 END),
    be = COALESCE(be, CASE WHEN subject_key LIKE '1002%' THEN 1 ELSE 0 END),
    bexchange = COALESCE(bexchange, 0),
    bcash = COALESCE(bcash, CASE WHEN subject_key LIKE '1001%' THEN 1 ELSE 0 END),
    bbank = COALESCE(bbank, CASE WHEN subject_key LIKE '1002%' THEN 1 ELSE 0 END),
    bused = COALESCE(bused, CASE WHEN subject_key LIKE '1002%' THEN 1 ELSE 0 END),
    bd_c = COALESCE(bd_c, CASE WHEN subject_key LIKE '1002%' THEN 1 ELSE 0 END),
    itrans = COALESCE(itrans, 0),
    bclose = COALESCE(bclose, 0),
    iotherused = COALESCE(iotherused, 0),
    bReport = COALESCE(bReport, 0),
    bGCJS = COALESCE(bGCJS, 0),
    bCashItem = COALESCE(bCashItem, 0),
    iViewItem = COALESCE(iViewItem, 0),
    bcDefine1 = COALESCE(bcDefine1, 0),
    bcDefine2 = COALESCE(bcDefine2, 0),
    bcDefine3 = COALESCE(bcDefine3, 0),
    bcDefine4 = COALESCE(bcDefine4, 0),
    bcDefine5 = COALESCE(bcDefine5, 0),
    bcDefine6 = COALESCE(bcDefine6, 0),
    bcDefine7 = COALESCE(bcDefine7, 0),
    bcDefine8 = COALESCE(bcDefine8, 0),
    bcDefine9 = COALESCE(bcDefine9, 0),
    bcDefine10 = COALESCE(bcDefine10, 0),
    bcDefine11 = COALESCE(bcDefine11, 0),
    bcDefine12 = COALESCE(bcDefine12, 0),
    bcDefine13 = COALESCE(bcDefine13, 0),
    bcDefine14 = COALESCE(bcDefine14, 0),
    bcDefine15 = COALESCE(bcDefine15, 0),
    bcDefine16 = COALESCE(bcDefine16, 0)
WHERE template_code IN ('AS_2007_ENTERPRISE', 'AS_2013_SMALL_BIZ');

UPDATE fin_account_subject
SET cclassany = COALESCE(NULLIF(cclassany, ''), subject_category),
    bproperty = COALESCE(bproperty, CASE WHEN balance_direction = 'DEBIT' THEN 1 ELSE 0 END),
    cbook_type = COALESCE(NULLIF(cbook_type, ''), CASE
        WHEN subject_code LIKE '1001%' THEN 'CASH'
        WHEN subject_code LIKE '1002%' THEN 'BANK'
        ELSE 'GENERAL'
    END),
    chelp = COALESCE(NULLIF(chelp, ''), subject_code),
    cexch_name = COALESCE(NULLIF(cexch_name, ''), 'CNY'),
    cgather = COALESCE(NULLIF(cgather, ''), '0'),
    br = COALESCE(br, CASE WHEN subject_code LIKE '1001%' OR subject_code LIKE '1002%' THEN 1 ELSE 0 END),
    be = COALESCE(be, CASE WHEN subject_code LIKE '1002%' THEN 1 ELSE 0 END),
    bexchange = COALESCE(bexchange, 0),
    bcash = COALESCE(bcash, CASE WHEN subject_code LIKE '1001%' THEN 1 ELSE 0 END),
    bbank = COALESCE(bbank, CASE WHEN subject_code LIKE '1002%' THEN 1 ELSE 0 END),
    bused = COALESCE(bused, CASE WHEN subject_code LIKE '1002%' THEN 1 ELSE 0 END),
    bd_c = COALESCE(bd_c, CASE WHEN subject_code LIKE '1002%' THEN 1 ELSE 0 END),
    itrans = COALESCE(itrans, 0),
    bclose = COALESCE(bclose, 0),
    iotherused = COALESCE(iotherused, 0),
    bReport = COALESCE(bReport, 0),
    bGCJS = COALESCE(bGCJS, 0),
    bCashItem = COALESCE(bCashItem, 0),
    iViewItem = COALESCE(iViewItem, 0),
    bcDefine1 = COALESCE(bcDefine1, 0),
    bcDefine2 = COALESCE(bcDefine2, 0),
    bcDefine3 = COALESCE(bcDefine3, 0),
    bcDefine4 = COALESCE(bcDefine4, 0),
    bcDefine5 = COALESCE(bcDefine5, 0),
    bcDefine6 = COALESCE(bcDefine6, 0),
    bcDefine7 = COALESCE(bcDefine7, 0),
    bcDefine8 = COALESCE(bcDefine8, 0),
    bcDefine9 = COALESCE(bcDefine9, 0),
    bcDefine10 = COALESCE(bcDefine10, 0),
    bcDefine11 = COALESCE(bcDefine11, 0),
    bcDefine12 = COALESCE(bcDefine12, 0),
    bcDefine13 = COALESCE(bcDefine13, 0),
    bcDefine14 = COALESCE(bcDefine14, 0),
    bcDefine15 = COALESCE(bcDefine15, 0),
    bcDefine16 = COALESCE(bcDefine16, 0);

INSERT INTO fin_account_set_template (
    template_code,
    template_name,
    accounting_standard,
    description,
    status
) VALUES
    ('AS_2007_ENTERPRISE', '2007 企业会计制度', '2007 企业会计制度', '适用于企业会计制度口径，预置完整一级科目与常用二级科目。', 1),
    ('AS_2013_SMALL_BIZ', '2013 小企业会计准则', '2013 小企业会计准则', '适用于小企业会计准则口径，预置完整一级科目与常用二级科目。', 1)
ON DUPLICATE KEY UPDATE
    template_name = VALUES(template_name),
    accounting_standard = VALUES(accounting_standard),
    description = VALUES(description),
    status = VALUES(status);

DELETE FROM fin_account_set_template_subject
WHERE template_code IN ('AS_2007_ENTERPRISE', 'AS_2013_SMALL_BIZ');

INSERT INTO fin_account_set_template_subject (
    template_code,
    subject_key,
    parent_subject_key,
    subject_level,
    level_segment,
    subject_name,
    balance_direction,
    subject_category,
    leaf_flag,
    sort_order,
    status
) VALUES
    ('AS_2007_ENTERPRISE', '1001', NULL, 1, '1001', '搴撳瓨鐜伴噾', 'DEBIT', 'ASSET', 1, 1001, 1),
    ('AS_2007_ENTERPRISE', '1002', NULL, 1, '1002', '閾惰瀛樻', 'DEBIT', 'ASSET', 0, 1002, 1),
    ('AS_2007_ENTERPRISE', '1002_01', '1002', 2, '01', '宸ュ晢閾惰瀛樻', 'DEBIT', 'ASSET', 1, 100201, 1),
    ('AS_2007_ENTERPRISE', '1002_02', '1002', 2, '02', '寤鸿閾惰瀛樻', 'DEBIT', 'ASSET', 1, 100202, 1),
    ('AS_2007_ENTERPRISE', '1012', NULL, 1, '1012', '鍏朵粬璐у竵璧勯噾', 'DEBIT', 'ASSET', 1, 1012, 1),
    ('AS_2007_ENTERPRISE', '1101', NULL, 1, '1101', '浜ゆ槗鎬ч噾铻嶈祫浜?', 'DEBIT', 'ASSET', 1, 1101, 1),
    ('AS_2007_ENTERPRISE', '1121', NULL, 1, '1121', '搴旀敹绁ㄦ嵁', 'DEBIT', 'ASSET', 1, 1121, 1),
    ('AS_2007_ENTERPRISE', '1122', NULL, 1, '1122', '搴旀敹璐︽', 'DEBIT', 'ASSET', 0, 1122, 1),
    ('AS_2007_ENTERPRISE', '1122_01', '1122', 2, '01', '搴旀敹閿€璐ф', 'DEBIT', 'ASSET', 1, 112201, 1),
    ('AS_2007_ENTERPRISE', '1122_02', '1122', 2, '02', '搴旀敹鏈嶅姟娆?', 'DEBIT', 'ASSET', 1, 112202, 1),
    ('AS_2007_ENTERPRISE', '1123', NULL, 1, '1123', '棰勪粯璐︽', 'DEBIT', 'ASSET', 1, 1123, 1),
    ('AS_2007_ENTERPRISE', '1131', NULL, 1, '1131', '搴旀敹鑲″埄', 'DEBIT', 'ASSET', 1, 1131, 1),
    ('AS_2007_ENTERPRISE', '1132', NULL, 1, '1132', '搴旀敹鍒╂伅', 'DEBIT', 'ASSET', 1, 1132, 1),
    ('AS_2007_ENTERPRISE', '1221', NULL, 1, '1221', '鍏朵粬搴旀敹娆?', 'DEBIT', 'ASSET', 1, 1221, 1),
    ('AS_2007_ENTERPRISE', '1231', NULL, 1, '1231', '鍧忚处鍑嗗', 'CREDIT', 'ASSET', 1, 1231, 1),
    ('AS_2007_ENTERPRISE', '1401', NULL, 1, '1401', '鏉愭枡閲囪喘', 'DEBIT', 'ASSET', 1, 1401, 1),
    ('AS_2007_ENTERPRISE', '1402', NULL, 1, '1402', '鍦ㄩ€旂墿璧?', 'DEBIT', 'ASSET', 1, 1402, 1),
    ('AS_2007_ENTERPRISE', '1403', NULL, 1, '1403', '鍘熸潗鏂?', 'DEBIT', 'ASSET', 1, 1403, 1),
    ('AS_2007_ENTERPRISE', '1405', NULL, 1, '1405', '搴撳瓨鍟嗗搧', 'DEBIT', 'ASSET', 1, 1405, 1),
    ('AS_2007_ENTERPRISE', '1406', NULL, 1, '1406', '鍙戝嚭鍟嗗搧', 'DEBIT', 'ASSET', 1, 1406, 1),
    ('AS_2007_ENTERPRISE', '1407', NULL, 1, '1407', '鍟嗗搧杩涢攢宸环', 'DEBIT', 'ASSET', 1, 1407, 1),
    ('AS_2007_ENTERPRISE', '1408', NULL, 1, '1408', '濮旀墭鍔犲伐鐗╄祫', 'DEBIT', 'ASSET', 1, 1408, 1),
    ('AS_2007_ENTERPRISE', '1411', NULL, 1, '1411', '鍛ㄨ浆鏉愭枡', 'DEBIT', 'ASSET', 1, 1411, 1),
    ('AS_2007_ENTERPRISE', '1471', NULL, 1, '1471', '瀛樿揣璺屼环鍑嗗', 'CREDIT', 'ASSET', 1, 1471, 1),
    ('AS_2007_ENTERPRISE', '1501', NULL, 1, '1501', '鎸佹湁鑷冲埌鏈熸姇璧?', 'DEBIT', 'ASSET', 1, 1501, 1),
    ('AS_2007_ENTERPRISE', '1503', NULL, 1, '1503', '鍙緵鍑哄敭閲戣瀺璧勪骇', 'DEBIT', 'ASSET', 1, 1503, 1),
    ('AS_2007_ENTERPRISE', '1511', NULL, 1, '1511', '闀挎湡鑲℃潈鎶曡祫', 'DEBIT', 'ASSET', 1, 1511, 1),
    ('AS_2007_ENTERPRISE', '1521', NULL, 1, '1521', '鎶曡祫鎬ф埧鍦颁骇', 'DEBIT', 'ASSET', 1, 1521, 1),
    ('AS_2007_ENTERPRISE', '1531', NULL, 1, '1531', '闀挎湡搴旀敹娆?', 'DEBIT', 'ASSET', 1, 1531, 1),
    ('AS_2007_ENTERPRISE', '1601', NULL, 1, '1601', '鍥哄畾璧勪骇', 'DEBIT', 'ASSET', 0, 1601, 1),
    ('AS_2007_ENTERPRISE', '1601_01', '1601', 2, '01', '鎴垮眿寤虹瓚鐗?', 'DEBIT', 'ASSET', 1, 160101, 1),
    ('AS_2007_ENTERPRISE', '1601_02', '1601', 2, '02', '鏈哄櫒璁惧', 'DEBIT', 'ASSET', 1, 160102, 1),
    ('AS_2007_ENTERPRISE', '1602', NULL, 1, '1602', '绱鎶樻棫', 'CREDIT', 'ASSET', 0, 1602, 1),
    ('AS_2007_ENTERPRISE', '1602_01', '1602', 2, '01', '鎴垮眿寤虹瓚鐗╂姌鏃?', 'CREDIT', 'ASSET', 1, 160201, 1),
    ('AS_2007_ENTERPRISE', '1602_02', '1602', 2, '02', '鏈哄櫒璁惧鎶樻棫', 'CREDIT', 'ASSET', 1, 160202, 1),
    ('AS_2007_ENTERPRISE', '1603', NULL, 1, '1603', '鍥哄畾璧勪骇鍑忓€煎噯澶?', 'CREDIT', 'ASSET', 1, 1603, 1),
    ('AS_2007_ENTERPRISE', '1604', NULL, 1, '1604', '鍦ㄥ缓宸ョ▼', 'DEBIT', 'ASSET', 1, 1604, 1),
    ('AS_2007_ENTERPRISE', '1605', NULL, 1, '1605', '宸ョ▼鐗╄祫', 'DEBIT', 'ASSET', 1, 1605, 1),
    ('AS_2007_ENTERPRISE', '1606', NULL, 1, '1606', '鍥哄畾璧勪骇娓呯悊', 'DEBIT', 'ASSET', 1, 1606, 1),
    ('AS_2007_ENTERPRISE', '1701', NULL, 1, '1701', '鏃犲舰璧勪骇', 'DEBIT', 'ASSET', 1, 1701, 1),
    ('AS_2007_ENTERPRISE', '1702', NULL, 1, '1702', '绱鎽婇攢', 'CREDIT', 'ASSET', 1, 1702, 1),
    ('AS_2007_ENTERPRISE', '1703', NULL, 1, '1703', '鏃犲舰璧勪骇鍑忓€煎噯澶?', 'CREDIT', 'ASSET', 1, 1703, 1),
    ('AS_2007_ENTERPRISE', '1711', NULL, 1, '1711', '鍟嗚獕', 'DEBIT', 'ASSET', 1, 1711, 1),
    ('AS_2007_ENTERPRISE', '1801', NULL, 1, '1801', '闀挎湡寰呮憡璐圭敤', 'DEBIT', 'ASSET', 1, 1801, 1),
    ('AS_2007_ENTERPRISE', '1811', NULL, 1, '1811', '閫掑欢鎵€寰楃◣璧勪骇', 'DEBIT', 'ASSET', 1, 1811, 1),
    ('AS_2007_ENTERPRISE', '1901', NULL, 1, '1901', '寰呭鐞嗚储浜ф崯婧?', 'DEBIT', 'ASSET', 1, 1901, 1),
    ('AS_2007_ENTERPRISE', '2001', NULL, 1, '2001', '鐭湡鍊熸', 'CREDIT', 'LIABILITY', 1, 2001, 1),
    ('AS_2007_ENTERPRISE', '2201', NULL, 1, '2201', '搴斾粯绁ㄦ嵁', 'CREDIT', 'LIABILITY', 1, 2201, 1),
    ('AS_2007_ENTERPRISE', '2202', NULL, 1, '2202', '搴斾粯璐︽', 'CREDIT', 'LIABILITY', 0, 2202, 1),
    ('AS_2007_ENTERPRISE', '2202_01', '2202', 2, '01', '搴斾粯閲囪喘娆?', 'CREDIT', 'LIABILITY', 1, 220201, 1),
    ('AS_2007_ENTERPRISE', '2202_02', '2202', 2, '02', '搴斾粯鏈嶅姟璐?', 'CREDIT', 'LIABILITY', 1, 220202, 1),
    ('AS_2007_ENTERPRISE', '2205', NULL, 1, '2205', '棰勬敹璐︽', 'CREDIT', 'LIABILITY', 1, 2205, 1),
    ('AS_2007_ENTERPRISE', '2211', NULL, 1, '2211', '搴斾粯鑱屽伐钖叕', 'CREDIT', 'LIABILITY', 1, 2211, 1),
    ('AS_2007_ENTERPRISE', '2221', NULL, 1, '2221', '搴斾氦绋庤垂', 'CREDIT', 'LIABILITY', 0, 2221, 1),
    ('AS_2007_ENTERPRISE', '2221_01', '2221', 2, '01', '搴斾氦澧炲€肩◣', 'CREDIT', 'LIABILITY', 1, 222101, 1),
    ('AS_2007_ENTERPRISE', '2221_02', '2221', 2, '02', '搴斾氦鍩庡競缁存姢寤鸿绋?', 'CREDIT', 'LIABILITY', 1, 222102, 1),
    ('AS_2007_ENTERPRISE', '2231', NULL, 1, '2231', '搴斾粯鍒╂伅', 'CREDIT', 'LIABILITY', 1, 2231, 1),
    ('AS_2007_ENTERPRISE', '2232', NULL, 1, '2232', '搴斾粯鑲″埄', 'CREDIT', 'LIABILITY', 1, 2232, 1),
    ('AS_2007_ENTERPRISE', '2241', NULL, 1, '2241', '鍏朵粬搴斾粯娆?', 'CREDIT', 'LIABILITY', 1, 2241, 1),
    ('AS_2007_ENTERPRISE', '2501', NULL, 1, '2501', '闀挎湡鍊熸', 'CREDIT', 'LIABILITY', 1, 2501, 1),
    ('AS_2007_ENTERPRISE', '2502', NULL, 1, '2502', '搴斾粯鍊哄埜', 'CREDIT', 'LIABILITY', 1, 2502, 1),
    ('AS_2007_ENTERPRISE', '2701', NULL, 1, '2701', '闀挎湡搴斾粯娆?', 'CREDIT', 'LIABILITY', 1, 2701, 1),
    ('AS_2007_ENTERPRISE', '2711', NULL, 1, '2711', '涓撻」搴斾粯娆?', 'CREDIT', 'LIABILITY', 1, 2711, 1),
    ('AS_2007_ENTERPRISE', '2801', NULL, 1, '2801', '棰勮璐熷€?', 'CREDIT', 'LIABILITY', 1, 2801, 1),
    ('AS_2007_ENTERPRISE', '2901', NULL, 1, '2901', '閫掑欢鎵€寰楃◣璐熷€?', 'CREDIT', 'LIABILITY', 1, 2901, 1),
    ('AS_2007_ENTERPRISE', '3001', NULL, 1, '3001', '瀹炴敹璧勬湰', 'CREDIT', 'EQUITY', 1, 3001, 1),
    ('AS_2007_ENTERPRISE', '3002', NULL, 1, '3002', '璧勬湰鍏Н', 'CREDIT', 'EQUITY', 1, 3002, 1),
    ('AS_2007_ENTERPRISE', '3101', NULL, 1, '3101', '鐩堜綑鍏Н', 'CREDIT', 'EQUITY', 1, 3101, 1),
    ('AS_2007_ENTERPRISE', '3103', NULL, 1, '3103', '鏈勾鍒╂鼎', 'CREDIT', 'EQUITY', 1, 3103, 1),
    ('AS_2007_ENTERPRISE', '3104', NULL, 1, '3104', '鍒╂鼎鍒嗛厤', 'CREDIT', 'EQUITY', 1, 3104, 1),
    ('AS_2007_ENTERPRISE', '4001', NULL, 1, '4001', '鐢熶骇鎴愭湰', 'DEBIT', 'COST', 1, 4001, 1),
    ('AS_2007_ENTERPRISE', '4101', NULL, 1, '4101', '鍒堕€犺垂鐢?', 'DEBIT', 'COST', 1, 4101, 1),
    ('AS_2007_ENTERPRISE', '4301', NULL, 1, '4301', '鐮斿彂鏀嚭', 'DEBIT', 'COST', 1, 4301, 1),
    ('AS_2007_ENTERPRISE', '5001', NULL, 1, '5001', '涓昏惀涓氬姟鏀跺叆', 'CREDIT', 'PROFIT', 0, 5001, 1),
    ('AS_2007_ENTERPRISE', '5001_01', '5001', 2, '01', '鍟嗗搧閿€鍞敹鍏?', 'CREDIT', 'PROFIT', 1, 500101, 1),
    ('AS_2007_ENTERPRISE', '5001_02', '5001', 2, '02', '鏈嶅姟鏀跺叆', 'CREDIT', 'PROFIT', 1, 500102, 1),
    ('AS_2007_ENTERPRISE', '5051', NULL, 1, '5051', '鍏朵粬涓氬姟鏀跺叆', 'CREDIT', 'PROFIT', 1, 5051, 1),
    ('AS_2007_ENTERPRISE', '5111', NULL, 1, '5111', '鎶曡祫鏀剁泭', 'CREDIT', 'PROFIT', 1, 5111, 1),
    ('AS_2007_ENTERPRISE', '5301', NULL, 1, '5301', '钀ヤ笟澶栨敹鍏?', 'CREDIT', 'PROFIT', 1, 5301, 1),
    ('AS_2007_ENTERPRISE', '5401', NULL, 1, '5401', '涓昏惀涓氬姟鎴愭湰', 'DEBIT', 'PROFIT', 0, 5401, 1),
    ('AS_2007_ENTERPRISE', '5401_01', '5401', 2, '01', '鍟嗗搧閿€鍞垚鏈?', 'DEBIT', 'PROFIT', 1, 540101, 1),
    ('AS_2007_ENTERPRISE', '5401_02', '5401', 2, '02', '鏈嶅姟鎴愭湰', 'DEBIT', 'PROFIT', 1, 540102, 1),
    ('AS_2007_ENTERPRISE', '5402', NULL, 1, '5402', '鍏朵粬涓氬姟鎴愭湰', 'DEBIT', 'PROFIT', 1, 5402, 1),
    ('AS_2007_ENTERPRISE', '5403', NULL, 1, '5403', '绋庨噾鍙婇檮鍔?', 'DEBIT', 'PROFIT', 1, 5403, 1),
    ('AS_2007_ENTERPRISE', '5601', NULL, 1, '5601', '閿€鍞垂鐢?', 'DEBIT', 'PROFIT', 0, 5601, 1),
    ('AS_2007_ENTERPRISE', '5601_01', '5601', 2, '01', '骞垮憡瀹ｄ紶璐?', 'DEBIT', 'PROFIT', 1, 560101, 1),
    ('AS_2007_ENTERPRISE', '5601_02', '5601', 2, '02', '灞曚細鏈嶅姟璐?', 'DEBIT', 'PROFIT', 1, 560102, 1),
    ('AS_2007_ENTERPRISE', '6601', NULL, 1, '6601', '閿€鍞垂鐢?', 'DEBIT', 'PROFIT', 1, 6601, 1),
    ('AS_2007_ENTERPRISE', '6602', NULL, 1, '6602', '绠＄悊璐圭敤', 'DEBIT', 'PROFIT', 0, 6602, 1),
    ('AS_2007_ENTERPRISE', '6602_01', '6602', 2, '01', '鍔炲叕璐?', 'DEBIT', 'PROFIT', 1, 660201, 1),
    ('AS_2007_ENTERPRISE', '6602_02', '6602', 2, '02', '鎶樻棫鎽婇攢', 'DEBIT', 'PROFIT', 1, 660202, 1),
    ('AS_2007_ENTERPRISE', '6602_03', '6602', 2, '03', '宸梾璐?', 'DEBIT', 'PROFIT', 1, 660203, 1),
    ('AS_2007_ENTERPRISE', '6603', NULL, 1, '6603', '璐㈠姟璐圭敤', 'DEBIT', 'PROFIT', 0, 6603, 1),
    ('AS_2007_ENTERPRISE', '6603_01', '6603', 2, '01', '鍒╂伅鏀嚭', 'DEBIT', 'PROFIT', 1, 660301, 1),
    ('AS_2007_ENTERPRISE', '6603_02', '6603', 2, '02', '鎵嬬画璐?', 'DEBIT', 'PROFIT', 1, 660302, 1),
    ('AS_2007_ENTERPRISE', '6701', NULL, 1, '6701', '璧勪骇鍑忓€兼崯澶?', 'DEBIT', 'PROFIT', 1, 6701, 1),
    ('AS_2007_ENTERPRISE', '6711', NULL, 1, '6711', '钀ヤ笟澶栨敮鍑?', 'DEBIT', 'PROFIT', 1, 6711, 1),
    ('AS_2007_ENTERPRISE', '6801', NULL, 1, '6801', '鎵€寰楃◣璐圭敤', 'DEBIT', 'PROFIT', 1, 6801, 1),
    ('AS_2007_ENTERPRISE', '6901', NULL, 1, '6901', '浠ュ墠骞村害鎹熺泭璋冩暣', 'DEBIT', 'PROFIT', 1, 6901, 1),

    ('AS_2013_SMALL_BIZ', '1001', NULL, 1, '1001', '搴撳瓨鐜伴噾', 'DEBIT', 'ASSET', 1, 1001, 1),
    ('AS_2013_SMALL_BIZ', '1002', NULL, 1, '1002', '閾惰瀛樻', 'DEBIT', 'ASSET', 0, 1002, 1),
    ('AS_2013_SMALL_BIZ', '1002_01', '1002', 2, '01', '鍩烘湰鎴峰瓨娆?', 'DEBIT', 'ASSET', 1, 100201, 1),
    ('AS_2013_SMALL_BIZ', '1002_02', '1002', 2, '02', '涓€鑸埛瀛樻', 'DEBIT', 'ASSET', 1, 100202, 1),
    ('AS_2013_SMALL_BIZ', '1121', NULL, 1, '1121', '搴旀敹绁ㄦ嵁', 'DEBIT', 'ASSET', 1, 1121, 1),
    ('AS_2013_SMALL_BIZ', '1122', NULL, 1, '1122', '搴旀敹璐︽', 'DEBIT', 'ASSET', 0, 1122, 1),
    ('AS_2013_SMALL_BIZ', '1122_01', '1122', 2, '01', '搴旀敹閿€璐ф', 'DEBIT', 'ASSET', 1, 112201, 1),
    ('AS_2013_SMALL_BIZ', '1122_02', '1122', 2, '02', '搴旀敹鍔冲姟娆?', 'DEBIT', 'ASSET', 1, 112202, 1),
    ('AS_2013_SMALL_BIZ', '1123', NULL, 1, '1123', '棰勪粯璐︽', 'DEBIT', 'ASSET', 1, 1123, 1),
    ('AS_2013_SMALL_BIZ', '1131', NULL, 1, '1131', '搴旀敹鑲″埄', 'DEBIT', 'ASSET', 1, 1131, 1),
    ('AS_2013_SMALL_BIZ', '1132', NULL, 1, '1132', '搴旀敹鍒╂伅', 'DEBIT', 'ASSET', 1, 1132, 1),
    ('AS_2013_SMALL_BIZ', '1221', NULL, 1, '1221', '鍏朵粬搴旀敹娆?', 'DEBIT', 'ASSET', 1, 1221, 1),
    ('AS_2013_SMALL_BIZ', '1231', NULL, 1, '1231', '鍧忚处鍑嗗', 'CREDIT', 'ASSET', 1, 1231, 1),
    ('AS_2013_SMALL_BIZ', '1401', NULL, 1, '1401', '鏉愭枡閲囪喘', 'DEBIT', 'ASSET', 1, 1401, 1),
    ('AS_2013_SMALL_BIZ', '1402', NULL, 1, '1402', '鍦ㄩ€旂墿璧?', 'DEBIT', 'ASSET', 1, 1402, 1),
    ('AS_2013_SMALL_BIZ', '1403', NULL, 1, '1403', '鍘熸潗鏂?', 'DEBIT', 'ASSET', 1, 1403, 1),
    ('AS_2013_SMALL_BIZ', '1405', NULL, 1, '1405', '搴撳瓨鍟嗗搧', 'DEBIT', 'ASSET', 1, 1405, 1),
    ('AS_2013_SMALL_BIZ', '1407', NULL, 1, '1407', '鍟嗗搧杩涢攢宸环', 'DEBIT', 'ASSET', 1, 1407, 1),
    ('AS_2013_SMALL_BIZ', '1408', NULL, 1, '1408', '濮旀墭鍔犲伐鐗╄祫', 'DEBIT', 'ASSET', 1, 1408, 1),
    ('AS_2013_SMALL_BIZ', '1411', NULL, 1, '1411', '鍛ㄨ浆鏉愭枡', 'DEBIT', 'ASSET', 1, 1411, 1),
    ('AS_2013_SMALL_BIZ', '1471', NULL, 1, '1471', '瀛樿揣璺屼环鍑嗗', 'CREDIT', 'ASSET', 1, 1471, 1),
    ('AS_2013_SMALL_BIZ', '1501', NULL, 1, '1501', '闀挎湡鍊哄埜鎶曡祫', 'DEBIT', 'ASSET', 1, 1501, 1),
    ('AS_2013_SMALL_BIZ', '1511', NULL, 1, '1511', '闀挎湡鑲℃潈鎶曡祫', 'DEBIT', 'ASSET', 1, 1511, 1),
    ('AS_2013_SMALL_BIZ', '1601', NULL, 1, '1601', '鍥哄畾璧勪骇', 'DEBIT', 'ASSET', 0, 1601, 1),
    ('AS_2013_SMALL_BIZ', '1601_01', '1601', 2, '01', '鎴垮眿寤虹瓚鐗?', 'DEBIT', 'ASSET', 1, 160101, 1),
    ('AS_2013_SMALL_BIZ', '1601_02', '1601', 2, '02', '鏈哄櫒璁惧', 'DEBIT', 'ASSET', 1, 160102, 1),
    ('AS_2013_SMALL_BIZ', '1602', NULL, 1, '1602', '绱鎶樻棫', 'CREDIT', 'ASSET', 0, 1602, 1),
    ('AS_2013_SMALL_BIZ', '1602_01', '1602', 2, '01', '鎴垮眿寤虹瓚鐗╂姌鏃?', 'CREDIT', 'ASSET', 1, 160201, 1),
    ('AS_2013_SMALL_BIZ', '1602_02', '1602', 2, '02', '鏈哄櫒璁惧鎶樻棫', 'CREDIT', 'ASSET', 1, 160202, 1),
    ('AS_2013_SMALL_BIZ', '1603', NULL, 1, '1603', '鍥哄畾璧勪骇鍑忓€煎噯澶?', 'CREDIT', 'ASSET', 1, 1603, 1),
    ('AS_2013_SMALL_BIZ', '1604', NULL, 1, '1604', '鍦ㄥ缓宸ョ▼', 'DEBIT', 'ASSET', 1, 1604, 1),
    ('AS_2013_SMALL_BIZ', '1605', NULL, 1, '1605', '宸ョ▼鐗╄祫', 'DEBIT', 'ASSET', 1, 1605, 1),
    ('AS_2013_SMALL_BIZ', '1606', NULL, 1, '1606', '鍥哄畾璧勪骇娓呯悊', 'DEBIT', 'ASSET', 1, 1606, 1),
    ('AS_2013_SMALL_BIZ', '1701', NULL, 1, '1701', '鏃犲舰璧勪骇', 'DEBIT', 'ASSET', 1, 1701, 1),
    ('AS_2013_SMALL_BIZ', '1702', NULL, 1, '1702', '绱鎽婇攢', 'CREDIT', 'ASSET', 1, 1702, 1),
    ('AS_2013_SMALL_BIZ', '1801', NULL, 1, '1801', '闀挎湡寰呮憡璐圭敤', 'DEBIT', 'ASSET', 1, 1801, 1),
    ('AS_2013_SMALL_BIZ', '1901', NULL, 1, '1901', '寰呭鐞嗚储浜ф崯婧?', 'DEBIT', 'ASSET', 1, 1901, 1),
    ('AS_2013_SMALL_BIZ', '2001', NULL, 1, '2001', '鐭湡鍊熸', 'CREDIT', 'LIABILITY', 1, 2001, 1),
    ('AS_2013_SMALL_BIZ', '2201', NULL, 1, '2201', '搴斾粯绁ㄦ嵁', 'CREDIT', 'LIABILITY', 1, 2201, 1),
    ('AS_2013_SMALL_BIZ', '2202', NULL, 1, '2202', '搴斾粯璐︽', 'CREDIT', 'LIABILITY', 0, 2202, 1),
    ('AS_2013_SMALL_BIZ', '2202_01', '2202', 2, '01', '搴斾粯閲囪喘娆?', 'CREDIT', 'LIABILITY', 1, 220201, 1),
    ('AS_2013_SMALL_BIZ', '2202_02', '2202', 2, '02', '搴斾粯鏈嶅姟璐?', 'CREDIT', 'LIABILITY', 1, 220202, 1),
    ('AS_2013_SMALL_BIZ', '2203', NULL, 1, '2203', '棰勬敹璐︽', 'CREDIT', 'LIABILITY', 1, 2203, 1),
    ('AS_2013_SMALL_BIZ', '2211', NULL, 1, '2211', '搴斾粯鑱屽伐钖叕', 'CREDIT', 'LIABILITY', 1, 2211, 1),
    ('AS_2013_SMALL_BIZ', '2221', NULL, 1, '2221', '搴斾氦绋庤垂', 'CREDIT', 'LIABILITY', 0, 2221, 1),
    ('AS_2013_SMALL_BIZ', '2221_01', '2221', 2, '01', '搴斾氦澧炲€肩◣', 'CREDIT', 'LIABILITY', 1, 222101, 1),
    ('AS_2013_SMALL_BIZ', '2221_02', '2221', 2, '02', '搴斾氦闄勫姞绋庤垂', 'CREDIT', 'LIABILITY', 1, 222102, 1),
    ('AS_2013_SMALL_BIZ', '2231', NULL, 1, '2231', '搴斾粯鍒╂伅', 'CREDIT', 'LIABILITY', 1, 2231, 1),
    ('AS_2013_SMALL_BIZ', '2232', NULL, 1, '2232', '搴斾粯鍒╂鼎', 'CREDIT', 'LIABILITY', 1, 2232, 1),
    ('AS_2013_SMALL_BIZ', '2241', NULL, 1, '2241', '鍏朵粬搴斾粯娆?', 'CREDIT', 'LIABILITY', 1, 2241, 1),
    ('AS_2013_SMALL_BIZ', '2401', NULL, 1, '2401', '閫掑欢鏀剁泭', 'CREDIT', 'LIABILITY', 1, 2401, 1),
    ('AS_2013_SMALL_BIZ', '2501', NULL, 1, '2501', '闀挎湡鍊熸', 'CREDIT', 'LIABILITY', 1, 2501, 1),
    ('AS_2013_SMALL_BIZ', '2701', NULL, 1, '2701', '闀挎湡搴斾粯娆?', 'CREDIT', 'LIABILITY', 1, 2701, 1),
    ('AS_2013_SMALL_BIZ', '3001', NULL, 1, '3001', '瀹炴敹璧勬湰', 'CREDIT', 'EQUITY', 1, 3001, 1),
    ('AS_2013_SMALL_BIZ', '3002', NULL, 1, '3002', '璧勬湰鍏Н', 'CREDIT', 'EQUITY', 1, 3002, 1),
    ('AS_2013_SMALL_BIZ', '3101', NULL, 1, '3101', '鐩堜綑鍏Н', 'CREDIT', 'EQUITY', 1, 3101, 1),
    ('AS_2013_SMALL_BIZ', '3103', NULL, 1, '3103', '鏈勾鍒╂鼎', 'CREDIT', 'EQUITY', 1, 3103, 1),
    ('AS_2013_SMALL_BIZ', '3104', NULL, 1, '3104', '鍒╂鼎鍒嗛厤', 'CREDIT', 'EQUITY', 1, 3104, 1),
    ('AS_2013_SMALL_BIZ', '4001', NULL, 1, '4001', '鐢熶骇鎴愭湰', 'DEBIT', 'COST', 1, 4001, 1),
    ('AS_2013_SMALL_BIZ', '4101', NULL, 1, '4101', '鍒堕€犺垂鐢?', 'DEBIT', 'COST', 1, 4101, 1),
    ('AS_2013_SMALL_BIZ', '4301', NULL, 1, '4301', '鐮斿彂鏀嚭', 'DEBIT', 'COST', 1, 4301, 1),
    ('AS_2013_SMALL_BIZ', '5001', NULL, 1, '5001', '涓昏惀涓氬姟鏀跺叆', 'CREDIT', 'PROFIT', 0, 5001, 1),
    ('AS_2013_SMALL_BIZ', '5001_01', '5001', 2, '01', '鍟嗗搧閿€鍞敹鍏?', 'CREDIT', 'PROFIT', 1, 500101, 1),
    ('AS_2013_SMALL_BIZ', '5001_02', '5001', 2, '02', '鏈嶅姟鏀跺叆', 'CREDIT', 'PROFIT', 1, 500102, 1),
    ('AS_2013_SMALL_BIZ', '5051', NULL, 1, '5051', '鍏朵粬涓氬姟鏀跺叆', 'CREDIT', 'PROFIT', 1, 5051, 1),
    ('AS_2013_SMALL_BIZ', '5111', NULL, 1, '5111', '鎶曡祫鏀剁泭', 'CREDIT', 'PROFIT', 1, 5111, 1),
    ('AS_2013_SMALL_BIZ', '5301', NULL, 1, '5301', '钀ヤ笟澶栨敹鍏?', 'CREDIT', 'PROFIT', 1, 5301, 1),
    ('AS_2013_SMALL_BIZ', '5401', NULL, 1, '5401', '涓昏惀涓氬姟鎴愭湰', 'DEBIT', 'PROFIT', 0, 5401, 1),
    ('AS_2013_SMALL_BIZ', '5401_01', '5401', 2, '01', '鍟嗗搧閿€鍞垚鏈?', 'DEBIT', 'PROFIT', 1, 540101, 1),
    ('AS_2013_SMALL_BIZ', '5401_02', '5401', 2, '02', '鏈嶅姟鎴愭湰', 'DEBIT', 'PROFIT', 1, 540102, 1),
    ('AS_2013_SMALL_BIZ', '5402', NULL, 1, '5402', '鍏朵粬涓氬姟鎴愭湰', 'DEBIT', 'PROFIT', 1, 5402, 1),
    ('AS_2013_SMALL_BIZ', '5403', NULL, 1, '5403', '绋庨噾鍙婇檮鍔?', 'DEBIT', 'PROFIT', 1, 5403, 1),
    ('AS_2013_SMALL_BIZ', '5601', NULL, 1, '5601', '閿€鍞垂鐢?', 'DEBIT', 'PROFIT', 0, 5601, 1),
    ('AS_2013_SMALL_BIZ', '5601_01', '5601', 2, '01', '骞垮憡瀹ｄ紶璐?', 'DEBIT', 'PROFIT', 1, 560101, 1),
    ('AS_2013_SMALL_BIZ', '5601_02', '5601', 2, '02', '鐗╂祦閰嶉€佽垂', 'DEBIT', 'PROFIT', 1, 560102, 1),
    ('AS_2013_SMALL_BIZ', '5602', NULL, 1, '5602', '绠＄悊璐圭敤', 'DEBIT', 'PROFIT', 0, 5602, 1),
    ('AS_2013_SMALL_BIZ', '5602_01', '5602', 2, '01', '鍔炲叕璐?', 'DEBIT', 'PROFIT', 1, 560201, 1),
    ('AS_2013_SMALL_BIZ', '5602_02', '5602', 2, '02', '鎶樻棫鎽婇攢', 'DEBIT', 'PROFIT', 1, 560202, 1),
    ('AS_2013_SMALL_BIZ', '5602_03', '5602', 2, '03', '宸梾璐?', 'DEBIT', 'PROFIT', 1, 560203, 1),
    ('AS_2013_SMALL_BIZ', '5603', NULL, 1, '5603', '璐㈠姟璐圭敤', 'DEBIT', 'PROFIT', 0, 5603, 1),
    ('AS_2013_SMALL_BIZ', '5603_01', '5603', 2, '01', '鍒╂伅鏀嚭', 'DEBIT', 'PROFIT', 1, 560301, 1),
    ('AS_2013_SMALL_BIZ', '5603_02', '5603', 2, '02', '鎵嬬画璐?', 'DEBIT', 'PROFIT', 1, 560302, 1),
    ('AS_2013_SMALL_BIZ', '5711', NULL, 1, '5711', '钀ヤ笟澶栨敮鍑?', 'DEBIT', 'PROFIT', 1, 5711, 1),
    ('AS_2013_SMALL_BIZ', '5801', NULL, 1, '5801', '鎵€寰楃◣璐圭敤', 'DEBIT', 'PROFIT', 1, 5801, 1),
    ('AS_2013_SMALL_BIZ', '6301', NULL, 1, '6301', '钀ヤ笟澶栨敹鍏?', 'CREDIT', 'PROFIT', 1, 6301, 1),
    ('AS_2013_SMALL_BIZ', '6711', NULL, 1, '6711', '钀ヤ笟澶栨敮鍑?', 'DEBIT', 'PROFIT', 1, 6711, 1);



-- comment standardization begin
ALTER TABLE fin_account_set
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'INITIALIZING' COMMENT '账套状态:INITIALIZING初始化中/READY已就绪/FAILED失败',
    MODIFY COLUMN enabled_year int NULL COMMENT '启用年度',
    MODIFY COLUMN enabled_period int NULL COMMENT '启用期间',
    MODIFY COLUMN template_code varchar(32) NULL COMMENT '模板编码',
    MODIFY COLUMN supervisor_user_id bigint NULL COMMENT '账套主管用户ID',
    MODIFY COLUMN create_mode varchar(16) NOT NULL DEFAULT 'BLANK' COMMENT '创建方式',
    MODIFY COLUMN reference_company_id varchar(64) NULL COMMENT '参照账套公司',
    MODIFY COLUMN subject_code_scheme varchar(32) NULL COMMENT '科目编码规则',
    MODIFY COLUMN subject_count int NOT NULL DEFAULT 0 COMMENT '科目数量',
    MODIFY COLUMN last_task_no varchar(32) NULL COMMENT '最近任务号',
    MODIFY COLUMN error_message varchar(500) NULL COMMENT '失败原因',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '财务账套主表';

ALTER TABLE fin_account_set_code_rule
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN rule_type varchar(32) NOT NULL COMMENT '规则类型',
    MODIFY COLUMN scheme varchar(32) NOT NULL COMMENT '规则表达式',
    MODIFY COLUMN level1_length int NOT NULL DEFAULT 4 COMMENT '一级科目长度',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套编码规则';

ALTER TABLE fin_account_set_template
    MODIFY COLUMN template_code varchar(32) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN template_name varchar(128) NOT NULL COMMENT '模板名称',
    MODIFY COLUMN accounting_standard varchar(128) NOT NULL COMMENT '制度口径',
    MODIFY COLUMN description varchar(500) NULL COMMENT '模板说明',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套模板主表';

ALTER TABLE fin_account_set_template_subject
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN template_code varchar(32) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN subject_key varchar(128) NOT NULL COMMENT '模板科目标识',
    MODIFY COLUMN parent_subject_key varchar(128) NULL COMMENT '父级模板科目标识',
    MODIFY COLUMN subject_level int NOT NULL COMMENT '科目层级',
    MODIFY COLUMN level_segment varchar(32) NOT NULL COMMENT '当前级编码段',
    MODIFY COLUMN subject_name varchar(128) NOT NULL COMMENT '科目名称',
    MODIFY COLUMN balance_direction varchar(16) NOT NULL COMMENT '余额方向',
    MODIFY COLUMN subject_category varchar(32) NOT NULL COMMENT '科目类别',
    MODIFY COLUMN cclassany varchar(32) NULL COMMENT '财务分析类型',
    MODIFY COLUMN bproperty tinyint NOT NULL DEFAULT 0 COMMENT '科目性质',
    MODIFY COLUMN cbook_type varchar(32) NULL COMMENT '账页格式',
    MODIFY COLUMN chelp varchar(128) NULL COMMENT '科目助记码',
    MODIFY COLUMN cexch_name varchar(32) NULL COMMENT '币种名称',
    MODIFY COLUMN cmeasure varchar(64) NULL COMMENT '计量单位',
    MODIFY COLUMN bperson tinyint NOT NULL DEFAULT 0 COMMENT '个人往来核算',
    MODIFY COLUMN bcus tinyint NOT NULL DEFAULT 0 COMMENT '客户往来核算',
    MODIFY COLUMN bsup tinyint NOT NULL DEFAULT 0 COMMENT '供应商往来核算',
    MODIFY COLUMN bdept tinyint NOT NULL DEFAULT 0 COMMENT '是否部门核算',
    MODIFY COLUMN bitem tinyint NOT NULL DEFAULT 0 COMMENT '是否项目核算',
    MODIFY COLUMN cass_item varchar(64) NULL COMMENT '项目大类编码',
    MODIFY COLUMN br tinyint NOT NULL DEFAULT 0 COMMENT '日记账',
    MODIFY COLUMN be tinyint NOT NULL DEFAULT 0 COMMENT '银行账',
    MODIFY COLUMN cgather varchar(16) NULL COMMENT '汇总打印',
    MODIFY COLUMN leaf_flag tinyint NOT NULL DEFAULT 1 COMMENT '是否末级',
    MODIFY COLUMN bexchange tinyint NOT NULL DEFAULT 0 COMMENT '是否参与汇兑损益计算',
    MODIFY COLUMN bcash tinyint NOT NULL DEFAULT 0 COMMENT '是否现金科目',
    MODIFY COLUMN bbank tinyint NOT NULL DEFAULT 0 COMMENT '是否银行科目',
    MODIFY COLUMN bused tinyint NOT NULL DEFAULT 0 COMMENT '银行科目启用',
    MODIFY COLUMN bd_c tinyint NOT NULL DEFAULT 0 COMMENT '银行对账方向',
    MODIFY COLUMN dbegin datetime NULL COMMENT '起始日期',
    MODIFY COLUMN dend datetime NULL COMMENT '截止日期',
    MODIFY COLUMN itrans tinyint NOT NULL DEFAULT 0 COMMENT '特殊科目标志',
    MODIFY COLUMN bclose tinyint NOT NULL DEFAULT 0 COMMENT '是否封存',
    MODIFY COLUMN cother varchar(64) NULL COMMENT '受控科目受控系统标识',
    MODIFY COLUMN iotherused int NOT NULL DEFAULT 0 COMMENT '其它系统是否使用',
    MODIFY COLUMN bReport tinyint NOT NULL DEFAULT 0 COMMENT '打印转账通知书',
    MODIFY COLUMN bGCJS tinyint NOT NULL DEFAULT 0 COMMENT '是否工程结算科目',
    MODIFY COLUMN bCashItem tinyint NOT NULL DEFAULT 0 COMMENT '是否常用现金流量科目',
    MODIFY COLUMN iViewItem int NOT NULL DEFAULT 0 COMMENT '在建工程项目科目类型',
    MODIFY COLUMN bcDefine1 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项1',
    MODIFY COLUMN bcDefine2 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项2',
    MODIFY COLUMN bcDefine3 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项3',
    MODIFY COLUMN bcDefine4 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项4',
    MODIFY COLUMN bcDefine5 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项5',
    MODIFY COLUMN bcDefine6 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项6',
    MODIFY COLUMN bcDefine7 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项7',
    MODIFY COLUMN bcDefine8 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项8',
    MODIFY COLUMN bcDefine9 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项9',
    MODIFY COLUMN bcDefine10 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项10',
    MODIFY COLUMN bcDefine11 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项11',
    MODIFY COLUMN bcDefine12 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项12',
    MODIFY COLUMN bcDefine13 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项13',
    MODIFY COLUMN bcDefine14 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项14',
    MODIFY COLUMN bcDefine15 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项15',
    MODIFY COLUMN bcDefine16 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项16',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套模板科目';

ALTER TABLE fin_account_subject
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN subject_code varchar(64) NOT NULL COMMENT '科目编码',
    MODIFY COLUMN subject_name varchar(128) NOT NULL COMMENT '科目名称',
    MODIFY COLUMN parent_subject_code varchar(64) NULL COMMENT '父级科目编码',
    MODIFY COLUMN subject_level int NOT NULL COMMENT '科目层级',
    MODIFY COLUMN balance_direction varchar(16) NOT NULL COMMENT '余额方向',
    MODIFY COLUMN subject_category varchar(32) NOT NULL COMMENT '科目类别',
    MODIFY COLUMN cclassany varchar(32) NULL COMMENT '财务分析类型',
    MODIFY COLUMN bproperty tinyint NOT NULL DEFAULT 0 COMMENT '科目性质',
    MODIFY COLUMN cbook_type varchar(32) NULL COMMENT '账页格式',
    MODIFY COLUMN chelp varchar(128) NULL COMMENT '科目助记码',
    MODIFY COLUMN cexch_name varchar(32) NULL COMMENT '币种名称',
    MODIFY COLUMN cmeasure varchar(64) NULL COMMENT '计量单位',
    MODIFY COLUMN bperson tinyint NOT NULL DEFAULT 0 COMMENT '个人往来核算',
    MODIFY COLUMN bcus tinyint NOT NULL DEFAULT 0 COMMENT '客户往来核算',
    MODIFY COLUMN bsup tinyint NOT NULL DEFAULT 0 COMMENT '供应商往来核算',
    MODIFY COLUMN bdept tinyint NOT NULL DEFAULT 0 COMMENT '是否部门核算',
    MODIFY COLUMN bitem tinyint NOT NULL DEFAULT 0 COMMENT '是否项目核算',
    MODIFY COLUMN cass_item varchar(64) NULL COMMENT '项目大类编码',
    MODIFY COLUMN br tinyint NOT NULL DEFAULT 0 COMMENT '日记账',
    MODIFY COLUMN be tinyint NOT NULL DEFAULT 0 COMMENT '银行账',
    MODIFY COLUMN cgather varchar(16) NULL COMMENT '汇总打印',
    MODIFY COLUMN leaf_flag tinyint NOT NULL DEFAULT 1 COMMENT '是否末级',
    MODIFY COLUMN bexchange tinyint NOT NULL DEFAULT 0 COMMENT '是否参与汇兑损益计算',
    MODIFY COLUMN bcash tinyint NOT NULL DEFAULT 0 COMMENT '是否现金科目',
    MODIFY COLUMN bbank tinyint NOT NULL DEFAULT 0 COMMENT '是否银行科目',
    MODIFY COLUMN bused tinyint NOT NULL DEFAULT 0 COMMENT '银行科目启用',
    MODIFY COLUMN bd_c tinyint NOT NULL DEFAULT 0 COMMENT '银行对账方向',
    MODIFY COLUMN dbegin datetime NULL COMMENT '起始日期',
    MODIFY COLUMN dend datetime NULL COMMENT '截止日期',
    MODIFY COLUMN itrans tinyint NOT NULL DEFAULT 0 COMMENT '特殊科目标志',
    MODIFY COLUMN bclose tinyint NOT NULL DEFAULT 0 COMMENT '是否封存',
    MODIFY COLUMN cother varchar(64) NULL COMMENT '受控科目受控系统标识',
    MODIFY COLUMN iotherused int NOT NULL DEFAULT 0 COMMENT '其它系统是否使用',
    MODIFY COLUMN bReport tinyint NOT NULL DEFAULT 0 COMMENT '打印转账通知书',
    MODIFY COLUMN bGCJS tinyint NOT NULL DEFAULT 0 COMMENT '是否工程结算科目',
    MODIFY COLUMN bCashItem tinyint NOT NULL DEFAULT 0 COMMENT '是否常用现金流量科目',
    MODIFY COLUMN iViewItem int NOT NULL DEFAULT 0 COMMENT '在建工程项目科目类型',
    MODIFY COLUMN bcDefine1 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项1',
    MODIFY COLUMN bcDefine2 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项2',
    MODIFY COLUMN bcDefine3 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项3',
    MODIFY COLUMN bcDefine4 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项4',
    MODIFY COLUMN bcDefine5 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项5',
    MODIFY COLUMN bcDefine6 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项6',
    MODIFY COLUMN bcDefine7 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项7',
    MODIFY COLUMN bcDefine8 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项8',
    MODIFY COLUMN bcDefine9 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项9',
    MODIFY COLUMN bcDefine10 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项10',
    MODIFY COLUMN bcDefine11 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项11',
    MODIFY COLUMN bcDefine12 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项12',
    MODIFY COLUMN bcDefine13 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项13',
    MODIFY COLUMN bcDefine14 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项14',
    MODIFY COLUMN bcDefine15 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项15',
    MODIFY COLUMN bcDefine16 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项16',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN template_code varchar(32) NULL COMMENT '来源模板编码',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套会计科目表';

-- comment standardization end
