USE finex_db;

SET NAMES utf8mb4;

ALTER TABLE ea_agent_credential_ref
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN owner_user_id bigint NOT NULL COMMENT '所属用户ID',
    MODIFY COLUMN credential_code varchar(64) NOT NULL COMMENT '凭据编码',
    MODIFY COLUMN provider_code varchar(64) NOT NULL COMMENT '提供方编码',
    MODIFY COLUMN credential_name varchar(100) NOT NULL COMMENT '凭据名称',
    MODIFY COLUMN masked_key varchar(128) NULL COMMENT '脱敏密钥',
    MODIFY COLUMN secret_payload text NULL COMMENT '敏感凭据载荷',
    MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态:ACTIVE启用/DISABLED停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理凭据引用表';

ALTER TABLE ea_agent_definition
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN agent_code varchar(32) NOT NULL COMMENT '代理编码',
    MODIFY COLUMN owner_user_id bigint NOT NULL COMMENT '所属用户ID',
    MODIFY COLUMN agent_name varchar(100) NOT NULL COMMENT '代理名称',
    MODIFY COLUMN agent_description varchar(500) NULL COMMENT '代理说明',
    MODIFY COLUMN icon_key varchar(64) NULL COMMENT '图标标识',
    MODIFY COLUMN theme_key varchar(64) NULL COMMENT '主题标识',
    MODIFY COLUMN cover_color varchar(32) NULL COMMENT '封面颜色',
    MODIFY COLUMN tags_json text NULL COMMENT '标签JSON',
    MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'DRAFT' COMMENT '状态:DRAFT草稿/PUBLISHED已发布/DISABLED停用',
    MODIFY COLUMN latest_version_no int NOT NULL DEFAULT 1 COMMENT '最新版本号',
    MODIFY COLUMN published_version_id bigint NULL COMMENT '已发布版本ID',
    MODIFY COLUMN last_run_id bigint NULL COMMENT '最近运行ID',
    MODIFY COLUMN last_run_status varchar(32) NULL COMMENT '最近运行状态',
    MODIFY COLUMN last_run_summary varchar(500) NULL COMMENT '最近运行摘要',
    MODIFY COLUMN last_run_at datetime NULL COMMENT '最近运行时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理定义表';

ALTER TABLE ea_agent_run
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN run_no varchar(40) NOT NULL COMMENT '运行编号',
    MODIFY COLUMN agent_id bigint NOT NULL COMMENT '代理ID',
    MODIFY COLUMN agent_version_id bigint NOT NULL COMMENT '代理版本ID',
    MODIFY COLUMN owner_user_id bigint NOT NULL COMMENT '所属用户ID',
    MODIFY COLUMN trigger_type varchar(32) NOT NULL COMMENT '触发类型',
    MODIFY COLUMN trigger_source varchar(64) NULL COMMENT '触发来源',
    MODIFY COLUMN status varchar(32) NOT NULL COMMENT '运行状态',
    MODIFY COLUMN error_message varchar(500) NULL COMMENT '错误信息',
    MODIFY COLUMN summary varchar(500) NULL COMMENT '摘要',
    MODIFY COLUMN input_json longtext NULL COMMENT '输入JSON',
    MODIFY COLUMN output_json longtext NULL COMMENT '输出JSON',
    MODIFY COLUMN scheduled_fire_at datetime NULL COMMENT '计划触发时间',
    MODIFY COLUMN started_at datetime NULL COMMENT '开始时间',
    MODIFY COLUMN finished_at datetime NULL COMMENT '结束时间',
    MODIFY COLUMN duration_ms bigint NULL COMMENT '耗时毫秒',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理运行记录表';

ALTER TABLE ea_agent_run_artifact
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN run_id bigint NOT NULL COMMENT '批次ID',
    MODIFY COLUMN artifact_key varchar(64) NOT NULL COMMENT '产物标识',
    MODIFY COLUMN artifact_type varchar(32) NOT NULL COMMENT '产物类型',
    MODIFY COLUMN artifact_name varchar(100) NULL COMMENT '产物名称',
    MODIFY COLUMN summary varchar(500) NULL COMMENT '摘要',
    MODIFY COLUMN content_json longtext NULL COMMENT '内容JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理运行产物表';

ALTER TABLE ea_agent_run_step
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN run_id bigint NOT NULL COMMENT '批次ID',
    MODIFY COLUMN step_no int NOT NULL COMMENT '步骤序号',
    MODIFY COLUMN node_key varchar(64) NOT NULL COMMENT '节点标识',
    MODIFY COLUMN node_type varchar(32) NOT NULL COMMENT '节点类型',
    MODIFY COLUMN node_label varchar(100) NULL COMMENT '节点标签',
    MODIFY COLUMN status varchar(32) NOT NULL COMMENT '步骤状态',
    MODIFY COLUMN error_message varchar(500) NULL COMMENT '错误信息',
    MODIFY COLUMN input_json longtext NULL COMMENT '输入JSON',
    MODIFY COLUMN output_json longtext NULL COMMENT '输出JSON',
    MODIFY COLUMN started_at datetime NULL COMMENT '开始时间',
    MODIFY COLUMN finished_at datetime NULL COMMENT '结束时间',
    MODIFY COLUMN duration_ms bigint NULL COMMENT '耗时毫秒',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理运行步骤表';

ALTER TABLE ea_agent_schedule
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN trigger_id bigint NOT NULL COMMENT '触发器ID',
    MODIFY COLUMN agent_id bigint NOT NULL COMMENT '代理ID',
    MODIFY COLUMN schedule_status varchar(32) NOT NULL DEFAULT 'IDLE' COMMENT '调度状态',
    MODIFY COLUMN last_fire_at datetime NULL COMMENT '上次触发时间',
    MODIFY COLUMN next_fire_at datetime NULL COMMENT '下次触发时间',
    MODIFY COLUMN last_run_id bigint NULL COMMENT '最近运行ID',
    MODIFY COLUMN locked_at datetime NULL COMMENT '锁定时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理调度表';

ALTER TABLE ea_agent_tool_binding
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN agent_id bigint NOT NULL COMMENT '代理ID',
    MODIFY COLUMN tool_code varchar(64) NOT NULL COMMENT '工具编码',
    MODIFY COLUMN enabled int NOT NULL DEFAULT 1 COMMENT '是否启用:1是 0否',
    MODIFY COLUMN credential_ref_code varchar(64) NULL COMMENT '凭据引用编码',
    MODIFY COLUMN config_json text NULL COMMENT '工具绑定配置JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理工具绑定表';

ALTER TABLE ea_agent_trigger
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN agent_id bigint NOT NULL COMMENT '代理ID',
    MODIFY COLUMN trigger_type varchar(32) NOT NULL COMMENT '触发类型',
    MODIFY COLUMN enabled int NOT NULL DEFAULT 1 COMMENT '是否启用:1是 0否',
    MODIFY COLUMN schedule_mode varchar(32) NULL COMMENT '调度模式',
    MODIFY COLUMN cron_expression varchar(64) NULL COMMENT 'Cron表达式',
    MODIFY COLUMN interval_minutes int NULL COMMENT '间隔分钟数',
    MODIFY COLUMN event_code varchar(64) NULL COMMENT '事件编码',
    MODIFY COLUMN config_json text NULL COMMENT '触发配置JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '档案代理触发器表';

ALTER TABLE ea_agent_version
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN agent_id bigint NOT NULL COMMENT '代理ID',
    MODIFY COLUMN version_no int NOT NULL COMMENT '版本号',
    MODIFY COLUMN version_label varchar(64) NULL COMMENT '版本标签',
    MODIFY COLUMN config_json longtext NOT NULL COMMENT '配置JSON',
    MODIFY COLUMN published int NOT NULL DEFAULT 0 COMMENT '是否已发布:1是 0否',
    MODIFY COLUMN created_by_user_id bigint NOT NULL COMMENT '创建人用户ID',
    MODIFY COLUMN created_by_name varchar(100) NULL COMMENT '创建人姓名',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    COMMENT = '档案代理版本表';

ALTER TABLE exp_voucher_push_batch
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN batch_no varchar(64) NOT NULL COMMENT '批次号',
    MODIFY COLUMN document_count int NOT NULL DEFAULT 0 COMMENT '单据数量',
    MODIFY COLUMN success_count int NOT NULL DEFAULT 0 COMMENT '成功数量',
    MODIFY COLUMN failure_count int NOT NULL DEFAULT 0 COMMENT '失败数量',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '推送状态',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '报销单推凭证批次表';

ALTER TABLE exp_voucher_push_document
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN batch_id bigint NULL COMMENT '批次ID',
    MODIFY COLUMN batch_no varchar(64) NULL COMMENT '批次号',
    MODIFY COLUMN document_code varchar(64) NOT NULL COMMENT '单据编码',
    MODIFY COLUMN template_code varchar(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN template_name varchar(128) NULL COMMENT '模板名称',
    MODIFY COLUMN submitter_user_id bigint NULL COMMENT '提单人用户ID',
    MODIFY COLUMN submitter_name varchar(128) NULL COMMENT '提单人姓名',
    MODIFY COLUMN total_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '总金额',
    MODIFY COLUMN push_status varchar(16) NOT NULL COMMENT '推送状态',
    MODIFY COLUMN voucher_no varchar(128) NULL COMMENT '凭证号',
    MODIFY COLUMN voucher_type varchar(16) NULL COMMENT '凭证类别字',
    MODIFY COLUMN voucher_number int NULL COMMENT '凭证编号',
    MODIFY COLUMN fiscal_period int NULL COMMENT '会计期间',
    MODIFY COLUMN bill_date date NULL COMMENT '单据日期',
    MODIFY COLUMN error_message varchar(500) NULL COMMENT '错误信息',
    MODIFY COLUMN pushed_at datetime NULL COMMENT '推送时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '报销单推凭证结果表';

ALTER TABLE exp_voucher_push_entry
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN push_document_id bigint NOT NULL COMMENT '推凭证单据ID',
    MODIFY COLUMN entry_no int NOT NULL COMMENT '分录序号',
    MODIFY COLUMN direction varchar(16) NOT NULL COMMENT '方向',
    MODIFY COLUMN digest varchar(255) NULL COMMENT '摘要',
    MODIFY COLUMN account_code varchar(64) NOT NULL COMMENT '科目编码',
    MODIFY COLUMN account_name varchar(128) NULL COMMENT '科目名称',
    MODIFY COLUMN expense_type_code varchar(64) NULL COMMENT '费用类型编码',
    MODIFY COLUMN expense_type_name varchar(128) NULL COMMENT '费用类型名称',
    MODIFY COLUMN amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '金额',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '报销单推凭证明细表';

ALTER TABLE exp_voucher_subject_mapping
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN template_code varchar(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN template_name varchar(128) NULL COMMENT '模板名称',
    MODIFY COLUMN expense_type_code varchar(64) NOT NULL COMMENT '费用类型编码',
    MODIFY COLUMN expense_type_name varchar(128) NULL COMMENT '费用类型名称',
    MODIFY COLUMN debit_account_code varchar(64) NOT NULL COMMENT '借方科目编码',
    MODIFY COLUMN debit_account_name varchar(128) NULL COMMENT '借方科目名称',
    MODIFY COLUMN enabled tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用:1是 0否',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN updated_by varchar(64) NULL COMMENT '更新人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '报销凭证科目映射表';

ALTER TABLE exp_voucher_template_policy
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN template_code varchar(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN template_name varchar(128) NULL COMMENT '模板名称',
    MODIFY COLUMN credit_account_code varchar(64) NOT NULL COMMENT '贷方科目编码',
    MODIFY COLUMN credit_account_name varchar(128) NULL COMMENT '贷方科目名称',
    MODIFY COLUMN voucher_type varchar(16) NOT NULL DEFAULT '记' COMMENT '凭证类别字',
    MODIFY COLUMN summary_rule varchar(255) NULL COMMENT '摘要生成规则',
    MODIFY COLUMN enabled tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用:1是 0否',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN updated_by varchar(64) NULL COMMENT '更新人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '报销凭证模板策略表';

ALTER TABLE fa_asset_account_policy
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN category_id bigint NOT NULL COMMENT '分类ID',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN asset_account varchar(64) NOT NULL COMMENT '资产科目编码',
    MODIFY COLUMN accum_depr_account varchar(64) NOT NULL COMMENT '累计折旧科目编码',
    MODIFY COLUMN depr_expense_account varchar(64) NOT NULL COMMENT '折旧费用科目编码',
    MODIFY COLUMN disposal_account varchar(64) NOT NULL COMMENT '处置清理科目编码',
    MODIFY COLUMN gain_account varchar(64) NOT NULL COMMENT '处置收益科目编码',
    MODIFY COLUMN loss_account varchar(64) NOT NULL COMMENT '处置损失科目编码',
    MODIFY COLUMN offset_account varchar(64) NOT NULL COMMENT '对冲科目编码',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产科目策略表';

ALTER TABLE fa_asset_card
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN asset_code varchar(64) NOT NULL COMMENT '资产编码',
    MODIFY COLUMN asset_name varchar(128) NOT NULL COMMENT '资产名称',
    MODIFY COLUMN category_id bigint NOT NULL COMMENT '分类ID',
    MODIFY COLUMN category_code varchar(64) NOT NULL COMMENT '分类编码',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN use_company_id varchar(64) NOT NULL COMMENT '使用公司主体编码',
    MODIFY COLUMN use_dept_id bigint NULL COMMENT '使用部门ID',
    MODIFY COLUMN keeper_user_id bigint NULL COMMENT '保管人用户ID',
    MODIFY COLUMN manager_user_id bigint NULL COMMENT '管理人用户ID',
    MODIFY COLUMN source_type varchar(16) NOT NULL DEFAULT 'MANUAL' COMMENT '来源类型',
    MODIFY COLUMN acquire_date date NULL COMMENT '取得日期',
    MODIFY COLUMN in_service_date date NOT NULL COMMENT '投入使用日期',
    MODIFY COLUMN original_amount decimal(18,2) NOT NULL COMMENT '原值金额',
    MODIFY COLUMN accum_depr_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '累计折旧金额',
    MODIFY COLUMN salvage_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '残值金额',
    MODIFY COLUMN net_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '净值金额',
    MODIFY COLUMN useful_life_months int NOT NULL COMMENT '使用寿命月数',
    MODIFY COLUMN depreciated_months int NOT NULL DEFAULT 0 COMMENT '已折旧月数',
    MODIFY COLUMN remaining_months int NOT NULL DEFAULT 0 COMMENT '剩余月数',
    MODIFY COLUMN work_total decimal(18,6) NULL COMMENT '工作总量',
    MODIFY COLUMN work_used decimal(18,6) NULL COMMENT '已使用工作量',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '资产状态',
    MODIFY COLUMN can_depreciate tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否允许折旧:1是 0否',
    MODIFY COLUMN last_depr_year int NULL COMMENT '最近折旧年度',
    MODIFY COLUMN last_depr_period int NULL COMMENT '最近折旧期间',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN updated_by varchar(64) NULL COMMENT '更新人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产卡片表';

ALTER TABLE fa_asset_category
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN category_code varchar(64) NOT NULL COMMENT '分类编码',
    MODIFY COLUMN category_name varchar(128) NOT NULL COMMENT '分类名称',
    MODIFY COLUMN share_scope varchar(16) NOT NULL DEFAULT 'COMPANY' COMMENT '共享范围:GLOBAL全局/COMPANY公司',
    MODIFY COLUMN depreciation_method varchar(32) NOT NULL COMMENT '折旧方法',
    MODIFY COLUMN useful_life_months int NOT NULL COMMENT '使用寿命月数',
    MODIFY COLUMN residual_rate decimal(10,4) NOT NULL DEFAULT 0.0500 COMMENT '净残值率',
    MODIFY COLUMN depreciable tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否计提折旧:1是 0否',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN updated_by varchar(64) NULL COMMENT '更新人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产分类表';

ALTER TABLE fa_asset_change_bill
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN bill_no varchar(64) NOT NULL COMMENT '单据编号',
    MODIFY COLUMN bill_type varchar(32) NOT NULL COMMENT '单据类型',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN fiscal_year int NOT NULL COMMENT '会计年度',
    MODIFY COLUMN fiscal_period int NOT NULL COMMENT '会计期间',
    MODIFY COLUMN bill_date date NOT NULL COMMENT '单据日期',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '单据状态',
    MODIFY COLUMN total_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '总金额',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN posted_by varchar(64) NULL COMMENT '过账人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN posted_at datetime NULL COMMENT '过账时间',
    COMMENT = '固定资产变动单据表';

ALTER TABLE fa_asset_change_line
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN bill_id bigint NOT NULL COMMENT '单据ID',
    MODIFY COLUMN asset_id bigint NULL COMMENT '资产ID',
    MODIFY COLUMN asset_code varchar(64) NOT NULL COMMENT '资产编码',
    MODIFY COLUMN asset_name varchar(128) NULL COMMENT '资产名称',
    MODIFY COLUMN change_type varchar(32) NOT NULL COMMENT '变动类型',
    MODIFY COLUMN category_id bigint NULL COMMENT '分类ID',
    MODIFY COLUMN category_code varchar(64) NULL COMMENT '分类编码',
    MODIFY COLUMN use_company_id varchar(64) NULL COMMENT '使用公司主体编码',
    MODIFY COLUMN use_dept_id bigint NULL COMMENT '使用部门ID',
    MODIFY COLUMN keeper_user_id bigint NULL COMMENT '保管人用户ID',
    MODIFY COLUMN in_service_date date NULL COMMENT '投入使用日期',
    MODIFY COLUMN change_amount decimal(18,2) NULL COMMENT '变动金额',
    MODIFY COLUMN old_value decimal(18,2) NULL COMMENT '变动前值',
    MODIFY COLUMN new_value decimal(18,2) NULL COMMENT '变动后值',
    MODIFY COLUMN old_salvage_amount decimal(18,2) NULL COMMENT '变动前残值金额',
    MODIFY COLUMN new_salvage_amount decimal(18,2) NULL COMMENT '变动后残值金额',
    MODIFY COLUMN old_useful_life_months int NULL COMMENT '变动前使用寿命月数',
    MODIFY COLUMN new_useful_life_months int NULL COMMENT '变动后使用寿命月数',
    MODIFY COLUMN old_remaining_months int NULL COMMENT '变动前剩余月数',
    MODIFY COLUMN new_remaining_months int NULL COMMENT '变动后剩余月数',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产变动明细表';

ALTER TABLE fa_asset_depr_line
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN run_id bigint NOT NULL COMMENT '批次ID',
    MODIFY COLUMN asset_id bigint NOT NULL COMMENT '资产ID',
    MODIFY COLUMN asset_code varchar(64) NOT NULL COMMENT '资产编码',
    MODIFY COLUMN asset_name varchar(128) NOT NULL COMMENT '资产名称',
    MODIFY COLUMN category_id bigint NOT NULL COMMENT '分类ID',
    MODIFY COLUMN depreciation_method varchar(32) NOT NULL COMMENT '折旧方法',
    MODIFY COLUMN work_amount decimal(18,6) NULL COMMENT '本次工作量',
    MODIFY COLUMN depreciation_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '本次折旧金额',
    MODIFY COLUMN before_accum_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '折旧前累计折旧金额',
    MODIFY COLUMN after_accum_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '折旧后累计折旧金额',
    MODIFY COLUMN before_net_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '折旧前净值金额',
    MODIFY COLUMN after_net_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '折旧后净值金额',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产折旧计提明细表';

ALTER TABLE fa_asset_depr_run
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN run_no varchar(64) NOT NULL COMMENT '运行编号',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN fiscal_year int NOT NULL COMMENT '会计年度',
    MODIFY COLUMN fiscal_period int NOT NULL COMMENT '会计期间',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '批次状态',
    MODIFY COLUMN asset_count int NOT NULL DEFAULT 0 COMMENT '资产数量',
    MODIFY COLUMN total_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '总金额',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN posted_by varchar(64) NULL COMMENT '过账人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN posted_at datetime NULL COMMENT '过账时间',
    COMMENT = '固定资产折旧计提批次表';

ALTER TABLE fa_asset_disposal_bill
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN bill_no varchar(64) NOT NULL COMMENT '单据编号',
    MODIFY COLUMN bill_type varchar(32) NOT NULL DEFAULT 'DISPOSAL' COMMENT '单据类型',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN fiscal_year int NOT NULL COMMENT '会计年度',
    MODIFY COLUMN fiscal_period int NOT NULL COMMENT '会计期间',
    MODIFY COLUMN bill_date date NOT NULL COMMENT '单据日期',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '单据状态',
    MODIFY COLUMN total_original_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '原值合计金额',
    MODIFY COLUMN total_accum_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '累计折旧合计金额',
    MODIFY COLUMN total_net_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '净值合计金额',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN posted_by varchar(64) NULL COMMENT '过账人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN posted_at datetime NULL COMMENT '过账时间',
    COMMENT = '固定资产处置单据表';

ALTER TABLE fa_asset_disposal_line
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN bill_id bigint NOT NULL COMMENT '单据ID',
    MODIFY COLUMN asset_id bigint NOT NULL COMMENT '资产ID',
    MODIFY COLUMN asset_code varchar(64) NOT NULL COMMENT '资产编码',
    MODIFY COLUMN asset_name varchar(128) NOT NULL COMMENT '资产名称',
    MODIFY COLUMN category_id bigint NOT NULL COMMENT '分类ID',
    MODIFY COLUMN original_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '原值金额',
    MODIFY COLUMN accum_depr_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '累计折旧金额',
    MODIFY COLUMN net_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '净值金额',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产处置明细表';

ALTER TABLE fa_asset_opening_import
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN batch_no varchar(64) NOT NULL COMMENT '批次号',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN fiscal_year int NOT NULL COMMENT '会计年度',
    MODIFY COLUMN fiscal_period int NOT NULL COMMENT '会计期间',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '导入状态',
    MODIFY COLUMN total_rows int NOT NULL DEFAULT 0 COMMENT '总行数',
    MODIFY COLUMN success_rows int NOT NULL DEFAULT 0 COMMENT '成功行数',
    MODIFY COLUMN failed_rows int NOT NULL DEFAULT 0 COMMENT '失败行数',
    MODIFY COLUMN created_by varchar(64) NULL COMMENT '创建人',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产期初导入批次表';

ALTER TABLE fa_asset_opening_import_line
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN batch_id bigint NOT NULL COMMENT '批次ID',
    MODIFY COLUMN row_no int NOT NULL COMMENT '行号',
    MODIFY COLUMN asset_code varchar(64) NULL COMMENT '资产编码',
    MODIFY COLUMN asset_name varchar(128) NULL COMMENT '资产名称',
    MODIFY COLUMN category_code varchar(64) NULL COMMENT '分类编码',
    MODIFY COLUMN result_status varchar(16) NOT NULL COMMENT '处理结果状态',
    MODIFY COLUMN error_message varchar(500) NULL COMMENT '错误信息',
    MODIFY COLUMN imported_asset_id bigint NULL COMMENT '导入资产ID',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产期初导入明细表';

ALTER TABLE fa_asset_period_close
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN book_code varchar(32) NOT NULL DEFAULT 'FINANCE' COMMENT '账簿编码',
    MODIFY COLUMN fiscal_year int NOT NULL COMMENT '会计年度',
    MODIFY COLUMN fiscal_period int NOT NULL COMMENT '会计期间',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'CLOSED' COMMENT '关账状态',
    MODIFY COLUMN closed_by varchar(64) NULL COMMENT '关账人',
    MODIFY COLUMN closed_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '关账时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产期间关账表';

ALTER TABLE fa_asset_voucher_link
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN business_type varchar(32) NOT NULL COMMENT '业务类型',
    MODIFY COLUMN business_id bigint NOT NULL COMMENT '业务ID',
    MODIFY COLUMN voucher_no varchar(128) NOT NULL COMMENT '凭证号',
    MODIFY COLUMN iperiod int NOT NULL COMMENT '会计期间',
    MODIFY COLUMN csign varchar(32) NOT NULL COMMENT '凭证类别字',
    MODIFY COLUMN ino_id int NOT NULL COMMENT '凭证编号',
    MODIFY COLUMN remark varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '固定资产凭证关联表';

ALTER TABLE fin_account_set
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN status varchar(16) NOT NULL DEFAULT 'INITIALIZING' COMMENT '账套状态:INITIALIZING初始化中/READY已就绪/FAILED失败',
    MODIFY COLUMN enabled_year int NULL COMMENT '启用年度',
    MODIFY COLUMN enabled_period int NULL COMMENT '启用期间',
    MODIFY COLUMN template_code varchar(64) NULL COMMENT '模板编码',
    MODIFY COLUMN supervisor_user_id bigint NULL COMMENT '账套主管用户ID',
    MODIFY COLUMN create_mode varchar(16) NOT NULL DEFAULT 'BLANK' COMMENT '创建方式',
    MODIFY COLUMN reference_company_id varchar(64) NULL COMMENT '参照账套公司',
    MODIFY COLUMN subject_code_scheme varchar(64) NULL COMMENT '科目编码规则',
    MODIFY COLUMN subject_count int NOT NULL DEFAULT 0 COMMENT '科目数量',
    MODIFY COLUMN last_task_no varchar(64) NULL COMMENT '鏈€杩戜换鍔″彿',
    MODIFY COLUMN error_message varchar(500) NULL COMMENT '失败原因',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '财务账套主表';

ALTER TABLE fin_account_set_code_rule
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN rule_type varchar(64) NOT NULL COMMENT '规则类型',
    MODIFY COLUMN scheme varchar(64) NOT NULL COMMENT '规则表达式',
    MODIFY COLUMN level1_length int NOT NULL DEFAULT 4 COMMENT '一级科目长度',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套编码规则';

ALTER TABLE fin_account_set_template
    MODIFY COLUMN template_code varchar(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN template_name varchar(128) NOT NULL COMMENT '模板名称',
    MODIFY COLUMN accounting_standard varchar(128) NOT NULL COMMENT '制度口径',
    MODIFY COLUMN description varchar(500) NULL COMMENT '模板说明',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套模板主表';

ALTER TABLE fin_account_set_template_subject
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN template_code varchar(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN subject_key varchar(128) NOT NULL COMMENT '模板科目标识',
    MODIFY COLUMN parent_subject_key varchar(128) NULL COMMENT '父级模板科目标识',
    MODIFY COLUMN subject_level int NOT NULL COMMENT '科目层级',
    MODIFY COLUMN level_segment varchar(32) NOT NULL COMMENT '当前级编码段',
    MODIFY COLUMN subject_name varchar(128) NOT NULL COMMENT '科目名称',
    MODIFY COLUMN balance_direction varchar(16) NOT NULL COMMENT '余额方向',
    MODIFY COLUMN subject_category varchar(32) NOT NULL COMMENT '科目类别',
    MODIFY COLUMN cclassany varchar(32) NULL COMMENT '财务分析类型',
    MODIFY COLUMN bproperty tinyint NOT NULL DEFAULT 0 COMMENT '科目性质',
    MODIFY COLUMN cbook_type varchar(32) NULL COMMENT '账页格式',
    MODIFY COLUMN chelp varchar(128) NULL COMMENT '科目助记码',
    MODIFY COLUMN cexch_name varchar(32) NULL COMMENT '币种名称',
    MODIFY COLUMN cmeasure varchar(64) NULL COMMENT '计量单位',
    MODIFY COLUMN bperson tinyint NOT NULL DEFAULT 0 COMMENT '个人往来核算',
    MODIFY COLUMN bcus tinyint NOT NULL DEFAULT 0 COMMENT '客户往来核算',
    MODIFY COLUMN bsup tinyint NOT NULL DEFAULT 0 COMMENT '供应商往来核算',
    MODIFY COLUMN bdept tinyint NOT NULL DEFAULT 0 COMMENT '是否部门核算',
    MODIFY COLUMN bitem tinyint NOT NULL DEFAULT 0 COMMENT '是否项目核算',
    MODIFY COLUMN cass_item varchar(64) NULL COMMENT '项目大类编码',
    MODIFY COLUMN br tinyint NOT NULL DEFAULT 0 COMMENT '日记账',
    MODIFY COLUMN be tinyint NOT NULL DEFAULT 0 COMMENT '银行账',
    MODIFY COLUMN cgather varchar(16) NULL COMMENT '汇总打印',
    MODIFY COLUMN leaf_flag tinyint NOT NULL DEFAULT 1 COMMENT '是否末级',
    MODIFY COLUMN bexchange tinyint NOT NULL DEFAULT 0 COMMENT '是否参与汇兑损益计算',
    MODIFY COLUMN bcash tinyint NOT NULL DEFAULT 0 COMMENT '是否现金科目',
    MODIFY COLUMN bbank tinyint NOT NULL DEFAULT 0 COMMENT '是否银行科目',
    MODIFY COLUMN bused tinyint NOT NULL DEFAULT 0 COMMENT '银行科目启用',
    MODIFY COLUMN bd_c tinyint NOT NULL DEFAULT 0 COMMENT '银行对账方向',
    MODIFY COLUMN dbegin datetime NULL COMMENT '起始日期',
    MODIFY COLUMN dend datetime NULL COMMENT '截止日期',
    MODIFY COLUMN itrans tinyint NOT NULL DEFAULT 0 COMMENT '特殊科目标志',
    MODIFY COLUMN bclose tinyint NOT NULL DEFAULT 0 COMMENT '是否封存',
    MODIFY COLUMN cother varchar(64) NULL COMMENT '受控科目受控系统标识',
    MODIFY COLUMN iotherused int NOT NULL DEFAULT 0 COMMENT '其它系统是否使用',
    MODIFY COLUMN bReport tinyint NOT NULL DEFAULT 0 COMMENT '打印转账通知书',
    MODIFY COLUMN bGCJS tinyint NOT NULL DEFAULT 0 COMMENT '是否工程结算科目',
    MODIFY COLUMN bCashItem tinyint NOT NULL DEFAULT 0 COMMENT '是否常用现金流量科目',
    MODIFY COLUMN iViewItem int NOT NULL DEFAULT 0 COMMENT '在建工程项目科目类型',
    MODIFY COLUMN bcDefine1 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项1',
    MODIFY COLUMN bcDefine2 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项2',
    MODIFY COLUMN bcDefine3 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项3',
    MODIFY COLUMN bcDefine4 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项4',
    MODIFY COLUMN bcDefine5 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项5',
    MODIFY COLUMN bcDefine6 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项6',
    MODIFY COLUMN bcDefine7 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项7',
    MODIFY COLUMN bcDefine8 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项8',
    MODIFY COLUMN bcDefine9 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项9',
    MODIFY COLUMN bcDefine10 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项10',
    MODIFY COLUMN bcDefine11 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项11',
    MODIFY COLUMN bcDefine12 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项12',
    MODIFY COLUMN bcDefine13 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项13',
    MODIFY COLUMN bcDefine14 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项14',
    MODIFY COLUMN bcDefine15 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项15',
    MODIFY COLUMN bcDefine16 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项16',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套模板科目';

ALTER TABLE fin_account_subject
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
    MODIFY COLUMN company_id varchar(64) NOT NULL COMMENT '公司主体编码',
    MODIFY COLUMN subject_code varchar(64) NOT NULL COMMENT '科目编码',
    MODIFY COLUMN subject_name varchar(128) NOT NULL COMMENT '科目名称',
    MODIFY COLUMN parent_subject_code varchar(64) NULL COMMENT '父级科目编码',
    MODIFY COLUMN subject_level int NOT NULL COMMENT '科目层级',
    MODIFY COLUMN balance_direction varchar(16) NOT NULL COMMENT '余额方向',
    MODIFY COLUMN subject_category varchar(32) NOT NULL COMMENT '科目类别',
    MODIFY COLUMN cclassany varchar(32) NULL COMMENT '财务分析类型',
    MODIFY COLUMN bproperty tinyint NOT NULL DEFAULT 0 COMMENT '科目性质',
    MODIFY COLUMN cbook_type varchar(32) NULL COMMENT '账页格式',
    MODIFY COLUMN chelp varchar(128) NULL COMMENT '科目助记码',
    MODIFY COLUMN cexch_name varchar(32) NULL COMMENT '币种名称',
    MODIFY COLUMN cmeasure varchar(64) NULL COMMENT '计量单位',
    MODIFY COLUMN bperson tinyint NOT NULL DEFAULT 0 COMMENT '个人往来核算',
    MODIFY COLUMN bcus tinyint NOT NULL DEFAULT 0 COMMENT '客户往来核算',
    MODIFY COLUMN bsup tinyint NOT NULL DEFAULT 0 COMMENT '供应商往来核算',
    MODIFY COLUMN bdept tinyint NOT NULL DEFAULT 0 COMMENT '是否部门核算',
    MODIFY COLUMN bitem tinyint NOT NULL DEFAULT 0 COMMENT '是否项目核算',
    MODIFY COLUMN cass_item varchar(64) NULL COMMENT '项目大类编码',
    MODIFY COLUMN br tinyint NOT NULL DEFAULT 0 COMMENT '日记账',
    MODIFY COLUMN be tinyint NOT NULL DEFAULT 0 COMMENT '银行账',
    MODIFY COLUMN cgather varchar(16) NULL COMMENT '汇总打印',
    MODIFY COLUMN leaf_flag tinyint NOT NULL DEFAULT 1 COMMENT '是否末级',
    MODIFY COLUMN bexchange tinyint NOT NULL DEFAULT 0 COMMENT '是否参与汇兑损益计算',
    MODIFY COLUMN bcash tinyint NOT NULL DEFAULT 0 COMMENT '是否现金科目',
    MODIFY COLUMN bbank tinyint NOT NULL DEFAULT 0 COMMENT '是否银行科目',
    MODIFY COLUMN bused tinyint NOT NULL DEFAULT 0 COMMENT '银行科目启用',
    MODIFY COLUMN bd_c tinyint NOT NULL DEFAULT 0 COMMENT '银行对账方向',
    MODIFY COLUMN dbegin datetime NULL COMMENT '起始日期',
    MODIFY COLUMN dend datetime NULL COMMENT '截止日期',
    MODIFY COLUMN itrans tinyint NOT NULL DEFAULT 0 COMMENT '特殊科目标志',
    MODIFY COLUMN bclose tinyint NOT NULL DEFAULT 0 COMMENT '是否封存',
    MODIFY COLUMN cother varchar(64) NULL COMMENT '受控科目受控系统标识',
    MODIFY COLUMN iotherused int NOT NULL DEFAULT 0 COMMENT '其它系统是否使用',
    MODIFY COLUMN bReport tinyint NOT NULL DEFAULT 0 COMMENT '打印转账通知书',
    MODIFY COLUMN bGCJS tinyint NOT NULL DEFAULT 0 COMMENT '是否工程结算科目',
    MODIFY COLUMN bCashItem tinyint NOT NULL DEFAULT 0 COMMENT '是否常用现金流量科目',
    MODIFY COLUMN iViewItem int NOT NULL DEFAULT 0 COMMENT '在建工程项目科目类型',
    MODIFY COLUMN bcDefine1 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项1',
    MODIFY COLUMN bcDefine2 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项2',
    MODIFY COLUMN bcDefine3 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项3',
    MODIFY COLUMN bcDefine4 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项4',
    MODIFY COLUMN bcDefine5 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项5',
    MODIFY COLUMN bcDefine6 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项6',
    MODIFY COLUMN bcDefine7 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项7',
    MODIFY COLUMN bcDefine8 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项8',
    MODIFY COLUMN bcDefine9 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项9',
    MODIFY COLUMN bcDefine10 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项10',
    MODIFY COLUMN bcDefine11 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项11',
    MODIFY COLUMN bcDefine12 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项12',
    MODIFY COLUMN bcDefine13 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项13',
    MODIFY COLUMN bcDefine14 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项14',
    MODIFY COLUMN bcDefine15 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项15',
    MODIFY COLUMN bcDefine16 tinyint NOT NULL DEFAULT 0 COMMENT '科目自定义项16',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN template_code varchar(64) NULL COMMENT '来源模板编码',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '账套会计科目表';

ALTER TABLE gl_customer
    MODIFY COLUMN cCusCode varchar(255) NOT NULL COMMENT '客户编码',
    MODIFY COLUMN cCusName varchar(255) NOT NULL COMMENT '客户名称',
    MODIFY COLUMN cCusAbbName varchar(255) NULL COMMENT '客户简称',
    MODIFY COLUMN cCCCode varchar(255) NULL COMMENT '客户分类编码',
    MODIFY COLUMN cDCCode varchar(255) NULL COMMENT '地区编码',
    MODIFY COLUMN cCusTradeCCode varchar(255) NULL COMMENT '行业编码',
    MODIFY COLUMN cTrade varchar(255) NULL COMMENT '所属行业',
    MODIFY COLUMN cCusAddress varchar(255) NULL COMMENT '地址',
    MODIFY COLUMN cCusPostCode varchar(255) NULL COMMENT '邮政编码',
    MODIFY COLUMN cCusRegCode varchar(255) NULL COMMENT '纳税人登记号',
    MODIFY COLUMN cCusBank varchar(255) NULL COMMENT '开户银行',
    MODIFY COLUMN cCusAccount varchar(255) NULL COMMENT '银行账号',
    MODIFY COLUMN cCusLPerson varchar(255) NULL COMMENT '法人',
    MODIFY COLUMN cCusPerson varchar(255) NULL COMMENT '联系人',
    MODIFY COLUMN cCusHand varchar(255) NULL COMMENT '手机',
    MODIFY COLUMN cCusCreGrade varchar(255) NULL COMMENT '信用等级',
    MODIFY COLUMN iCusCreLine decimal(18,2) NULL COMMENT '信用额度',
    MODIFY COLUMN iCusCreDate int NULL COMMENT '信用期限',
    MODIFY COLUMN cCusOAddress varchar(255) NULL COMMENT '发货地址',
    MODIFY COLUMN cCusOType varchar(255) NULL COMMENT '发运方式',
    MODIFY COLUMN cCusHeadCode varchar(255) NULL COMMENT '客户总公司编码',
    MODIFY COLUMN cCusWhCode varchar(255) NULL COMMENT '发货仓库',
    MODIFY COLUMN cCusDepart varchar(255) NULL COMMENT '分管部门',
    MODIFY COLUMN iARMoney decimal(18,2) NULL COMMENT '应收余额',
    MODIFY COLUMN dLastDate datetime NULL COMMENT '最后交易日期',
    MODIFY COLUMN iLastMoney decimal(18,2) NULL COMMENT '最后交易金额',
    MODIFY COLUMN dLRDate datetime NULL COMMENT '最后收款日期',
    MODIFY COLUMN iLRMoney decimal(18,2) NULL COMMENT '最后收款金额',
    MODIFY COLUMN dEndDate datetime NULL COMMENT '停用日期',
    MODIFY COLUMN cCusBankCode varchar(255) NULL COMMENT '所属银行编码',
    MODIFY COLUMN cCusDefine1 varchar(255) NULL COMMENT '客户自定义项1',
    MODIFY COLUMN cCusDefine2 varchar(255) NULL COMMENT '客户自定义项2',
    MODIFY COLUMN cCusDefine3 varchar(255) NULL COMMENT '客户自定义项3',
    MODIFY COLUMN cCusDefine4 varchar(255) NULL COMMENT '客户自定义项4',
    MODIFY COLUMN cCusDefine5 varchar(255) NULL COMMENT '客户自定义项5',
    MODIFY COLUMN cCusDefine6 varchar(255) NULL COMMENT '客户自定义项6',
    MODIFY COLUMN cCusDefine7 varchar(255) NULL COMMENT '客户自定义项7',
    MODIFY COLUMN cCusDefine8 varchar(255) NULL COMMENT '客户自定义项8',
    MODIFY COLUMN cCusDefine9 varchar(255) NULL COMMENT '客户自定义项9',
    MODIFY COLUMN cCusDefine10 varchar(255) NULL COMMENT '客户自定义项10',
    MODIFY COLUMN cCusDefine11 int NULL COMMENT '客户自定义项11',
    MODIFY COLUMN cCusDefine12 int NULL COMMENT '客户自定义项12',
    MODIFY COLUMN cCusDefine13 decimal(18,2) NULL COMMENT '客户自定义项13',
    MODIFY COLUMN cCusDefine14 decimal(18,2) NULL COMMENT '客户自定义项14',
    MODIFY COLUMN cCusDefine15 datetime NULL COMMENT '客户自定义项15',
    MODIFY COLUMN cCusDefine16 datetime NULL COMMENT '客户自定义项16',
    MODIFY COLUMN cInvoiceCompany varchar(255) NULL COMMENT '开票单位',
    MODIFY COLUMN bCredit tinyint NULL DEFAULT 0 COMMENT '是否控制信用',
    MODIFY COLUMN bCreditDate tinyint NULL DEFAULT 0 COMMENT '是否控制信用期限',
    MODIFY COLUMN bCreditByHead tinyint NULL DEFAULT 0 COMMENT '是否按总公司控制信用',
    MODIFY COLUMN cMemo varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN fCommisionRate decimal(18,2) NULL COMMENT '佣金比率(%)',
    MODIFY COLUMN fInsueRate decimal(18,2) NULL COMMENT '保险费率(%)',
    MODIFY COLUMN CustomerKCode varchar(255) NULL COMMENT '客户级别编码',
    MODIFY COLUMN bCusState tinyint NULL DEFAULT 0 COMMENT '是否成交',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '客户档案表';

ALTER TABLE gl_vender
    MODIFY COLUMN cVenCode varchar(255) NOT NULL COMMENT '供应商编码',
    MODIFY COLUMN cVenName varchar(255) NOT NULL COMMENT '供应商名称',
    MODIFY COLUMN cVenAbbName varchar(255) NULL COMMENT '供应商简称',
    MODIFY COLUMN cVCCode varchar(255) NULL COMMENT '供应商分类编码',
    MODIFY COLUMN cTrade varchar(255) NULL COMMENT '所属行业',
    MODIFY COLUMN cVenAddress varchar(255) NULL COMMENT '地址',
    MODIFY COLUMN cVenRegCode varchar(255) NULL COMMENT '纳税人登记号',
    MODIFY COLUMN cVenBank varchar(255) NULL COMMENT '开户银行',
    MODIFY COLUMN cVenAccount varchar(255) NULL COMMENT '银行账号',
    MODIFY COLUMN cVenBankNub varchar(255) NULL COMMENT '银行行号',
    MODIFY COLUMN receipt_account_name varchar(255) NULL COMMENT '收款开户名',
    MODIFY COLUMN receipt_bank_province varchar(64) NULL COMMENT '收款开户省',
    MODIFY COLUMN receipt_bank_city varchar(64) NULL COMMENT '收款开户市',
    MODIFY COLUMN receipt_branch_code varchar(64) NULL COMMENT '收款分支行编码',
    MODIFY COLUMN receipt_branch_name varchar(255) NULL COMMENT '收款分支行名称',
    MODIFY COLUMN cVenPerson varchar(255) NULL COMMENT '联系人',
    MODIFY COLUMN cVenPhone varchar(255) NULL COMMENT '电话',
    MODIFY COLUMN cVenHand varchar(255) NULL COMMENT '手机',
    MODIFY COLUMN cVenEmail varchar(255) NULL COMMENT 'Email地址',
    MODIFY COLUMN company_id varchar(255) NULL COMMENT '公司主体编码',
    MODIFY COLUMN cMemo varchar(255) NULL COMMENT '备注',
    MODIFY COLUMN dEndDate datetime NULL COMMENT '停用日期',
    MODIFY COLUMN bBusinessDate tinyint NULL DEFAULT 0 COMMENT '经营许可证是否期限管理',
    MODIFY COLUMN bLicenceDate tinyint NULL DEFAULT 0 COMMENT '营业执照是否期限管理',
    MODIFY COLUMN bPassGMP tinyint NULL DEFAULT 0 COMMENT '是否通过GMP认证',
    MODIFY COLUMN bProxyDate tinyint NULL DEFAULT 0 COMMENT '法人委托书是否期限管理',
    MODIFY COLUMN bProxyForeign tinyint NULL DEFAULT 0 COMMENT '是否委外',
    MODIFY COLUMN bVenCargo tinyint NULL DEFAULT 0 COMMENT '是否货物',
    MODIFY COLUMN bVenService tinyint NULL DEFAULT 0 COMMENT '是否服务',
    MODIFY COLUMN bVenTax tinyint NULL DEFAULT 0 COMMENT '单价是否含税',
    MODIFY COLUMN cBarCode varchar(255) NULL COMMENT '对应条形码',
    MODIFY COLUMN cCreatePerson varchar(255) NULL COMMENT '建档人',
    MODIFY COLUMN cDCCode varchar(255) NULL COMMENT '地区编码',
    MODIFY COLUMN cModifyPerson varchar(255) NULL COMMENT '变更人',
    MODIFY COLUMN cRelCustomer varchar(255) NULL COMMENT '对应客户',
    MODIFY COLUMN cVenBankCode varchar(255) NULL COMMENT '所属银行编码',
    MODIFY COLUMN cVenBP varchar(255) NULL COMMENT '呼机',
    MODIFY COLUMN cVenDefine10 varchar(255) NULL COMMENT '供应商自定义项10',
    MODIFY COLUMN cVenDefine11 int NULL COMMENT '供应商自定义项11',
    MODIFY COLUMN cVenDefine12 int NULL COMMENT '供应商自定义项12',
    MODIFY COLUMN cVenDefine13 decimal(18,2) NULL COMMENT '供应商自定义项13',
    MODIFY COLUMN cVenDefine14 decimal(18,2) NULL COMMENT '供应商自定义项14',
    MODIFY COLUMN cVenDefine15 datetime NULL COMMENT '供应商自定义项15',
    MODIFY COLUMN cVenDefine16 datetime NULL COMMENT '供应商自定义项16',
    MODIFY COLUMN cVenDefine3 varchar(255) NULL COMMENT '供应商自定义项3',
    MODIFY COLUMN cVenDefine4 varchar(255) NULL COMMENT '供应商自定义项4',
    MODIFY COLUMN cVenDefine5 varchar(255) NULL COMMENT '供应商自定义项5',
    MODIFY COLUMN cVenDefine6 varchar(255) NULL COMMENT '供应商自定义项6',
    MODIFY COLUMN cVenDefine7 varchar(255) NULL COMMENT '供应商自定义项7',
    MODIFY COLUMN cVenDefine8 varchar(255) NULL COMMENT '供应商自定义项8',
    MODIFY COLUMN cVenDefine9 varchar(255) NULL COMMENT '供应商自定义项9',
    MODIFY COLUMN cVenDepart varchar(255) NULL COMMENT '分管部门',
    MODIFY COLUMN cVenFax varchar(255) NULL COMMENT '传真',
    MODIFY COLUMN cVenHeadCode varchar(255) NULL COMMENT '供应商总公司编码',
    MODIFY COLUMN cVenIAddress varchar(255) NULL COMMENT '到货地址',
    MODIFY COLUMN cVenIType varchar(255) NULL COMMENT '到货方式',
    MODIFY COLUMN cVenLPerson varchar(255) NULL COMMENT '法人',
    MODIFY COLUMN cVenPayCond varchar(255) NULL COMMENT '付款条件编码',
    MODIFY COLUMN cVenPostCode varchar(255) NULL COMMENT '邮政编码',
    MODIFY COLUMN cVenPPerson varchar(255) NULL COMMENT '专营业务员',
    MODIFY COLUMN cVenTradeCCode varchar(255) NULL COMMENT '行业编码',
    MODIFY COLUMN cVenWhCode varchar(255) NULL COMMENT '到货仓库',
    MODIFY COLUMN dBusinessEDate datetime NULL COMMENT '经营许可证到期日期',
    MODIFY COLUMN dBusinessSDate datetime NULL COMMENT '经营许可证生效日期',
    MODIFY COLUMN dLastDate datetime NULL COMMENT '最后交易日期',
    MODIFY COLUMN dLicenceEDate datetime NULL COMMENT '营业执照到期日期',
    MODIFY COLUMN dLicenceSDate datetime NULL COMMENT '营业执照生效日期',
    MODIFY COLUMN dLRDate datetime NULL COMMENT '最后付款日期',
    MODIFY COLUMN dModifyDate datetime NULL COMMENT '变更日期',
    MODIFY COLUMN dProxyEDate datetime NULL COMMENT '法人委托书到期日期',
    MODIFY COLUMN dProxySDate datetime NULL COMMENT '法人委托书生效日期',
    MODIFY COLUMN dVenDevDate datetime NULL COMMENT '发展日期',
    MODIFY COLUMN fRegistFund decimal(18,2) NULL COMMENT '注册资金',
    MODIFY COLUMN iAPMoney decimal(18,2) NULL COMMENT '应付余额',
    MODIFY COLUMN iBusinessADays int NULL COMMENT '经营许可证预警天数',
    MODIFY COLUMN iEmployeeNum int NULL COMMENT '员工人数',
    MODIFY COLUMN iFrequency int NULL COMMENT '使用频度',
    MODIFY COLUMN iGradeABC smallint NULL COMMENT 'ABC等级',
    MODIFY COLUMN iId int NULL COMMENT '所属权限组',
    MODIFY COLUMN iLastMoney decimal(18,2) NULL COMMENT '最后交易金额',
    MODIFY COLUMN iLicenceADays int NULL COMMENT '营业执照预警天数',
    MODIFY COLUMN iLRMoney decimal(18,2) NULL COMMENT '最后付款金额',
    MODIFY COLUMN iProxyADays int NULL COMMENT '法人委托书预警天数',
    MODIFY COLUMN iVenCreDate int NULL COMMENT '信用期限',
    MODIFY COLUMN iVenCreGrade varchar(255) NULL COMMENT '信用等级',
    MODIFY COLUMN iVenCreLine decimal(18,2) NULL COMMENT '信用额度',
    MODIFY COLUMN iVenDisRate decimal(18,2) NULL COMMENT '扣率',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '供应商档案表';

ALTER TABLE pm_bank_payment_record
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN task_id bigint NOT NULL COMMENT '任务ID',
    MODIFY COLUMN document_code varchar(64) NOT NULL COMMENT '单据编码',
    MODIFY COLUMN company_bank_account_id bigint NULL COMMENT '公司银行账户ID',
    MODIFY COLUMN bank_provider varchar(64) NOT NULL COMMENT '银行提供方',
    MODIFY COLUMN bank_channel varchar(64) NOT NULL COMMENT '银行支付渠道',
    MODIFY COLUMN manual_paid tinyint NOT NULL DEFAULT 0 COMMENT '是否人工标记付款:1是 0否',
    MODIFY COLUMN push_request_no varchar(128) NULL COMMENT '推送请求号',
    MODIFY COLUMN bank_order_no varchar(128) NULL COMMENT '银行订单号',
    MODIFY COLUMN bank_flow_no varchar(128) NULL COMMENT '银行流水号',
    MODIFY COLUMN push_payload_json longtext NULL COMMENT '推送请求载荷JSON',
    MODIFY COLUMN push_result_json longtext NULL COMMENT '推送结果JSON',
    MODIFY COLUMN callback_payload_json longtext NULL COMMENT '回调载荷JSON',
    MODIFY COLUMN callback_received_at datetime NULL COMMENT '回调接收时间',
    MODIFY COLUMN paid_at datetime NULL COMMENT '付款时间',
    MODIFY COLUMN receipt_status varchar(64) NULL COMMENT '回单状态',
    MODIFY COLUMN receipt_received_at datetime NULL COMMENT '回单接收时间',
    MODIFY COLUMN last_receipt_query_at datetime NULL COMMENT '最近回单查询时间',
    MODIFY COLUMN receipt_query_count int NOT NULL DEFAULT 0 COMMENT '回单查询次数',
    MODIFY COLUMN receipt_attachment_id varchar(64) NULL COMMENT '回单附件ID',
    MODIFY COLUMN receipt_file_name varchar(255) NULL COMMENT '回单文件名',
    MODIFY COLUMN receipt_result_json longtext NULL COMMENT '回单结果JSON',
    MODIFY COLUMN last_error_message varchar(1000) NULL COMMENT '最近错误信息',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '银行付款跟踪记录表';

ALTER TABLE pm_custom_archive_rule
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '自动划分规则ID',
    MODIFY COLUMN archive_item_id bigint NOT NULL COMMENT '归属结果项ID',
    MODIFY COLUMN group_no int NOT NULL DEFAULT 1 COMMENT '规则组号，同组条件为且、组间为或',
    MODIFY COLUMN field_key varchar(64) NOT NULL COMMENT '匹配字段标识',
    MODIFY COLUMN operator varchar(32) NOT NULL COMMENT '比较运算符:EQ/NE/IN/NOT_IN/GT/BETWEEN/CONTAINS',
    MODIFY COLUMN compare_value varchar(500) NULL COMMENT '比较值，按JSON序列化存储',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '自定义档案自动划分规则表';

ALTER TABLE pm_document_relation
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN source_document_code varchar(64) NOT NULL COMMENT '源单据编码',
    MODIFY COLUMN source_field_key varchar(128) NOT NULL COMMENT '源字段标识',
    MODIFY COLUMN target_document_code varchar(64) NOT NULL COMMENT '目标单据编码',
    MODIFY COLUMN target_template_type varchar(32) NOT NULL COMMENT '目标模板类型',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 1 COMMENT '排序号',
    MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'ACTIVE' COMMENT '状态:ACTIVE启用/DISABLED停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '单据关联关系表';

ALTER TABLE pm_document_task
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '审批任务ID',
    MODIFY COLUMN document_code varchar(64) NOT NULL COMMENT '单据编码',
    MODIFY COLUMN node_key varchar(64) NOT NULL COMMENT '节点key',
    MODIFY COLUMN node_name varchar(100) NULL COMMENT '节点名称',
    MODIFY COLUMN node_type varchar(32) NOT NULL COMMENT '节点类型',
    MODIFY COLUMN assignee_user_id bigint NOT NULL COMMENT '处理人用户ID',
    MODIFY COLUMN assignee_name varchar(100) NULL COMMENT '处理人姓名',
    MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '任务状态',
    MODIFY COLUMN task_batch_no varchar(64) NOT NULL COMMENT '同节点同批次任务号',
    MODIFY COLUMN approval_mode varchar(32) NULL COMMENT '审批模式',
    MODIFY COLUMN task_kind varchar(32) NULL COMMENT '任务类型',
    MODIFY COLUMN source_task_id bigint NULL COMMENT '来源任务ID',
    MODIFY COLUMN action_comment varchar(500) NULL COMMENT '处理意见',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN handled_at datetime NULL COMMENT '处理时间',
    COMMENT = '审批任务表';

ALTER TABLE pm_document_template
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '模板ID',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN template_code varchar(64) NOT NULL COMMENT '模板编码',
    MODIFY COLUMN template_name varchar(100) NOT NULL COMMENT '模板名称',
    MODIFY COLUMN template_type varchar(32) NOT NULL COMMENT '模板类型:report/application/loan',
    MODIFY COLUMN template_type_label varchar(32) NOT NULL COMMENT '模板类型中文名',
    MODIFY COLUMN category_code varchar(64) NOT NULL COMMENT '分类编码',
    MODIFY COLUMN template_description varchar(500) NULL COMMENT '模板说明',
    MODIFY COLUMN numbering_rule varchar(64) NULL COMMENT '编号规则',
    MODIFY COLUMN form_design_code varchar(64) NULL COMMENT '表单设计编码',
    MODIFY COLUMN expense_detail_design_code varchar(64) NULL COMMENT '费用明细设计编码',
    MODIFY COLUMN icon_color varchar(32) NULL DEFAULT 'blue' COMMENT '图标颜色',
    MODIFY COLUMN enabled tinyint NULL DEFAULT 1 COMMENT '是否启用',
    MODIFY COLUMN publish_status varchar(16) NULL DEFAULT 'ENABLED' COMMENT '发布状态',
    MODIFY COLUMN print_mode varchar(64) NULL COMMENT '打印方式',
    MODIFY COLUMN approval_flow varchar(64) NULL COMMENT '审批流程编码',
    MODIFY COLUMN flow_name varchar(100) NULL COMMENT '审批流程名称',
    MODIFY COLUMN payment_mode varchar(64) NULL COMMENT '付款联动模式',
    MODIFY COLUMN split_payment tinyint NULL DEFAULT 0 COMMENT '是否支持分期付款:1是 0否',
    MODIFY COLUMN travel_form varchar(64) NULL COMMENT '出差申请配置',
    MODIFY COLUMN allocation_form varchar(64) NULL COMMENT '分摊表单',
    MODIFY COLUMN ai_audit_mode varchar(64) NULL DEFAULT 'disabled' COMMENT 'AI审核模式',
    MODIFY COLUMN relation_remark varchar(500) NULL COMMENT '关联规则说明',
    MODIFY COLUMN validation_remark varchar(500) NULL COMMENT '校验规则说明',
    MODIFY COLUMN installment_remark varchar(500) NULL COMMENT '分期付款说明',
    MODIFY COLUMN highlights varchar(500) NULL COMMENT '卡片亮点，使用|分隔',
    MODIFY COLUMN owner_name varchar(64) NULL COMMENT '负责人姓名',
    MODIFY COLUMN sort_order int NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN created_at datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    MODIFY COLUMN expense_detail_mode_default varchar(32) NULL COMMENT '企业往来默认模式',
    COMMENT = '单据流程模板表';

ALTER TABLE pm_document_write_off
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN source_document_code varchar(64) NOT NULL COMMENT '源单据编码',
    MODIFY COLUMN source_field_key varchar(128) NOT NULL COMMENT '源字段标识',
    MODIFY COLUMN target_document_code varchar(64) NOT NULL COMMENT '目标单据编码',
    MODIFY COLUMN target_template_type varchar(32) NOT NULL COMMENT '目标模板类型',
    MODIFY COLUMN writeoff_source_kind varchar(32) NOT NULL COMMENT '核销来源类型',
    MODIFY COLUMN requested_amount decimal(18,2) NOT NULL DEFAULT 0.00 COMMENT '申请金额',
    MODIFY COLUMN effective_amount decimal(18,2) NULL COMMENT '生效金额',
    MODIFY COLUMN available_snapshot_amount decimal(18,2) NULL COMMENT '可用快照金额',
    MODIFY COLUMN remaining_snapshot_amount decimal(18,2) NULL COMMENT '剩余快照金额',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 1 COMMENT '排序号',
    MODIFY COLUMN status varchar(32) NOT NULL DEFAULT 'PENDING_EFFECTIVE' COMMENT '状态:PENDING_EFFECTIVE待生效/EFFECTIVE已生效/CANCELLED已取消',
    MODIFY COLUMN effective_at datetime NULL COMMENT '生效时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '单据核销关系表';

ALTER TABLE pm_form_design
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '表单设计ID',
    MODIFY COLUMN form_code varchar(64) NOT NULL COMMENT '表单设计编码',
    MODIFY COLUMN form_name varchar(100) NOT NULL COMMENT '表单设计名称',
    MODIFY COLUMN template_type varchar(32) NOT NULL COMMENT '适用模板类型:report/application/loan',
    MODIFY COLUMN form_description varchar(500) NULL COMMENT '表单设计说明',
    MODIFY COLUMN schema_json longtext NULL COMMENT '表单结构定义JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '表单设计表';

ALTER TABLE pm_process_flow_node
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '节点ID',
    MODIFY COLUMN version_id bigint NOT NULL COMMENT '所属流程版本ID',
    MODIFY COLUMN node_key varchar(64) NOT NULL COMMENT '节点唯一标识',
    MODIFY COLUMN node_type varchar(32) NOT NULL COMMENT '节点类型:APPROVAL审批/CC抄送/PAYMENT支付/BRANCH分支',
    MODIFY COLUMN node_name varchar(100) NOT NULL COMMENT '节点名称',
    MODIFY COLUMN scene_id bigint NULL COMMENT '关联场景ID，仅分支节点可选',
    MODIFY COLUMN parent_node_key varchar(64) NULL COMMENT '父容器节点标识',
    MODIFY COLUMN display_order int NOT NULL DEFAULT 0 COMMENT '节点显示顺序',
    MODIFY COLUMN config_json longtext NULL COMMENT '节点配置JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程节点表';

ALTER TABLE pm_process_flow_route
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '路由ID',
    MODIFY COLUMN version_id bigint NOT NULL COMMENT '所属流程版本ID',
    MODIFY COLUMN route_key varchar(64) NOT NULL COMMENT '路由唯一标识',
    MODIFY COLUMN source_node_key varchar(64) NOT NULL COMMENT '来源节点标识',
    MODIFY COLUMN target_node_key varchar(64) NULL COMMENT '目标节点标识，为空表示流转结束',
    MODIFY COLUMN route_name varchar(100) NOT NULL COMMENT '路由名称',
    MODIFY COLUMN priority int NOT NULL DEFAULT 1 COMMENT '路由优先级，值越小越先匹配',
    MODIFY COLUMN default_route tinyint NOT NULL DEFAULT 0 COMMENT '是否默认路由:1是 0否',
    MODIFY COLUMN condition_json longtext NULL COMMENT '路由条件组JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程路由表';

ALTER TABLE pm_process_flow_scene
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '场景ID',
    MODIFY COLUMN scene_code varchar(64) NOT NULL COMMENT '场景编码',
    MODIFY COLUMN scene_name varchar(100) NOT NULL COMMENT '场景名称',
    MODIFY COLUMN scene_description varchar(500) NULL COMMENT '场景说明',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程场景表';

ALTER TABLE pm_process_flow_version
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '流程版本ID',
    MODIFY COLUMN flow_id bigint NOT NULL COMMENT '所属流程ID',
    MODIFY COLUMN version_no int NOT NULL COMMENT '版本号',
    MODIFY COLUMN version_status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态:DRAFT草稿/PUBLISHED已发布/HISTORY历史版本',
    MODIFY COLUMN snapshot_json longtext NULL COMMENT '流程快照JSON',
    MODIFY COLUMN published_at datetime NULL COMMENT '发布时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程版本表';

ALTER TABLE sys_bank_branch_catalog
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    MODIFY COLUMN bank_code varchar(64) NOT NULL COMMENT '银行编码',
    MODIFY COLUMN bank_name varchar(200) NOT NULL COMMENT '银行名称',
    MODIFY COLUMN province varchar(64) NOT NULL COMMENT '开户省',
    MODIFY COLUMN city varchar(64) NOT NULL COMMENT '开户市',
    MODIFY COLUMN branch_code varchar(64) NOT NULL COMMENT '分支行编码',
    MODIFY COLUMN branch_name varchar(200) NOT NULL COMMENT '分支行名称',
    MODIFY COLUMN cnaps_code varchar(64) NULL COMMENT '联行号',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '国内银行联行目录表';

ALTER TABLE sys_bank_catalog
    MODIFY COLUMN bank_code varchar(64) NOT NULL COMMENT '银行编码',
    MODIFY COLUMN bank_name varchar(200) NOT NULL COMMENT '银行名称',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '国内银行目录表';

ALTER TABLE sys_department
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '部门ID',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN dept_code varchar(64) NOT NULL COMMENT '部门编码',
    MODIFY COLUMN leader_user_id bigint NULL COMMENT '部门负责人用户ID',
    MODIFY COLUMN dept_name varchar(128) NOT NULL COMMENT '部门名称',
    MODIFY COLUMN parent_id bigint NULL COMMENT '上级部门ID',
    MODIFY COLUMN wecom_department_id varchar(100) NULL COMMENT '企微部门ID',
    MODIFY COLUMN dingtalk_department_id varchar(100) NULL COMMENT '钉钉部门ID',
    MODIFY COLUMN feishu_department_id varchar(100) NULL COMMENT '飞书部门ID',
    MODIFY COLUMN sync_source varchar(32) NULL COMMENT '同步来源:MANUAL/WECOM/DINGTALK/FEISHU/MIXED',
    MODIFY COLUMN sync_enabled tinyint NOT NULL DEFAULT 1 COMMENT '是否启用同步',
    MODIFY COLUMN sync_managed tinyint NOT NULL DEFAULT 0 COMMENT '是否纳入同步管理:1是 0否',
    MODIFY COLUMN sync_status varchar(32) NULL COMMENT '同步状态',
    MODIFY COLUMN sync_remark varchar(500) NULL COMMENT '同步备注',
    MODIFY COLUMN stat_department_belong varchar(100) NULL COMMENT '统计部门归属',
    MODIFY COLUMN stat_region_belong varchar(100) NULL COMMENT '统计大区归属',
    MODIFY COLUMN stat_area_belong varchar(100) NULL COMMENT '统计区域归属',
    MODIFY COLUMN last_sync_at datetime NULL COMMENT '最近同步时间',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN sort_order int NOT NULL DEFAULT 0 COMMENT '排序号',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '全局部门树主数据表';

ALTER TABLE sys_user
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '用户ID',
    MODIFY COLUMN username varchar(50) NOT NULL COMMENT '用户名',
    MODIFY COLUMN password varchar(64) NOT NULL COMMENT '密码(MD5)',
    MODIFY COLUMN name varchar(50) NULL COMMENT '姓名',
    MODIFY COLUMN phone varchar(20) NULL COMMENT '手机号',
    MODIFY COLUMN email varchar(100) NULL COMMENT '邮箱',
    MODIFY COLUMN dept_id bigint NULL COMMENT '部门ID',
    MODIFY COLUMN position varchar(50) NULL COMMENT '岗位',
    MODIFY COLUMN labor_relation_belong varchar(100) NULL COMMENT '劳动关系归属',
    MODIFY COLUMN stat_department_belong varchar(100) NULL COMMENT '统计部门归属',
    MODIFY COLUMN stat_region_belong varchar(100) NULL COMMENT '统计大区归属',
    MODIFY COLUMN stat_area_belong varchar(100) NULL COMMENT '统计区域归属',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN status tinyint NULL DEFAULT 1 COMMENT '状态:1正常 0停用',
    MODIFY COLUMN source_type varchar(32) NULL COMMENT '来源类型',
    MODIFY COLUMN sync_managed tinyint NOT NULL DEFAULT 0 COMMENT '是否纳入同步管理:1是 0否',
    MODIFY COLUMN wecom_user_id varchar(100) NULL COMMENT '企微用户ID',
    MODIFY COLUMN dingtalk_user_id varchar(100) NULL COMMENT '钉钉用户ID',
    MODIFY COLUMN feishu_user_id varchar(100) NULL COMMENT '飞书用户ID',
    MODIFY COLUMN last_sync_at datetime NULL COMMENT '最近同步时间',
    MODIFY COLUMN created_at datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '用户表';

ALTER TABLE sys_user_bank_account
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '银行账户ID',
    MODIFY COLUMN user_id bigint NOT NULL COMMENT '用户ID',
    MODIFY COLUMN company_id varchar(64) NULL COMMENT '公司主体编码',
    MODIFY COLUMN bank_name varchar(100) NOT NULL COMMENT '银行名称',
    MODIFY COLUMN branch_name varchar(100) NULL COMMENT '支行名称',
    MODIFY COLUMN bank_code varchar(64) NULL COMMENT '开户银行编码',
    MODIFY COLUMN branch_code varchar(64) NULL COMMENT '分支行编码',
    MODIFY COLUMN cnaps_code varchar(64) NULL COMMENT '联行号',
    MODIFY COLUMN province varchar(64) NULL COMMENT '开户省',
    MODIFY COLUMN city varchar(64) NULL COMMENT '开户市',
    MODIFY COLUMN account_name varchar(100) NOT NULL COMMENT '科目名称',
    MODIFY COLUMN account_no varchar(50) NOT NULL COMMENT '银行卡号',
    MODIFY COLUMN account_type varchar(50) NULL DEFAULT '对私账户' COMMENT '账户类型',
    MODIFY COLUMN default_account tinyint NULL DEFAULT 0 COMMENT '是否默认账户',
    MODIFY COLUMN status tinyint NULL DEFAULT 1 COMMENT '状态',
    MODIFY COLUMN created_at datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '用户银行卡表';
