USE finex_db;

SET NAMES utf8mb4;

ALTER TABLE pm_custom_archive_design
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自定义档案ID',
    MODIFY COLUMN archive_code VARCHAR(64) NOT NULL COMMENT '档案编码',
    MODIFY COLUMN archive_name VARCHAR(64) NOT NULL COMMENT '档案名称',
    MODIFY COLUMN archive_type VARCHAR(32) NOT NULL COMMENT '档案类型:SELECT可选档案/AUTO_RULE自动划分',
    MODIFY COLUMN archive_description VARCHAR(255) NULL COMMENT '档案说明',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_custom_archive_item
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '档案结果项ID',
    MODIFY COLUMN archive_id BIGINT NOT NULL COMMENT '所属档案ID',
    MODIFY COLUMN item_code VARCHAR(64) NOT NULL COMMENT '结果项编码',
    MODIFY COLUMN item_name VARCHAR(64) NOT NULL COMMENT '结果项名称',
    MODIFY COLUMN priority INT NULL DEFAULT 1 COMMENT '优先级，值越小越靠前',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_custom_archive_rule
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '自动划分规则ID',
    MODIFY COLUMN archive_item_id BIGINT NOT NULL COMMENT '归属结果项ID',
    MODIFY COLUMN group_no INT NOT NULL DEFAULT 1 COMMENT '规则组号，同组条件为且、组间为或',
    MODIFY COLUMN field_key VARCHAR(64) NOT NULL COMMENT '匹配字段标识',
    MODIFY COLUMN operator VARCHAR(32) NOT NULL COMMENT '比较运算符:EQ/NE/IN/NOT_IN/GT/BETWEEN/CONTAINS',
    MODIFY COLUMN compare_value VARCHAR(500) NULL COMMENT '比较值，按JSON序列化存储',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_expense_detail_design
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '费用明细设计ID',
    MODIFY COLUMN detail_code VARCHAR(64) NOT NULL COMMENT '明细设计编码',
    MODIFY COLUMN detail_name VARCHAR(64) NOT NULL COMMENT '明细设计名称',
    MODIFY COLUMN detail_type VARCHAR(32) NOT NULL COMMENT '明细类型:NORMAL_REIMBURSEMENT普通报销/ENTERPRISE_TRANSACTION企业往来',
    MODIFY COLUMN detail_description VARCHAR(500) NULL COMMENT '明细设计说明',
    MODIFY COLUMN schema_json LONGTEXT NULL COMMENT '明细表单结构定义JSON',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_document_expense_detail
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '费用明细实例ID',
    MODIFY COLUMN document_code VARCHAR(64) NOT NULL COMMENT '所属单据编码',
    MODIFY COLUMN detail_no VARCHAR(64) NOT NULL COMMENT '明细编号',
    MODIFY COLUMN detail_design_code VARCHAR(64) NOT NULL COMMENT '明细设计编码',
    MODIFY COLUMN detail_type VARCHAR(32) NOT NULL COMMENT '明细类型:NORMAL_REIMBURSEMENT普通报销/ENTERPRISE_TRANSACTION企业往来',
    MODIFY COLUMN enterprise_mode VARCHAR(32) NULL COMMENT '企业往来模式:PREPAY_UNBILLED预付未开票/INVOICE_FULL_PAYMENT到票全额付款',
    MODIFY COLUMN expense_type_code VARCHAR(64) NULL COMMENT '费用类型编码',
    MODIFY COLUMN business_scene_mode VARCHAR(32) NULL COMMENT '业务场景模式:PREPAY_UNBILLED预付未开票/INVOICE_FULL_PAYMENT到票全额付款',
    MODIFY COLUMN detail_title VARCHAR(128) NULL COMMENT '明细标题',
    MODIFY COLUMN sort_order INT NOT NULL DEFAULT 1 COMMENT '明细排序号',
    MODIFY COLUMN invoice_amount DECIMAL(18,2) NULL COMMENT '发票金额',
    MODIFY COLUMN actual_payment_amount DECIMAL(18,2) NULL COMMENT '实付金额',
    MODIFY COLUMN pending_write_off_amount DECIMAL(18,2) NULL COMMENT '待核销金额',
    MODIFY COLUMN schema_snapshot_json LONGTEXT NOT NULL COMMENT '明细设计快照JSON',
    MODIFY COLUMN form_data_json LONGTEXT NOT NULL COMMENT '明细表单数据JSON',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_form_design
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '表单设计ID',
    MODIFY COLUMN form_code VARCHAR(64) NOT NULL COMMENT '表单设计编码',
    MODIFY COLUMN form_name VARCHAR(64) NOT NULL COMMENT '表单设计名称',
    MODIFY COLUMN template_type VARCHAR(32) NOT NULL COMMENT '适用模板类型:report/application/loan',
    MODIFY COLUMN form_description VARCHAR(500) NULL COMMENT '表单设计说明',
    MODIFY COLUMN schema_json LONGTEXT NULL COMMENT '表单结构定义JSON',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_process_flow
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '流程ID',
    MODIFY COLUMN flow_code VARCHAR(64) NOT NULL COMMENT '流程编码',
    MODIFY COLUMN flow_name VARCHAR(64) NOT NULL COMMENT '流程名称',
    MODIFY COLUMN flow_description VARCHAR(500) NULL COMMENT '流程说明',
    MODIFY COLUMN status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '流程状态:DRAFT草稿/ENABLED启用/DISABLED停用',
    MODIFY COLUMN current_draft_version_id BIGINT NULL COMMENT '当前草稿版本ID',
    MODIFY COLUMN current_published_version_id BIGINT NULL COMMENT '当前已发布版本ID',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_process_flow_scene
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '场景ID',
    MODIFY COLUMN scene_code VARCHAR(64) NOT NULL COMMENT '场景编码',
    MODIFY COLUMN scene_name VARCHAR(64) NOT NULL COMMENT '场景名称',
    MODIFY COLUMN scene_description VARCHAR(500) NULL COMMENT '场景说明',
    MODIFY COLUMN status TINYINT NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_process_flow_version
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '流程版本ID',
    MODIFY COLUMN flow_id BIGINT NOT NULL COMMENT '所属流程ID',
    MODIFY COLUMN version_no INT NOT NULL COMMENT '版本号',
    MODIFY COLUMN version_status VARCHAR(16) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态:DRAFT草稿/PUBLISHED已发布/HISTORY历史版本',
    MODIFY COLUMN snapshot_json LONGTEXT NULL COMMENT '流程快照JSON',
    MODIFY COLUMN published_at DATETIME NULL COMMENT '发布时间',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_process_flow_node
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '节点ID',
    MODIFY COLUMN version_id BIGINT NOT NULL COMMENT '所属流程版本ID',
    MODIFY COLUMN node_key VARCHAR(64) NOT NULL COMMENT '节点唯一标识',
    MODIFY COLUMN node_type VARCHAR(32) NOT NULL COMMENT '节点类型:APPROVAL审批/CC抄送/PAYMENT支付/BRANCH分支',
    MODIFY COLUMN node_name VARCHAR(64) NOT NULL COMMENT '节点名称',
    MODIFY COLUMN scene_id BIGINT NULL COMMENT '关联场景ID，仅分支节点可选',
    MODIFY COLUMN parent_node_key VARCHAR(64) NULL COMMENT '父容器节点标识',
    MODIFY COLUMN display_order INT NOT NULL DEFAULT 0 COMMENT '节点显示顺序',
    MODIFY COLUMN config_json LONGTEXT NULL COMMENT '节点配置JSON',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

ALTER TABLE pm_process_flow_route
    MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '路由ID',
    MODIFY COLUMN version_id BIGINT NOT NULL COMMENT '所属流程版本ID',
    MODIFY COLUMN route_key VARCHAR(64) NOT NULL COMMENT '路由唯一标识',
    MODIFY COLUMN source_node_key VARCHAR(64) NOT NULL COMMENT '来源节点标识',
    MODIFY COLUMN target_node_key VARCHAR(64) NULL COMMENT '目标节点标识，为空表示流转结束',
    MODIFY COLUMN route_name VARCHAR(64) NOT NULL COMMENT '路由名称',
    MODIFY COLUMN priority INT NOT NULL DEFAULT 1 COMMENT '路由优先级，值越小越先匹配',
    MODIFY COLUMN default_route TINYINT NOT NULL DEFAULT 0 COMMENT '是否默认路由:1是 0否',
    MODIFY COLUMN condition_json LONGTEXT NULL COMMENT '路由条件组JSON',
    MODIFY COLUMN created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';

-- comment standardization begin
ALTER TABLE pm_custom_archive_rule
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '自动划分规则ID',
    MODIFY COLUMN archive_item_id bigint NOT NULL COMMENT '归属结果项ID',
    MODIFY COLUMN group_no int NOT NULL DEFAULT 1 COMMENT '规则组号，同组条件为且、组间为或',
    MODIFY COLUMN field_key varchar(64) NOT NULL COMMENT '匹配字段标识',
    MODIFY COLUMN operator varchar(32) NOT NULL COMMENT '比较运算符:EQ/NE/IN/NOT_IN/GT/BETWEEN/CONTAINS',
    MODIFY COLUMN compare_value varchar(500) NULL COMMENT '比较值，按JSON序列化存储',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '自定义档案自动划分规则表';

ALTER TABLE pm_form_design
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '表单设计ID',
    MODIFY COLUMN form_code varchar(64) NOT NULL COMMENT '表单设计编码',
    MODIFY COLUMN form_name varchar(64) NOT NULL COMMENT '表单设计名称',
    MODIFY COLUMN template_type varchar(32) NOT NULL COMMENT '适用模板类型:report/application/loan',
    MODIFY COLUMN form_description varchar(500) NULL COMMENT '表单设计说明',
    MODIFY COLUMN schema_json longtext NULL COMMENT '表单结构定义JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '表单设计表';

ALTER TABLE pm_process_flow_node
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '节点ID',
    MODIFY COLUMN version_id bigint NOT NULL COMMENT '所属流程版本ID',
    MODIFY COLUMN node_key varchar(64) NOT NULL COMMENT '节点唯一标识',
    MODIFY COLUMN node_type varchar(32) NOT NULL COMMENT '节点类型:APPROVAL审批/CC抄送/PAYMENT支付/BRANCH分支',
    MODIFY COLUMN node_name varchar(64) NOT NULL COMMENT '节点名称',
    MODIFY COLUMN scene_id bigint NULL COMMENT '关联场景ID，仅分支节点可选',
    MODIFY COLUMN parent_node_key varchar(64) NULL COMMENT '父容器节点标识',
    MODIFY COLUMN display_order int NOT NULL DEFAULT 0 COMMENT '节点显示顺序',
    MODIFY COLUMN config_json longtext NULL COMMENT '节点配置JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程节点表';

ALTER TABLE pm_process_flow_route
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '路由ID',
    MODIFY COLUMN version_id bigint NOT NULL COMMENT '所属流程版本ID',
    MODIFY COLUMN route_key varchar(64) NOT NULL COMMENT '路由唯一标识',
    MODIFY COLUMN source_node_key varchar(64) NOT NULL COMMENT '来源节点标识',
    MODIFY COLUMN target_node_key varchar(64) NULL COMMENT '目标节点标识，为空表示流转结束',
    MODIFY COLUMN route_name varchar(64) NOT NULL COMMENT '路由名称',
    MODIFY COLUMN priority int NOT NULL DEFAULT 1 COMMENT '路由优先级，值越小越先匹配',
    MODIFY COLUMN default_route tinyint NOT NULL DEFAULT 0 COMMENT '是否默认路由:1是 0否',
    MODIFY COLUMN condition_json longtext NULL COMMENT '路由条件组JSON',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程路由表';

ALTER TABLE pm_process_flow_scene
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '场景ID',
    MODIFY COLUMN scene_code varchar(64) NOT NULL COMMENT '场景编码',
    MODIFY COLUMN scene_name varchar(64) NOT NULL COMMENT '场景名称',
    MODIFY COLUMN scene_description varchar(500) NULL COMMENT '场景说明',
    MODIFY COLUMN status tinyint NOT NULL DEFAULT 1 COMMENT '状态:1启用 0停用',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程场景表';

ALTER TABLE pm_process_flow_version
    MODIFY COLUMN id bigint NOT NULL AUTO_INCREMENT COMMENT '流程版本ID',
    MODIFY COLUMN flow_id bigint NOT NULL COMMENT '所属流程ID',
    MODIFY COLUMN version_no int NOT NULL COMMENT '版本号',
    MODIFY COLUMN version_status varchar(16) NOT NULL DEFAULT 'DRAFT' COMMENT '版本状态:DRAFT草稿/PUBLISHED已发布/HISTORY历史版本',
    MODIFY COLUMN snapshot_json longtext NULL COMMENT '流程快照JSON',
    MODIFY COLUMN published_at datetime NULL COMMENT '发布时间',
    MODIFY COLUMN created_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    MODIFY COLUMN updated_at datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    COMMENT = '流程版本表';

-- comment standardization end
